package com.misys.equation.common.internal.dao.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.ResultSetExtractor;

import com.misys.equation.common.dao.beans.SC1RecordDataModel;

/**
 * This is a helper class used by Sp framework to populate the data model.<br>
 * This class will extract data from the <code>ResultSet</code> and create a data model.
 * 
 * @author deroset
 * 
 */
public class SC1RecordResultSetExtractor implements ResultSetExtractor
{
	/**
	 * This is the unique class id used for serialisation.
	 */
	private static final long serialVersionUID = 1281524637689l;

	/**
	 * This class will extract data from the <code>ResultSet</code> and create a data model.
	 * 
	 * @param the
	 *            passed <code>ResultSet</code> which contains the data.
	 * @return a <code>SC1RecordDataModel</code> data model.
	 */
	public Object extractData(ResultSet resultSet) throws SQLException
	{
		SC1RecordDataModel record = new SC1RecordDataModel();
		record.setAccountBranch(resultSet.getString(1).trim());
		record.setBasicNumber(resultSet.getString(2).trim());
		record.setAccountSuffix(resultSet.getString(3).trim());
		record.setApplication(resultSet.getString(4).trim());
		record.setAccountStructure(resultSet.getString(5).trim());
		record.setContingent(resultSet.getString(6).trim());
		record.setInternalAccount(resultSet.getString(7).trim());
		record.setAdjustedBalanceLastNight(resultSet.getLong(8));
		record.setAdjustedBalanceLastPeriod(resultSet.getLong(9));
		record.setClosingBalance(resultSet.getLong(10));
		record.setNetClearingToday(resultSet.getLong(11));
		record.setNetClearingTomorrow(resultSet.getLong(12));
		record.setNetClearingAfterTomorrow(resultSet.getLong(13));
		record.setShadowDebits(resultSet.getLong(14));
		record.setShadowCredits(resultSet.getLong(15));
		record.setReservedBalance(resultSet.getLong(16));
		record.setDaylightReservedBalance(resultSet.getString(17).trim());
		record.setShadowAdjustments(resultSet.getLong(18));
		record.setAccountShortName(resultSet.getString(19).trim());
		record.setCustomerType(resultSet.getString(20).trim());
		record.setAcType(resultSet.getString(21).trim());
		record.setAnalysisCode(resultSet.getString(22).trim());
		record.setSundryAnalysisCode(resultSet.getString(23).trim());
		record.setNumericAnalysisCode(resultSet.getString(24).trim());
		record.setResidenceCountry(resultSet.getString(25).trim());
		record.setCcy(resultSet.getString(26).trim());
		record.setRiskCountry(resultSet.getString(27).trim());
		record.setParentCountry(resultSet.getString(28).trim());
		record.setPostageCharged(resultSet.getString(29).trim());
		record.setSecurityHeld(resultSet.getString(30).trim());
		record.setAdviseTrans(resultSet.getString(31).trim());
		record.setStoppedCheques(resultSet.getString(32).trim());
		record.setStandingOrder(resultSet.getString(33).trim());
		record.setDebitStats(resultSet.getString(34).trim());
		record.setCreditStats(resultSet.getString(35).trim());
		record.setHighBalStats(resultSet.getString(36).trim());
		record.setLowBalStats(resultSet.getString(37).trim());
		record.setDrIntStats(resultSet.getString(38).trim());
		record.setCrIntStats(resultSet.getString(39).trim());
		record.setPLStats(resultSet.getString(40).trim());
		record.setDrToStats(resultSet.getString(41).trim());
		record.setCrToStats(resultSet.getString(42).trim());
		record.setEligibleForExtSystemTransfer(resultSet.getString(43).trim());
		record.setBulk(resultSet.getString(44).trim());
		record.setSeparateInterestCharges(resultSet.getString(45).trim());
		record.setPassBook(resultSet.getString(46).trim());
		record.setTaxCharges(resultSet.getString(47).trim());
		record.setTaxInterest(resultSet.getString(48).trim());
		record.setCharges(resultSet.getString(49).trim());
		record.setBoHeld(resultSet.getString(50).trim());
		record.setFundingReceiving(resultSet.getString(51).trim());
		record.setDiaryNotesHeld(resultSet.getString(52).trim());
		record.setSpecialInstructions(resultSet.getString(53).trim());
		record.setReferCredits(resultSet.getString(54).trim());
		record.setReferDebits(resultSet.getString(55).trim());
		record.setReferCreditBalance(resultSet.getString(56).trim());
		record.setDoNotReferDrBalance(resultSet.getString(57).trim());
		record.setDeceasedOrLiquidated(resultSet.getString(58).trim());
		record.setBlocked(resultSet.getString(59).trim());
		record.setInactive(resultSet.getString(60).trim());
		record.setZeroBalanceRequired(resultSet.getString(61).trim());
		record.setClearedBalance(resultSet.getString(62).trim());
		record.setClearOnlyCredits(resultSet.getString(63).trim());
		record.setStatementFrequency(resultSet.getString(64).trim());
		record.setStatementBalance(resultSet.getLong(65));
		record.setNoPostingsNotOnStatement(resultSet.getInt(66));
		record.setLastStatementDate(resultSet.getInt(67));
		record.setLastStatementNumber(resultSet.getInt(68));
		record.setShortNameOnStatement(resultSet.getString(69).trim());
		record.setSuppressStatement(resultSet.getString(70).trim());
		record.setStatementOnlyOnFrequency(resultSet.getString(71).trim());
		record.setForceCycleStatement(resultSet.getString(72).trim());
		record.setCopyStatementToAccount(resultSet.getString(73).trim());
		record.setCopyStatementToCustomer(resultSet.getString(74).trim());
		record.setHoldStatement(resultSet.getString(75).trim());
		record.setActionStatement(resultSet.getString(76).trim());
		record.setStatementsOnPrinter2(resultSet.getString(77).trim());
		record.setConfirmationsOnPrinter2(resultSet.getString(78).trim());
		record.setSuppressConfirmations(resultSet.getString(79).trim());
		record.setSuppressAddress(resultSet.getString(80).trim());
		record.setNoStopConfirmations(resultSet.getString(81).trim());
		record.setNoStandingOrderConfirmations(resultSet.getString(82).trim());
		record.setNoBalanceOrderConfirmations(resultSet.getString(83).trim());
		record.setRetentionPeriod(resultSet.getString(84).trim());
		record.setSc080(resultSet.getString(85).trim());
		record.setSc081(resultSet.getString(86).trim());
		record.setSc082(resultSet.getString(87).trim());
		record.setSc083(resultSet.getString(88).trim());
		record.setSc084(resultSet.getString(89).trim());
		record.setSc085(resultSet.getString(90).trim());
		record.setSc086(resultSet.getString(91).trim());
		record.setSc087(resultSet.getString(92).trim());
		record.setSc090(resultSet.getString(93).trim());
		record.setSc091(resultSet.getString(94).trim());
		record.setSc092(resultSet.getString(95).trim());
		record.setSc093(resultSet.getString(96).trim());
		record.setSc094(resultSet.getString(97).trim());
		record.setSc095(resultSet.getString(98).trim());
		record.setSc096(resultSet.getString(99).trim());
		record.setSc097(resultSet.getString(100).trim());
		record.setNumberOfReconciliationChars(resultSet.getInt(101));
		record.setDateAcOpened(resultSet.getInt(102));
		record.setDateLastEntry(resultSet.getInt(103));
		record.setDateAccountClosed(resultSet.getInt(104));
		record.setTotalOverdraft(resultSet.getLong(105));
		record.setApprovedOverdraftExpiryDate(resultSet.getInt(106));
		record.setDateLastMaintained(resultSet.getInt(107));
		record.setP1Rating(resultSet.getString(108).trim());
		record.setP2Rating(resultSet.getString(109).trim());
		record.setP3Rating(resultSet.getString(110).trim());
		record.setP4Rating(resultSet.getString(111).trim());
		record.setP5Rating(resultSet.getString(112).trim());
		record.setC1Rating(resultSet.getString(113).trim());
		record.setC2Rating(resultSet.getString(114).trim());
		record.setC3Rating(resultSet.getString(115).trim());
		record.setC4Rating(resultSet.getString(116).trim());
		record.setC5Rating(resultSet.getString(117).trim());
		record.setAccountOfficer(resultSet.getString(118).trim());
		record.setLanguage(resultSet.getString(119).trim());
		record.setCapital(resultSet.getString(120).trim());
		record.setTradeDate(resultSet.getString(121).trim());
		record.setAccountClosing(resultSet.getString(122).trim());
		record.setDealInterestDaysBasis(resultSet.getString(123).trim());
		record.setNominatedAccount(resultSet.getString(124).trim());
		record.setDebitInterest(resultSet.getString(125).trim());
		record.setCreditInterest(resultSet.getString(126).trim());
		record.setCreditInterestAdjusted(resultSet.getString(127).trim());
		record.setDebitInterestAdjusted(resultSet.getString(128).trim());
		record.setAdviseRateChanges(resultSet.getString(129).trim());
		record.setAcMovedSinceReorganisation(resultSet.getString(130).trim());
		record.setGeneratedPostingsOnly(resultSet.getString(131).trim());
		record.setInterestBearing(resultSet.getString(132).trim());
		record.setMarketableSecurity(resultSet.getString(133).trim());
		record.setSc0g0(resultSet.getString(134).trim());
		record.setSc0g1(resultSet.getString(135).trim());
		record.setSc0g2(resultSet.getString(136).trim());
		record.setSc0g3(resultSet.getString(137).trim());
		record.setSc0g4(resultSet.getString(138).trim());
		record.setSc0g5(resultSet.getString(139).trim());
		record.setSc0g6(resultSet.getString(140).trim());
		record.setSc0g7(resultSet.getString(141).trim());
		record.setNetClearingLocal(resultSet.getLong(142));
		record.setPrintChargesStatement(resultSet.getString(143).trim());
		record.setChargesStatementFrequency(resultSet.getString(144).trim());
		record.setLastChargesStatementDate(resultSet.getInt(145));
		record.setNextChargesStatementDate(resultSet.getInt(146));
		record.setArabicShortName(resultSet.getString(147).trim());
		record.setMirroredArabicShortName(resultSet.getString(148).trim());
		record.setInternalRiskCountry(resultSet.getString(149).trim());
		record.setJointAc(resultSet.getString(150).trim());
		record.setIbTransactions(resultSet.getString(151).trim());
		record.setFontisAccount(resultSet.getString(152).trim());
		record.setFontisDownFreq(resultSet.getInt(153));
		record.setLastFontisStatBal(resultSet.getLong(154));
		record.setLastFontisStatNo(resultSet.getInt(155));
		record.setFontisDate(resultSet.getInt(156));
		record.setDebitBalanceNotAllowed(resultSet.getString(157).trim());
		record.setRealtimeBalanceOrder(resultSet.getString(158).trim());
		record.setNonaccrual(resultSet.getString(159).trim());
		record.setUserStatus(resultSet.getString(160).trim());
		record.setCurrentStatus(resultSet.getString(161).trim());
		record.setIntBillingAdvice(resultSet.getString(162).trim());
		record.setDiscretionaryOverdraftsEffectiveToday(resultSet.getLong(163));
		record.setApprovedOverdraftLimit(resultSet.getLong(164));
		record.setOdAgainstUcCheques(resultSet.getString(165).trim());
		record.setSuspOdUcCheques(resultSet.getString(166).trim());
		record.setDoesActive(resultSet.getString(167).trim());
		record.setNoticeAccount(resultSet.getString(168).trim());
		record.setSc190UserSpecialCondition(resultSet.getString(169).trim());
		record.setSc191UserSpecialCondition(resultSet.getString(170).trim());
		record.setSc192UserSpecialCondition(resultSet.getString(171).trim());
		record.setSc193UserSpecialCondition(resultSet.getString(172).trim());
		record.setSc194UserSpecialCondition(resultSet.getString(173).trim());
		record.setSc195UserSpecialCondition(resultSet.getString(174).trim());
		record.setSc196UserSpecialCondition(resultSet.getString(175).trim());
		record.setSc197UserSpecialCondition(resultSet.getString(176).trim());
		record.setCalculateInterestOnAverageDailyCreditBalance(resultSet.getString(177).trim());
		record.setCalculateInterestOnAverageDailyCrdrBalance(resultSet.getString(178).trim());
		record.setSuppressConsolidatedStatements(resultSet.getString(179).trim());
		record.setSuppressDetailedConsolidatedStmt(resultSet.getString(180).trim());
		record.setInterestAccrualsAtStartOfDay(resultSet.getString(181).trim());
		record.setUserDefinedInterestAccounting(resultSet.getString(182).trim());
		record.setSuppressForwardItemsOnStatements(resultSet.getString(183).trim());
		record.setSc207ReservedForFutureUse(resultSet.getString(184).trim());
		record.setSc210ReservedForFutureUse(resultSet.getString(185).trim());
		record.setSuppressChequebookConfirmation(resultSet.getString(186).trim());
		record.setDoNotIssueChequebook(resultSet.getString(187).trim());
		record.setEligibleForQueuing(resultSet.getString(188).trim());
		record.setQueueAllDebitTransaction(resultSet.getString(189).trim());
		record.setSuspendQueuedTransaction(resultSet.getString(190).trim());
		record.setCourtOrderExists(resultSet.getString(191).trim());
		record.setSc217ReservedForFutureUse(resultSet.getString(192).trim());
		record.setParallelIasAccountInUse(resultSet.getString(193).trim());
		record.setAddOverdraftConfirmations(resultSet.getString(194).trim());
		record.setSc222SelfserviceStatement(resultSet.getString(195).trim());
		record.setSc223SubjectToS24cReporting(resultSet.getString(196).trim());
		record.setAmendOverdraftConfirmation(resultSet.getString(197).trim());
		record.setIncludeInAuditLetters(resultSet.getString(198).trim());
		record.setSc226MdsAccount(resultSet.getString(199).trim());
		record.setCorporateFxLimitApplies(resultSet.getString(200).trim());
		record.setSc230ReservedForFutureUse(resultSet.getString(201).trim());
		record.setSc231ReservedForFutureUse(resultSet.getString(202).trim());
		record.setSc232ReservedForFutureUse(resultSet.getString(203).trim());
		record.setSc233ReservedForFutureUse(resultSet.getString(204).trim());
		record.setSc234ReservedForFutureUse(resultSet.getString(205).trim());
		record.setSc235ReservedForFutureUse(resultSet.getString(206).trim());
		record.setSc236ReservedForFutureUse(resultSet.getString(207).trim());
		record.setSc237ReservedForFutureUse(resultSet.getString(208).trim());
		record.setCollateralRequired(resultSet.getString(209).trim());
		record.setSourceOriginalBranch(resultSet.getString(210).trim());
		record.setOldAccountAlternativeKey(resultSet.getString(211).trim());
		record.setBranchChangeDate(resultSet.getInt(212));
		record.setLedgerBalanceInBaseCurrency(resultSet.getLong(213));
		record.setCreditShadowPostingsInBase(resultSet.getLong(214));
		record.setDebitShadowPostingsInBase(resultSet.getLong(215));
		record.setShadowAdjustmentsInBaseCurrency(resultSet.getLong(216));
		record.setNetItemsClearingTodayInBaseCurrency(resultSet.getLong(217));
		record.setNetItemsClrgNextBusDayBaseCurrency(resultSet.getLong(218));
		record.setNetItemsClrgAfterNextBusDayBaseCcy(resultSet.getLong(219));
		record.setLedgerBalanceInUserCurrency(resultSet.getLong(220));
		record.setCreditShadowPostingsInUser(resultSet.getLong(221));
		record.setDebitShadowPostingsInUser(resultSet.getLong(222));
		record.setShadowAdjustmentsInUserCurrency(resultSet.getLong(223));
		record.setNetItemsClearingTodayInUserCurrency(resultSet.getLong(224));
		record.setNetItemsClrgNextBusDayUserCurrency(resultSet.getLong(225));
		record.setNetItemsClrgAfterNextBusDayUserCcy(resultSet.getLong(226));
		record.setReservedBalanceForCollateralHoldsAssignments(resultSet.getLong(227));
		record.setYesterdaysUserDefinedIntAccounting(resultSet.getString(228).trim());
		record.setHoldQueuedAmount(resultSet.getLong(229));
		record.setCountingPeriodDefined(resultSet.getString(230).trim());
		record.setChargeStructureId(resultSet.getInt(231));
		record.setProductIdentifier(resultSet.getString(232).trim());
		record.setBundleIdentifier(resultSet.getString(233).trim());
		record.setSegmentIdentifier(resultSet.getString(234).trim());
		record.setTemporaryShadowAdjustments(resultSet.getLong(235));
		record.setTemporaryShadowAdjustmentsInBaseCurrency(resultSet.getLong(236));
		record.setTemporaryShadowAdjustmentsInUserCurrency(resultSet.getLong(237));
		record.setConfirmedSelfService(resultSet.getInt(238));
		record.setFailedSelfService(resultSet.getInt(239));
		record.setForcedSelfService(resultSet.getInt(240));
		record.setTaxAdviceType(resultSet.getString(241).trim());
		record.setTaxAdviceTypeNextYear(resultSet.getString(242).trim());

		return record;
	}
}