setLanguageLabel('GB','ACIDES','Cheque input for ARS');
setLanguageList('GB','ACIVAL',['1','2']);
setLanguageList('GB','ACIDSC',['Normal only','Inward clearing only']);
setLanguageLabel('GB','ACLDES','Account level');
setLanguageList('GB','ACLVAL',['1','2','3']);
setLanguageList('GB','ACLDSC',['One','Two','Three']);
setLanguageLabel('GB','ACNDES','Account nature');
setLanguageList('GB','ACNVAL',['A','D','L']);
setLanguageList('GB','ACNDSC',['Asset','Derived','Liability']);
setLanguageLabel('GB','ACPDES','Account closure');
setLanguageList('GB','ACPVAL',['0','1','2','3']);
setLanguageList('GB','ACPDSC',['Equation standard','Use previous period rate','Zero for final period','Delay until next profit rate approv']);
setLanguageLabel('GB','ACRDES','Account reference');
setLanguageList('GB','ACRVAL',['01','02']);
setLanguageList('GB','ACRDSC',['Receive settlement','Pay settlement']);
setLanguageLabel('GB','ACSDES','Account structure');
setLanguageList('GB','ACSVAL',['M','T','X']);
setLanguageList('GB','ACSDSC',['Movement','Term','Exchange']);
setLanguageLabel('GB','ACTDES','Action if no available balance');
setLanguageList('GB','ACTVAL',['1','2','3']);
setLanguageList('GB','ACTDSC',['Charge will be waived','Charge will be forced','Charge will be netted with the int.']);
setLanguageLabel('GB','ACYDES','Account cycle rule');
setLanguageList('GB','ACYVAL',['0','1','2','3']);
setLanguageList('GB','ACYDSC',['Use indicative rate','Latest approved profit rate','Hold until profit rate approved','Hold if between approval and end']);
setLanguageLabel('GB','AC2DES','Account reference');
setLanguageList('GB','AC2VAL',['01']);
setLanguageList('GB','AC2DSC',['Receive settlement']);
setLanguageLabel('GB','ADBDES','Account, deal or bank');
setLanguageList('GB','ADBVAL',['A','B','D']);
setLanguageList('GB','ADBDSC',['Account','Bank','Deal']);
setLanguageLabel('GB','ADIDES','Account definition indicator');
setLanguageList('GB','ADIVAL',['D','I']);
setLanguageList('GB','ADIDSC',['Data entry account','Internal account']);
setLanguageLabel('GB','ADJDES','Mat/rvr date adj type');
setLanguageList('GB','ADJVAL',['0','1']);
setLanguageList('GB','ADJDSC',['Date adj flag held on currency','Date adj held on int to due date']);
setLanguageLabel('GB','ADODES','Credit or debit');
setLanguageList('GB','ADOVAL',['01','02']);
setLanguageList('GB','ADODSC',['Add','Delete']);
setLanguageLabel('GB','AECDES','Amount edit code');
setLanguageList('GB','AECVAL',['H','T','M','B']);
setLanguageList('GB','AECDSC',['Hundreds','Thousands','Millions','Billions']);
setLanguageLabel('GB','ALMDES','Allocation method');
setLanguageList('GB','ALMVAL',['0','1','2','3','4']);
setLanguageList('GB','ALMDSC',['Externally defined','Average balance method','Number of accounts in pool','Percentage','Same ratio as income']);
setLanguageLabel('GB','ALRDES','Account long cycle rule');
setLanguageList('GB','ALRVAL',['0','1']);
setLanguageList('GB','ALRDSC',['Use interim profit rates','Use final profit period rate']);
setLanguageLabel('GB','AMDDES','Amortisation method');
setLanguageList('GB','AMDVAL',['CY','NA','SL']);
setLanguageList('GB','AMDDSC',['Constant yield','Not applicable','Straight line']);
setLanguageLabel('GB','AMRDES','Amount 2');
setLanguageLabel('GB','AMTDES','Amount');
setLanguageLabel('GB','APPDES','Application');
setLanguageList('GB','APPVAL',['CL','CP','FR','FX','GD','IR','MM','MS','RL','SW','TF']);
setLanguageList('GB','APPDSC',['Commercial Lending','Clean Payments','Fwd Rate Agreement','Foreign Exchange','Generic Deal','Interest Rate Swap','Money Market','Marketable Securities','Retail Lending','Swap','Trade Finance']);
setLanguageLabel('GB','APTDES','Apply to');
setLanguageList('GB','APTVAL',['A','B','C']);
setLanguageList('GB','APTDSC',['Account','Both','Customer']);
setLanguageLabel('GB','AP2DES','Application');
setLanguageList('GB','AP2VAL',['CL','CM','FR','FX','IR','MM','R','RL']);
setLanguageList('GB','AP2DSC',['Commercial lending','Core management','Forward rate agreements','Foreign exchange','Interest rate swaps','Money market','Retail','Retail lending']);
setLanguageLabel('GB','ARFDES','Amount reference');
setLanguageList('GB','ARFVAL',['01']);
setLanguageList('GB','ARFDSC',['Receive total']);
setLanguageLabel('GB','ARTDES','Cheque type for ARS');
setLanguageList('GB','ARTVAL',['1','2']);
setLanguageList('GB','ARTDSC',['Cheque can be authorised','Cheque must be returned']);
setLanguageLabel('GB','AR2DES','Amount reference');
setLanguageList('GB','AR2VAL',['01','02','03','04']);
setLanguageList('GB','AR2DSC',['Receive total','Receive net','Pay total','Pay net']);
setLanguageLabel('GB','AR3DES','Amount reference');
setLanguageList('GB','AR3VAL',['02','03','04','05','06','07','08','09','10','11','12','13','14']);
setLanguageList('GB','AR3DSC',['Charge','Tax level 1 on charge','Tax level 2 on charge','Commission','Tax level 1 on commission','Tax level 2 on commission','Total chgs, comms and taxes','Total charges and taxes','Total charges','Total commissions and taxes','Total commissions','Total taxes level 1','Total taxes level 2']);
setLanguageLabel('GB','AR4DES','Amount reference');
setLanguageList('GB','AR4VAL',['01']);
setLanguageList('GB','AR4DSC',['Entered']);
setLanguageLabel('GB','ASTDES','Warning asterisk');
setLanguageLabel('GB','ATYDES','Account type');
setLanguageList('GB','ATYVAL',['B','D','O']);
setLanguageList('GB','ATYDSC',['Balance','Derived','Off Balance']);
setLanguageLabel('GB','AUBDES','User type');
setLanguageList('GB','AUBVAL',['A','B','U']);
setLanguageList('GB','AUBDSC',['Authoriser','Both authoriser and user','User']);
setLanguageLabel('GB','AZTDES','Amortization type');
setLanguageList('GB','AZTVAL',['D','1','2','3','4','5']);
setLanguageList('GB','AZTDSC',['Derived in interface program','Constant Principal and Int Annuity','Constant Principal Annuity','Bullet','Pre-computed','Beh Amortization']);
setLanguageLabel('GB','BALDES','No of beneficiary add line');
setLanguageList('GB','BALVAL',['C','0','1','2','3','4']);
setLanguageList('GB','BALDSC',['Retrieve the customer full name','Abbreviated instructions flag is N','One','Two','Three','Abbreviated instructions flag is Y']);
setLanguageLabel('GB','BCIDES','Business/calendar indicator');
setLanguageList('GB','BCIVAL',['B','C']);
setLanguageList('GB','BCIDSC',['Business days','Calendar days']);
setLanguageLabel('GB','BCODES','Bank or customer');
setLanguageList('GB','BCOVAL',['B','C']);
setLanguageList('GB','BCODSC',['Bank','Customer']);
setLanguageLabel('GB','BDTDES','Basic deal type');
setLanguageList('GB','BDTVAL',['P','T','X']);
setLanguageList('GB','BDTDSC',['Parent','Term','Exchange']);
setLanguageLabel('GB','BFTDES','Broker fee type');
setLanguageList('GB','BFTVAL',['F','N','S','W']);
setLanguageList('GB','BFTDSC',['Input manually','Not known','System calculated','Waived']);
setLanguageLabel('GB','BINDES','Bulk indicator');
setLanguageList('GB','BINVAL',['B']);
setLanguageList('GB','BINDSC',['Bulk']);
setLanguageLabel('GB','BKPDES','Bulk posting');
setLanguageList('GB','BKPVAL',['1','2','3']);
setLanguageList('GB','BKPDSC',['No bulking','Bulking with transaction code','Bulking without transaction code']);
setLanguageLabel('GB','BLFDES','Balance flag');
setLanguageList('GB','BLFVAL',['0','1']);
setLanguageList('GB','BLFDSC',['Do not summarize the account','Summarise the account in BIAS']);
setLanguageLabel('GB','BOCDES','Bank operation code');
setLanguageList('GB','BOCVAL',['CRED','CRTS','SPAY','SPRI','SSTD']);
setLanguageList('GB','BOCDSC',['CR transfer - no SWIFT service','CR transfer - test purposes','CR transfer - SWIFT pay service','CR transfer - priority service','CR transfer - standard service']);
setLanguageLabel('GB','BOQDES','Branch output queue');
setLanguageList('GB','BOQVAL',['1','2','3','4']);
setLanguageList('GB','BOQDSC',['1','2','3','4']);
setLanguageLabel('GB','BOTDES','Balance order type');
setLanguageList('GB','BOTVAL',['D','L','R','S']);
setLanguageList('GB','BOTDSC',['Deficit','Limits','Real-time','Surplus']);
setLanguageLabel('GB','BRCDES','Branch Communications');
setLanguageList('GB','BRCVAL',['1','11','4','5','6','7','8','9']);
setLanguageList('GB','BRCDSC',['Suspend host monitor','Communications recovery log','Force branch closure','Force branch open off-line','Revoke forced status','Send refresh file','Re-apply trickle feed file','Branch event log']);
setLanguageLabel('GB','BTUDES','Balance to Use');
setLanguageList('GB','BTUVAL',['1','2','3','4','5']);
setLanguageList('GB','BTUDSC',['Average','Low','High','Available','Ledger']);
setLanguageLabel('GB','CALCAL','Date');
setLanguageLabel('GB','CALDES','Calendar picker');
setLanguageLabel('GB','CALERR','Error');
setLanguageLabel('GB','CALM01','The entered date is invalid.');
setLanguageLabel('GB','CALM02','The entered date is out of range');
setLanguageLabel('GB','CALM03','The entered date does not exists');
setLanguageLabel('GB','CALM04','Invalid date (');
setLanguageLabel('GB','CALM05',') ignored');
setLanguageLabel('GB','CALM06','is not a Date object');
setLanguageLabel('GB','CALM07','should consist of two elements');
setLanguageLabel('GB','CALM08','Click here to drag');
setLanguageLabel('GB','CALTOD','Today');
setLanguageLabel('GB','CALWK1','S');
setLanguageLabel('GB','CALWK2','S');
setLanguageLabel('GB','CALWK3','M');
setLanguageLabel('GB','CALWK4','T');
setLanguageLabel('GB','CALWK5','W');
setLanguageLabel('GB','CALWK6','T');
setLanguageLabel('GB','CALWK7','F');
setLanguageLabel('GB','CARDES','Collateral assignment rule');
setLanguageList('GB','CARVAL',['1','2','3']);
setLanguageList('GB','CARDSC',['Assign the collateral required','Assign the bank valuation','Assign percentage of bank valuation']);
setLanguageLabel('GB','CBQDES','Customer characteristics');
setLanguageList('GB','CBQVAL',['1','2','3']);
setLanguageList('GB','CBQDSC',['Non-correspondent bank','Correspondent bank','Non-bank customer']);
setLanguageLabel('GB','CBSDES','Cheque book status - SDAXG-SDAXI');
setLanguageList('GB','CBSVAL',['B','P','R']);
setLanguageList('GB','CBSDSC',['Received back from printer','Sent to security printers','Requested']);
setLanguageLabel('GB','CCADES','Charge calculation');
setLanguageList('GB','CCAVAL',['1','2']);
setLanguageList('GB','CCADSC',['Flat charge','Percentage']);
setLanguageLabel('GB','CCLDES','');
setLanguageList('GB','CCLVAL',['1','2','3']);
setLanguageList('GB','CCLDSC',['','','']);
setLanguageLabel('GB','CCRDES','Conversion rate');
setLanguageList('GB','CCRVAL',['C','N','P','S','T','U']);
setLanguageList('GB','CCRDSC',['Cash buy rate','Cash sell rate','Travellers cheque buy rate','Spot rate','Travellers cheque sell rate','User rate']);
setLanguageLabel('GB','CDEDES','Clearing code');
setLanguageList('GB','CDEVAL',['001','002','003','017','018','019','051','091']);
setLanguageList('GB','CDEDSC',['DD 1st payment','Debit Cheque','Debit item','DD reg payment','DD represented','DD last payment','Credit item','DD return']);
setLanguageLabel('GB','CDFDES','Check Digit Formula');
setLanguageList('GB','CDFVAL',['A','B','C']);
setLanguageList('GB','CDFDSC',['A','B','C']);
setLanguageLabel('GB','CDLDES','Delivery option');
setLanguageList('GB','CDLVAL',['1','2']);
setLanguageList('GB','CDLDSC',['Bank','Customer']);
setLanguageLabel('GB','CDODES','Customer document layout');
setLanguageList('GB','CDOVAL',['0','1','2']);
setLanguageList('GB','CDODSC',['Suppress document','Worse layout','Improve layout']);
setLanguageLabel('GB','CDPDES','Check digit position');
setLanguageList('GB','CDPVAL',['01','02','03','04','05','06','07','08','09','10','11','12','13']);
setLanguageList('GB','CDPDSC',['1','2','3','4','5','6','7','8','9','10','11','12','13']);
setLanguageLabel('GB','CDSDES','Cheque deposit status');
setLanguageList('GB','CDSVAL',['1','2','3','4']);
setLanguageList('GB','CDSDSC',['Deposit proved','Some items in error','Deposit header only','Deposit items saved']);
setLanguageLabel('GB','CEIDES','Cum/Ex interest');
setLanguageList('GB','CEIVAL',['C','E']);
setLanguageList('GB','CEIDSC',['Cum interest','Ex interest']);
setLanguageLabel('GB','CFPDES','Capital/flat price');
setLanguageList('GB','CFPVAL',['C','F']);
setLanguageList('GB','CFPDSC',['Capital price','Flat price']);
setLanguageLabel('GB','CFRDES','Compound frequency');
setLanguageList('GB','CFRVAL',['A','Q','S']);
setLanguageList('GB','CFRDSC',['Annual','Quarterly','Semi-annual']);
setLanguageLabel('GB','CHFDES','Charges for');
setLanguageList('GB','CHFVAL',['BEN','OUR','SHA']);
setLanguageList('GB','CHFDSC',['Beneficiary','Ours','Shared']);
setLanguageLabel('GB','CHMDES','Penalty charge method');
setLanguageList('GB','CHMVAL',['1','2']);
setLanguageList('GB','CHMDSC',['Debit notice account','Interest adjustment']);
setLanguageLabel('GB','CHTDES','Charge type');
setLanguageList('GB','CHTVAL',['F','U']);
setLanguageList('GB','CHTDSC',['Flat fee','Per unit']);
setLanguageLabel('GB','CIDDES','Cheque input date');
setLanguageList('GB','CIDVAL',['1','2']);
setLanguageList('GB','CIDDSC',['Today only','Historic only']);
setLanguageLabel('GB','CINDES','Cost of funds indicator');
setLanguageList('GB','CINVAL',['D','S']);
setLanguageList('GB','CINDSC',['Derived','Source']);
setLanguageLabel('GB','CITDES','Cheque item type');
setLanguageList('GB','CITVAL',['H','L','O','R']);
setLanguageList('GB','CITDSC',['House Cheque','Local Cheque','Outport Cheque','Remittance Cheque']);
setLanguageLabel('GB','CLCDES','Pricing calculation');
setLanguageList('GB','CLCVAL',['1','2','3']);
setLanguageList('GB','CLCDSC',['Interest (price)','Interest (proceeds)','Discount']);
setLanguageLabel('GB','CLTDES','Claim type');
setLanguageList('GB','CLTVAL',['I','P']);
setLanguageList('GB','CLTDSC',['Interest','Principal']);
setLanguageLabel('GB','CMPDES','Amount to compare');
setLanguageList('GB','CMPVAL',['1','2']);
setLanguageList('GB','CMPDSC',['Withdrawal amount','Withdrawal + charge amount']);
setLanguageLabel('GB','CNCDES','Customer number position');
setLanguageList('GB','CNCVAL',['1','2','3','4','5','6']);
setLanguageList('GB','CNCDSC',['One','Two','Three','Four','Five','Six']);
setLanguageLabel('GB','CN1DES','Display Primary Job');
setLanguageList('GB','CN1VAL',['1']);
setLanguageList('GB','CN1DSC',['Display Primary Job']);
setLanguageLabel('GB','COADES','Currency of amount');
setLanguageList('GB','COAVAL',['A','B','C','D','L','P','S']);
setLanguageList('GB','COADSC',['Account currency','Base currency','Collateral currency','Deal currency','Local currency','Purchase currency','Sale currency']);
setLanguageLabel('GB','COCDES','Cancel or claim');
setLanguageList('GB','COCVAL',['1','2']);
setLanguageList('GB','COCDSC',['Claim','Cancel']);
setLanguageLabel('GB','CONDES','Output in console');
setLanguageLabel('GB','CPDDES','Cheque post dated deposit');
setLanguageList('GB','CPDVAL',['1','2']);
setLanguageList('GB','CPDDSC',['Post dated only','Not post dated']);
setLanguageLabel('GB','CPGDES','Charge priority group');
setLanguageList('GB','CPGVAL',['A','B','C','D','E']);
setLanguageList('GB','CPGDSC',['A','B','C','D','E']);
setLanguageLabel('GB','CPODES','Penalty calculation');
setLanguageList('GB','CPOVAL',['1','2']);
setLanguageList('GB','CPODSC',['Withdrawal amount only','Withdrawal + charge amount']);
setLanguageLabel('GB','CPTDES','Clean payment type');
setLanguageList('GB','CPTVAL',['INT','NSA','SO']);
setLanguageList('GB','CPTDSC',['Interest','Notice saving account','Standing order']);
setLanguageLabel('GB','CRFDES','Currency reference');
setLanguageList('GB','CRFVAL',['01','02','03','04']);
setLanguageList('GB','CRFDSC',['Receive settlement','Pay settlement','Local','Base']);
setLanguageLabel('GB','CRHDES','Cheque reason held');
setLanguageList('GB','CRHVAL',['C','S']);
setLanguageList('GB','CRHDSC',['Collateral','Safekeeping']);
setLanguageLabel('GB','CRTDES','Curve type');
setLanguageList('GB','CRTVAL',['D','Z']);
setLanguageList('GB','CRTDSC',['Discount factor','Zero coupon']);
setLanguageLabel('GB','CSLDES','Charge selection option');
setLanguageList('GB','CSLVAL',['X','1']);
setLanguageList('GB','CSLDSC',['Exclude','Select']);
setLanguageLabel('GB','CTPDES','CLS Type');
setLanguageList('GB','CTPVAL',['1','2','3','4']);
setLanguageList('GB','CTPDSC',['Settlement member','User member','Third party','Branch of settlement member']);
setLanguageLabel('GB','CTRDES','Cheque type required');
setLanguageList('GB','CTRVAL',['1','2','3','4','5']);
setLanguageList('GB','CTRDSC',['Full','Customer full name','Specific address','All address','Add customer case']);
setLanguageLabel('GB','CTTDES','Customer transfer type');
setLanguageList('GB','CTTVAL',['1','2','3','4']);
setLanguageList('GB','CTTDSC',['Default for inward/interbank tfrs','MT100 default for outward cust tfrs','MT103','MT103+']);
setLanguageLabel('GB','CTVDES','CLS Date trade/value');
setLanguageList('GB','CTVVAL',['1','2']);
setLanguageList('GB','CTVDSC',['Deal trade date','Value date']);
setLanguageLabel('GB','DABDES','Date abbreviation');
setLanguageList('GB','DABVAL',['D','M','W','Y']);
setLanguageList('GB','DABDSC',['Day','Month','Week','Year']);
setLanguageLabel('GB','DAYDES','Day');
setLanguageList('GB','DAYVAL',['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14']);
setLanguageList('GB','DAYDSC',['Zero','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen']);
setLanguageLabel('GB','DCADES','Date code - SDBCT/SDDAB');
setLanguageList('GB','DCAVAL',['B','C','D','M','T','W','Y']);
setLanguageList('GB','DCADSC',['Business day','Calendar day','Day','Month','Relative to today','Week','Year']);
setLanguageLabel('GB','DCIDES','Debit or credit interest - SDAHU');
setLanguageList('GB','DCIVAL',['C','D']);
setLanguageList('GB','DCIDSC',['Credit','Debit']);
setLanguageLabel('GB','DCODES','Credit or debit');
setLanguageList('GB','DCOVAL',['CR','DR']);
setLanguageList('GB','DCODSC',['Credit','Debit']);
setLanguageLabel('GB','DCRDES','Deposit cycle/rollover rule');
setLanguageList('GB','DCRVAL',['0','1','2','3']);
setLanguageList('GB','DCRDSC',['Equation standard','Latest approved profit rate','Hold until profit rate approved','Cycle between profit end/approval']);
setLanguageLabel('GB','DCVDES','Round Up, Down, Nearest');
setLanguageList('GB','DCVVAL',['D','N','U']);
setLanguageList('GB','DCVDSC',['Down','Nearest','Up']);
setLanguageLabel('GB','DC2DES','Credit or debit');
setLanguageList('GB','DC2VAL',['01','02']);
setLanguageList('GB','DC2DSC',['Debit','Credit']);
setLanguageLabel('GB','DDCDES','Direct debit claim type');
setLanguageList('GB','DDCVAL',['C','I','P']);
setLanguageList('GB','DDCDSC',['Charges','Interest','Principal']);
setLanguageLabel('GB','DDIDES','Direct debit instruction status');
setLanguageList('GB','DDIVAL',['0','1','2','3','4','9']);
setLanguageList('GB','DDIDSC',['Pending','Active','Held','Expired','Failed','Cancel']);
setLanguageLabel('GB','DEEDES','Deal Enquiry or Deal Events');
setLanguageList('GB','DEEVAL',['1','2']);
setLanguageList('GB','DEEDSC',['Deal Enquiry','Deal Events']);
setLanguageLabel('GB','DELDES','Delete');
setLanguageList('GB','DELVAL',['D']);
setLanguageList('GB','DELDSC',['Delete']);
setLanguageLabel('GB','DFRDES','Download frequency');
setLanguageList('GB','DFRVAL',['120','180','30','60']);
setLanguageList('GB','DFRDSC',['120','180','30','60']);
setLanguageLabel('GB','DFSDES','Default instructions');
setLanguageList('GB','DFSVAL',['D','F','S']);
setLanguageList('GB','DFSDSC',['Our Documents','Our Funds','Customer Settlement']);
setLanguageLabel('GB','DIRDES','Deal input requirements');
setLanguageList('GB','DIRVAL',['1','2','3']);
setLanguageList('GB','DIRDSC',['Equation input functions','Equation APIs','Either input functions or APIs']);
setLanguageLabel('GB','DOPDES','Data Operation');
setLanguageList('GB','DOPVAL',['G','I','L','N','R','X']);
setLanguageList('GB','DOPDSC',['Greater than','Include','Less than','Not equal','Range','Not in Range']);
setLanguageLabel('GB','DO1DES','Delete or Select');
setLanguageList('GB','DO1VAL',['D','1']);
setLanguageList('GB','DO1DSC',['Delete','Select']);
setLanguageLabel('GB','DPADES','Action if no available balance');
setLanguageList('GB','DPAVAL',['1','2','3','4','5']);
setLanguageList('GB','DPADSC',['Apply','Retry','Delete','Acknowledge','Reset']);
setLanguageLabel('GB','DRFDES','Date reference');
setLanguageList('GB','DRFVAL',['01','02','03','04','05','06','07','08']);
setLanguageList('GB','DRFDSC',['Receive settlement','Pay settlement','Log','Last review','Authorisation','Current','Tomorrow (1 processing day ahead)','Spot (2 processing days ahead)']);
setLanguageLabel('GB','DR2DES','Date reference');
setLanguageList('GB','DR2VAL',['09']);
setLanguageList('GB','DR2DSC',['Open']);
setLanguageLabel('GB','DTCDES','Data type code');
setLanguageList('GB','DTCVAL',['AL','AM','CO','DT','IR','NU','XR']);
setLanguageList('GB','DTCDSC',['Alphanumeric','Monetary amount','Code','Date','Interest rate','Numeric','Exchange rate']);
setLanguageLabel('GB','DTEDES','System date');
setLanguageLabel('GB','DTTDES','Data type');
setLanguageList('GB','DTTVAL',['1','2','3','4','5','6','7']);
setLanguageList('GB','DTTDSC',['SWIFT date format','SWIFT amount format','SWIFT currency code','SWIFT rate format','SWIFT address format','Numeric amount format','EQUATION currency code']);
setLanguageLabel('GB','DVCDES','Date validation calendar');
setLanguageList('GB','DVCVAL',['C','L']);
setLanguageList('GB','DVCDSC',['Deal currency calendar','Local run day calendar']);
setLanguageLabel('GB','DWMDES','Period');
setLanguageList('GB','DWMVAL',['D','M','W']);
setLanguageList('GB','DWMDSC',['Days','Months','Weeks']);
setLanguageLabel('GB','ECADES','Enquire, cancel or add');
setLanguageList('GB','ECAVAL',['1','2','3']);
setLanguageList('GB','ECADSC',['Enquire','Add','Cancel']);
setLanguageLabel('GB','EFODES','Editing for output');
setLanguageList('GB','EFOVAL',['A','N','P','Z']);
setLanguageList('GB','EFODSC',['Month abbreviation','Month numeric','Past dates','Suppress leading zeroes']);
setLanguageLabel('GB','ELRDES','Eligibility rules');
setLanguageList('GB','ELRVAL',['0','1','2','3']);
setLanguageList('GB','ELRDSC',['Actual balance','Aggregate average balance','Minimum balance','Externally defined']);
setLanguageLabel('GB','EPADES','Early payment method');
setLanguageList('GB','EPAVAL',['0','1','2','3','4']);
setLanguageList('GB','EPADSC',['Default','Stay constant','Principal reduction','Reduction keep maturity date','Reduction keep payment amount']);
setLanguageLabel('GB','EWRDES','Early withdrawal rule');
setLanguageList('GB','EWRVAL',['0','1','2','3']);
setLanguageList('GB','EWRDSC',['Equation standard','Previous period profit rate','Zero for final period','Delay until next profit rate approv']);
setLanguageLabel('GB','EXFDES','Exchange rate type');
setLanguageList('GB','EXFVAL',['1','2','3','4','5','6','7']);
setLanguageList('GB','EXFDSC',['Spot rate','User rate','Buy-Sell','Buy-Buy','Sell-Buy','Sell-Sell','Mid-rate']);
setLanguageLabel('GB','EX2DES','Exchange rate type');
setLanguageList('GB','EX2VAL',['1','2','5']);
setLanguageList('GB','EX2DSC',['Spot rate','User rate','Retail rate']);
setLanguageLabel('GB','FCTDES','Function mode');
setLanguageLabel('GB','FDFDES','Fontis download frequency - SDDRF');
setLanguageList('GB','FDFVAL',['']);
setLanguageList('GB','FDFDSC',['']);
setLanguageLabel('GB','FEQDES','Default payment frequency');
setLanguageList('GB','FEQVAL',['A','M','S','V']);
setLanguageList('GB','FEQDSC',['Yearly','Half yearly','Quarterly','Monthly']);
setLanguageLabel('GB','FFDDES','Fix format data');
setLanguageLabel('GB','FLDDES','Field selection code');
setLanguageList('GB','FLDVAL',['C','D','E','G','I','L','N','R','X']);
setLanguageList('GB','FLDDSC',['Include if date is within the range','Date is equal to','Exclude if date is within the range','Greater than','Include','Less than','Not equal','Range','Not in range']);
setLanguageLabel('GB','FRIDES','Frequency code indicator');
setLanguageList('GB','FRIVAL',['B','N','P']);
setLanguageList('GB','FRIDSC',['Business days with frequency code','Calendar days - next day','Calendar days - previous day']);
setLanguageLabel('GB','FRMDES','Form type');
setLanguageList('GB','FRMVAL',['0','1','2']);
setLanguageList('GB','FRMDSC',['Tax payee','R85','R105']);
setLanguageLabel('GB','FRQDAILY','Daily');
setLanguageLabel('GB','FRQDES','Frequency picker');
setLanguageLabel('GB','FRQFORT','Fortnightly');
setLanguageLabel('GB','FRQFRQ','Frequency');
setLanguageLabel('GB','FRQHALF','Half-yearly');
setLanguageLabel('GB','FRQMON','Monthly');
setLanguageLabel('GB','FRQM01','Select');
setLanguageLabel('GB','FRQM02','On');
setLanguageLabel('GB','FRQM03','On The');
setLanguageLabel('GB','FRQM04','Recurrence');
setLanguageLabel('GB','FRQM05','Day');
setLanguageLabel('GB','FRQM06','In');
setLanguageLabel('GB','FRQM07','Every');
setLanguageLabel('GB','FRQPOS1','First');
setLanguageLabel('GB','FRQPOS2','Second');
setLanguageLabel('GB','FRQPOS3','Third');
setLanguageLabel('GB','FRQPOS4','Fourth');
setLanguageLabel('GB','FRQPOS5','Fifth');
setLanguageLabel('GB','FRQQUAR','Quarterly');
setLanguageLabel('GB','FRQWEEK','Weekly');
setLanguageLabel('GB','FRQWK1','Sunday');
setLanguageLabel('GB','FRQWK2','Monday');
setLanguageLabel('GB','FRQWK3','Tuesday');
setLanguageLabel('GB','FRQWK4','Wednesday');
setLanguageLabel('GB','FRQWK5','Thursday');
setLanguageLabel('GB','FRQWK6','Friday');
setLanguageLabel('GB','FRQWK7','Saturday');
setLanguageLabel('GB','FRQYEAR','Yearly');
setLanguageLabel('GB','FTMDES','Funding type');
setLanguageLabel('GB','FRRDES','Fixed rate rule');
setLanguageList('GB','FRRVAL',['0','1']);
setLanguageList('GB','FRRDSC',['Always used fixed rate','Treat as minimum rate']);
setLanguageList('GB','FTMVAL',['1','2']);
setLanguageList('GB','FTMDSC',['Manual payments','Automatic payments']);
setLanguageLabel('GB','FTTDES','Formatted text');
setLanguageLabel('GB','FTYDES','Field type');
setLanguageList('GB','FTYVAL',['1','2','3']);
setLanguageList('GB','FTYDSC',['Alphanumeric','Numeric','Character']);
setLanguageLabel('GB','FWMDES','Free withdrawal');
setLanguageList('GB','FWMVAL',['0','1','2']);
setLanguageList('GB','FWMDSC',['Not allowed','Per calendar period','After elapsed time']);
setLanguageLabel('GB','GBLABORT','Abort');
setLanguageLabel('GB','GBLABORT2','abort');
setLanguageLabel('GB','GBLACPT','Accept');
setLanguageLabel('GB','GBLADD','Add');
setLanguageLabel('GB','GBLADD2','add');
setLanguageLabel('GB','GBLALL','All');
setLanguageLabel('GB','GBLALL2','all');
setLanguageLabel('GB','GBLAPR','APR');
setLanguageLabel('GB','GBLAUG','AUG');
setLanguageLabel('GB','GBLAUTH','Authorise');
setLanguageLabel('GB','GBLAUTHD','Authorised');
setLanguageLabel('GB','GBLAUTHD2','authorised');
setLanguageLabel('GB','GBLAVAIL','Available');
setLanguageLabel('GB','GBLAVAIL2','available');
setLanguageLabel('GB','GBLBACK','Back');
setLanguageLabel('GB','GBLBRNM','Branch');
setLanguageLabel('GB','GBLBRNM2','branch');
setLanguageLabel('GB','GBLCAN','Cancel');
setLanguageLabel('GB','GBLCHGR','Charge');
setLanguageLabel('GB','GBLCHGRS','Charges');
setLanguageLabel('GB','GBLCHGRS2','charges');
setLanguageLabel('GB','GBLCHGR2','charge');
setLanguageLabel('GB','GBLCLOSE','Close');
setLanguageLabel('GB','GBLCOMNT','Comment'); 
setLanguageLabel('GB','GBLCOMNT2','comment');
setLanguageLabel('GB','GBLCOMP','Complete');
setLanguageLabel('GB','GBLCOMPN','Completion');
setLanguageLabel('GB','GBLCONT','Continue');
setLanguageLabel('GB','GBLCONT2','continue');
setLanguageLabel('GB','GBLCTRL','Control');
setLanguageLabel('GB','GBLDEC','DEC');
setLanguageLabel('GB','GBLDECL','Decline');
setLanguageLabel('GB','GBLDECLD','Declined');
setLanguageLabel('GB','GBLDECLD2','declined');
setLanguageLabel('GB','GBLDEL','Delete');
setLanguageLabel('GB','GBLDELC2','decline');
setLanguageLabel('GB','GBLDES','Global dictionary');
setLanguageLabel('GB','GBLDIAGC','Diagnostic');
setLanguageLabel('GB','GBLENT','Enter');
setLanguageLabel('GB','GBLERROR','Error');
setLanguageLabel('GB','GBLESC','Escape');
setLanguageLabel('GB','GBLEXIT','Exit');
setLanguageLabel('GB','GBLFEB','FEB');
setLanguageLabel('GB','GBLFILT','Filter');
setLanguageLabel('GB','GBLFIN','Finish');
setLanguageLabel('GB','GBLFIN2','finish');
setLanguageLabel('GB','GBLFIRST','First');  
setLanguageLabel('GB','GBLFIRST2','first');
setLanguageLabel('GB','GBLFWD','Forward');
setLanguageLabel('GB','GBLGO','Go');
setLanguageLabel('GB','GBLGROUP','Group');
setLanguageLabel('GB','GBLGROUP2','group');
setLanguageLabel('GB','GBLHDR','Header');
setLanguageLabel('GB','GBLHELP','Help');
setLanguageLabel('GB','GBLHOME','Home');
setLanguageLabel('GB','GBLINFOL','Informational');
setLanguageLabel('GB','GBLINQ','Inquiry');
setLanguageLabel('GB','GBLJAN','JAN');
setLanguageLabel('GB','GBLJOB','Job');
setLanguageLabel('GB','GBLJOBLOG','Joblog');
setLanguageLabel('GB','GBLJUL','JUL');
setLanguageLabel('GB','GBLJUN','JUN');
setLanguageLabel('GB','GBLLANG','Language');
setLanguageLabel('GB','GBLLAST','Last'); 
setLanguageLabel('GB','GBLLAST2','last');
setLanguageLabel('GB','GBLLGOF','Logout');
setLanguageLabel('GB','GBLLGON','Logon');
setLanguageLabel('GB','GBLLGON2','logon');
setLanguageLabel('GB','GBLLIB','Library');
setLanguageLabel('GB','GBLLIB2','library');
setLanguageLabel('GB','GBLLOAD','Load');
setLanguageLabel('GB','GBLLOAD2','load');
setLanguageLabel('GB','GBLLOG','Log');
setLanguageLabel('GB','GBLMAIN','Main');
setLanguageLabel('GB','GBLMAIN2','main');
setLanguageLabel('GB','GBLMAR','MAR');
setLanguageLabel('GB','GBLMAXI','Maximize');
setLanguageLabel('GB','GBLMAY','MAY');
setLanguageLabel('GB','GBLMENU','Menu');
setLanguageLabel('GB','GBLMENUS','Menus');
setLanguageLabel('GB','GBLMSG','Message');
setLanguageLabel('GB','GBLMSGS','Messages');
setLanguageLabel('GB','GBLN','N');
setLanguageLabel('GB','GBLNAME','Name');
setLanguageLabel('GB','GBLNAME2','name');
setLanguageLabel('GB','GBLNAVI','Navigator');
setLanguageLabel('GB','GBLNAVI2','navigator');
setLanguageLabel('GB','GBLNEXT','Next');
setLanguageLabel('GB','GBLNEXT2','next');
setLanguageLabel('GB','GBLNO','No');
setLanguageLabel('GB','GBLNONE','None');
setLanguageLabel('GB','GBLNOTFY','Notify');
setLanguageLabel('GB','GBLNOV','NOV');
setLanguageLabel('GB','GBLOCT','OCT');
setLanguageLabel('GB','GBLOFLN','Offline');
setLanguageLabel('GB','GBLOFLN2','offline');
setLanguageLabel('GB','GBLOK','OK');
setLanguageLabel('GB','GBLOLDER','Older');
setLanguageLabel('GB','GBLONLN','Online');
setLanguageLabel('GB','GBLONLN2','online');
setLanguageLabel('GB','GBLOPTION','Option');
setLanguageLabel('GB','GBLOPTION2','option');
setLanguageLabel('GB','GBLOR','Or');
setLanguageLabel('GB','GBLOR2','or');
setLanguageLabel('GB','GBLOUTPUT','Output');
setLanguageLabel('GB','GBLOVR','Override');
setLanguageLabel('GB','GBLPAGE','Page');
setLanguageLabel('GB','GBLPAGES','Pages'); 
setLanguageLabel('GB','GBLPAGES2','pages');
setLanguageLabel('GB','GBLPAGE2','page');
setLanguageLabel('GB','GBLPEND','Pending');
setLanguageLabel('GB','GBLPEND2','pending');
setLanguageLabel('GB','GBLPHS','Phase');
setLanguageLabel('GB','GBLPRCD','Proceed');
setLanguageLabel('GB','GBLPREV','Previous');
setLanguageLabel('GB','GBLPREV2','previous');
setLanguageLabel('GB','GBLPRMPT','Prompt');
setLanguageLabel('GB','GBLPRNT','Print');
setLanguageLabel('GB','GBLPROB','Problem');
setLanguageLabel('GB','GBLPROBS','Problems');
setLanguageLabel('GB','GBLPROC','Process');
setLanguageLabel('GB','GBLPROG','Progress');
setLanguageLabel('GB','GBLPWD','Password');
setLanguageLabel('GB','GBLPWD2','password');
setLanguageLabel('GB','GBLRECENT','Recent');
setLanguageLabel('GB','GBLRANGE','Range'); 
setLanguageLabel('GB','GBLRANGE2','range');
setLanguageLabel('GB','GBLREF','Referral');
setLanguageLabel('GB','GBLREFER','Refer'); 
setLanguageLabel('GB','GBLREFER2','refer');
setLanguageLabel('GB','GBLREFR','Refresh');
setLanguageLabel('GB','GBLREFRD','Referred');
setLanguageLabel('GB','GBLREFRD2','referred');
setLanguageLabel('GB','GBLREFR2','refresh');
setLanguageLabel('GB','GBLREFS','Referrals');
setLanguageLabel('GB','GBLREFS2','referrals');
setLanguageLabel('GB','GBLREF2','referral');
setLanguageLabel('GB','GBLREJCT','Reject'); 
setLanguageLabel('GB','GBLREJCT2','reject');
setLanguageLabel('GB','GBLREPLY','Reply');
setLanguageLabel('GB','GBLRESTR','Restore');
setLanguageLabel('GB','GBLRESUB','Resubmit');
setLanguageLabel('GB','GBLRESUB2','resubmit');
setLanguageLabel('GB','GBLRQST','Request');
setLanguageLabel('GB','GBLRRFER','Re-refer'); 
setLanguageLabel('GB','GBLRRFER2','re-refer');
setLanguageLabel('GB','GBLRVWNG','Reviewing');
setLanguageLabel('GB','GBLRVWNG2','reviewing');
setLanguageLabel('GB','GBLSAVE','Save');
setLanguageLabel('GB','GBLSAVE2','save');
setLanguageLabel('GB','GBLSBMT','Submit');
setLanguageLabel('GB','GBLSEARCH','Search');
setLanguageLabel('GB','GBLSEARCH2','search');
setLanguageLabel('GB','GBLSECS','Seconds');
setLanguageLabel('GB','GBLSECS2','seconds');
setLanguageLabel('GB','GBLSEP','SEP');
setLanguageLabel('GB','GBLSUPP','Support');
setLanguageLabel('GB','GBLSUPVS','Supervisor');
setLanguageLabel('GB','GBLSUPVS2','supervisor');
setLanguageLabel('GB','GBLSYS','System');
setLanguageLabel('GB','GBLSYS2','system');
setLanguageLabel('GB','GBLTBAR','Toolbar');
setLanguageLabel('GB','GBLTBAR2','toolbar');
setLanguageLabel('GB','GBLTIME','Time'); 
setLanguageLabel('GB','GBLTIME2','time');
setLanguageLabel('GB','GBLTITLE','Title');
setLanguageLabel('GB','GBLTITLE2','title');
setLanguageLabel('GB','GBLTMSTM','Timestamp'); 
setLanguageLabel('GB','GBLTMSTM2','timestamp');
setLanguageLabel('GB','GBLTODAY','Today');
setLanguageLabel('GB','GBLTOGLE','Toggle');
setLanguageLabel('GB','GBLTOGLE2','toggle');
setLanguageLabel('GB','GBLUNIT','Unit');
setLanguageLabel('GB','GBLUNIT2','unit');
setLanguageLabel('GB','GBLUSER','User');
setLanguageLabel('GB','GBLUSER2','user');
setLanguageLabel('GB','GBLVERI','Verify');
setLanguageLabel('GB','GBLVERSN','Version'); 
setLanguageLabel('GB','GBLVERSN2','version');
setLanguageLabel('GB','GBLWAITG','Waiting');
setLanguageLabel('GB','GBLWAITG2','waiting');
setLanguageLabel('GB','GBLWSID','Workstation id');
setLanguageLabel('GB','GBLY','Y');
setLanguageLabel('GB','GBLYES','Yes');
setLanguageLabel('GB','GBLYEST','Yesterday');
setLanguageLabel('GB','GBL000001','Validation Error');
setLanguageLabel('GB','GBL000002','No messages found');
setLanguageLabel('GB','GBL000003','Prime menu');
setLanguageLabel('GB','GBL000004','All menus');
setLanguageLabel('GB','GBL000005','System menu');
setLanguageLabel('GB','GBL000006','Webform');
setLanguageLabel('GB','GBL000007','System status');
setLanguageLabel('GB','GBL000008','Equation User Interface');
setLanguageLabel('GB','GBL000009','Control system');
setLanguageLabel('GB','GBL000010','System status');
setLanguageLabel('GB','GBL000011','Navigation');
setLanguageLabel('GB','GBL000012','Equation Banking Server');
setLanguageLabel('GB','GBL000013','Equation User Interface Entry');
setLanguageLabel('GB','GBL000014','Input System');
setLanguageLabel('GB','GBL000015','Equation Input System');
setLanguageLabel('GB','GBL000016','Input System Navigator');
setLanguageLabel('GB','GBL000017','Equation User Interface Logon');
setLanguageLabel('GB','GBL000018','Navigator Toolbar');
setLanguageLabel('GB','GBL000019','Session Identifier');
setLanguageLabel('GB','GBL000020','Close shutter');
setLanguageLabel('GB','GBL000021','Open shutter');
setLanguageLabel('GB','GBL000022','Navigator View');
setLanguageLabel('GB','GBL000023','Control System');
setLanguageLabel('GB','GBL000024','Search Results');
setLanguageLabel('GB','GBL000025','Output System');
setLanguageLabel('GB','GBL000026','Output System Navigator');
setLanguageLabel('GB','GBL000027','Invalid frequency');
setLanguageLabel('GB','GBL000028','Show header');
setLanguageLabel('GB','GBL000029','Hide header');
setLanguageLabel('GB','GBL000030','Last week');
setLanguageLabel('GB','GBL000031','Two weeks ago');
setLanguageLabel('GB','GBL000032','Three weeks ago');
setLanguageLabel('GB','GBL000033','Last month');
setLanguageLabel('GB','GBL000034','Toggle footer');
setLanguageLabel('GB','GBL000035','Collapse all');
setLanguageLabel('GB','GBL000036','Expand all');
setLanguageLabel('GB','GBL000037','Webform Control');
setLanguageLabel('GB','GBL000038','User menu');
setLanguageLabel('GB','GBL000039','Unspecified error');
setLanguageLabel('GB','GBL000040','Equation Control');
setLanguageLabel('GB','GBL000041','System Configuration');
setLanguageLabel('GB','GBL000042','Runtime Control');
setLanguageLabel('GB','GBL000043','Interface Control');
setLanguageLabel('GB','GBL000044','Recovery Control');
setLanguageLabel('GB','GBL000045','SWIFT Control');
setLanguageLabel('GB','GBL000046','Additional Message Information');
setLanguageLabel('GB','GBL000047','Spooled File Listing');
setLanguageLabel('GB','GBL000048','From user');
setLanguageLabel('GB','GBL000049','Message severity');
setLanguageLabel('GB','GBL000050','Message type');
setLanguageLabel('GB','GBL000051','Date sent');
setLanguageLabel('GB','GBL000052','Time sent');
setLanguageLabel('GB','GBL000053','Error message');
setLanguageLabel('GB','GBL000054','Job log');
setLanguageLabel('GB','GBL000055','Spooled file name');
setLanguageLabel('GB','GBL000056','Job name');
setLanguageLabel('GB','GBL000057','Job user');
setLanguageLabel('GB','GBL000058','Job number');
setLanguageLabel('GB','GBL000059','Spooled file number');
setLanguageLabel('GB','GBL000060','Spooled file');
setLanguageLabel('GB','GBL000061','Message ID');
setLanguageLabel('GB','GBL000062','Senders copy');
setLanguageLabel('GB','GBL000063','User\'s spooled file');
setLanguageLabel('GB','GBL000064','Unit\'s spooled file');
setLanguageLabel('GB','GBL000065','Page up');
setLanguageLabel('GB','GBL000066','Page down');
setLanguageLabel('GB','GBL000067','Exit prompting');
setLanguageLabel('GB','GBL000068','Exit and run');
setLanguageLabel('GB','GBL000069','Switch unit');
setLanguageLabel('GB','GBL000070','Suspend Input System');
setLanguageLabel('GB','GBL000071','Input System Suspended');
setLanguageLabel('GB','GBL000072','Suspend Equation Desktop');
setLanguageLabel('GB','GBL000073','Equation Desktop Suspended');
setLanguageLabel('GB','GBL000074','Input branch');
setLanguageLabel('GB','GBL000075','System information');
setLanguageLabel('GB','GBL000076','Unit description');
setLanguageLabel('GB','GBL000077','Processing date');
setLanguageLabel('GB','GBL000078','Workload');
setLanguageLabel('GB','GBL000079','Search result');
setLanguageLabel('GB','GBL000080','Saved');
setLanguageLabel('GB','GBL000081','Template');
setLanguageLabel('GB','GBL000082','Referred');
setLanguageLabel('GB','GBL000083','In progress');
setLanguageLabel('GB','GBL000084','Submitted');
setLanguageLabel('GB','GBL000085','Unknown');
setLanguageLabel('GB','GBL000086','Filter:');
setLanguageLabel('GB','GBL000087','Delete all');
setLanguageLabel('GB','GBL000088','Delete selected');
setLanguageLabel('GB','GBL000089','Print session');
setLanguageLabel('GB','GBL000090','Save as template');
setLanguageLabel('GB','GBL000091','Reason for rejection');
setLanguageLabel('GB','GBL000092','Retrieve database');
setLanguageLabel('GB','GBL000093','Return to key');
setLanguageLabel('GB','GBL000094','Partially authorised');
setLanguageLabel('GB','GBL000095','Select an option');
setLanguageLabel('GB','GBL000096','Select from list');
setLanguageLabel('GB','GBL000097','Welcome to BankFusion Equation');
setLanguageLabel('GB','GBL000098','Authorise all');
setLanguageLabel('GB','GBL000099','Auth first warning');
setLanguageLabel('GB','GBL000100','Charge key record');
setLanguageLabel('GB','GBL000101','Charge key record description');
setLanguageLabel('GB','GBL000102','Event mnemonic');
setLanguageLabel('GB','GBL000103','This is the event mnemonic');
setLanguageLabel('GB','GBL000104','Charge component');
setLanguageLabel('GB','GBL000105','Enter the charge component');
setLanguageLabel('GB','GBL000106','Charge key detail');
setLanguageLabel('GB','GBL000107','This is the charge key detail');
setLanguageLabel('GB','GBL000108','Add Event Charge');
setLanguageLabel('GB','GBL000109','This is the list of charges for this transaction');
setLanguageLabel('GB','GBL000110','Reference');
setLanguageLabel('GB','GBL000111','This is either the account, deal, commitment');
setLanguageLabel('GB','GBL000112','Option');
setLanguageLabel('GB','GBL000113','Enter the selection');
setLanguageLabel('GB','GBL000114','Calculated charge');
setLanguageLabel('GB','GBL000115','This is the calculated charge');
setLanguageLabel('GB','GBL000116','Charge amount');
setLanguageLabel('GB','GBL000117','This is the charge amount');
setLanguageLabel('GB','GBL000118','Event mnemonic');
setLanguageLabel('GB','GBL000119','This is the event mnemonic');
setLanguageLabel('GB','GBL000120','Charge structure');
setLanguageLabel('GB','GBL000121','This is the charge structure');
setLanguageLabel('GB','GBL000122','Charge description');
setLanguageLabel('GB','GBL000123','This is the charge description');
setLanguageLabel('GB','GBL000124','Charge start date');
setLanguageLabel('GB','GBL000125','This is the charge start date');
setLanguageLabel('GB','GBL000126','Charge end date');
setLanguageLabel('GB','GBL000127','This is the charge end date');
setLanguageLabel('GB','GBL000128','Charge value date');
setLanguageLabel('GB','GBL000129','This is the charge value date');
setLanguageLabel('GB','GBL000130','Calculate on amount description');
setLanguageLabel('GB','GBL000131','This is the calculculate on amount description');
setLanguageLabel('GB','GBL000132','Add Event Charge');
setLanguageLabel('GB','GBL000133','This is the Add Event Charge screen');
setLanguageLabel('GB','GBL000134','Charge based on');
setLanguageLabel('GB','GBL000135','This is the charge structure where this charge is based on');
setLanguageLabel('GB','GBL000136','Charge component');
setLanguageLabel('GB','GBL000137','This is the charge component');
setLanguageLabel('GB','GBL000138','Charge code');
setLanguageLabel('GB','GBL000139','This is the charge code');
setLanguageLabel('GB','GBL000140','Charge currency');
setLanguageLabel('GB','GBL000141','This is the charge currency');
setLanguageLabel('GB','GBL000142','Regular frequency charge');
setLanguageLabel('GB','GBL000143','Enter the regular frequency charge');
setLanguageLabel('GB','GBL000144','Charge start date');
setLanguageLabel('GB','GBL000145','Enter the charge start date');
setLanguageLabel('GB','GBL000146','Charge end date');
setLanguageLabel('GB','GBL000147','Enter the charge end date');
setLanguageLabel('GB','GBL000148','Charge amount');
setLanguageLabel('GB','GBL000149','Enter the charge amount');
setLanguageLabel('GB','GBL000150','Base code');
setLanguageLabel('GB','GBL000151','Enter the base code');
setLanguageLabel('GB','GBL000152','Percentage rate');
setLanguageLabel('GB','GBL000153','Enter the percentage rate');
setLanguageLabel('GB','GBL000154','Calculate on amount');
setLanguageLabel('GB','GBL000155','This is the amount where the percentage charge is calculated from');
setLanguageLabel('GB','GBL000156','Minimum charge amount');
setLanguageLabel('GB','GBL000157','This is the minimum charge amount');
setLanguageLabel('GB','GBL000158','Maximum charge amount');
setLanguageLabel('GB','GBL000159','This is the maximum charge amount');
setLanguageLabel('GB','GBL000160','Calculated charge amount');
setLanguageLabel('GB','GBL000161','This is the calculated chargeamount');
setLanguageLabel('GB','GBL000162','Waived amount');
setLanguageLabel('GB','GBL000163','Enter the waived amount');
setLanguageLabel('GB','GBL000164','Calculation narrative 1');
setLanguageLabel('GB','GBL000165','Enter the calculation narrative line 1');
setLanguageLabel('GB','GBL000166','Calculation narrative 2');
setLanguageLabel('GB','GBL000167','Enter the calculation narrative line 2');
setLanguageLabel('GB','GBL000168','Calculation narrative 3');
setLanguageLabel('GB','GBL000169','Enter the calculation narrative line 3');
setLanguageLabel('GB','GBL000170','Calculation narrative 4');
setLanguageLabel('GB','GBL000171','Enter the calculation narrative line 4');
setLanguageLabel('GB','GBL000172','Funding account');
setLanguageLabel('GB','GBL000173','Enter the funding account');
setLanguageLabel('GB','GBL000174','Account basic number');
setLanguageLabel('GB','GBL000176','Account suffix');
setLanguageLabel('GB','GBL000178','Capitalised charge?');
setLanguageLabel('GB','GBL000179','Is the charge capitalised?');
setLanguageLabel('GB','GBL000180','Force to fee?');
setLanguageLabel('GB','GBL000181','Is the charge force to fees receivables?');
setLanguageLabel('GB','GBL000182','Posting narrative 1');
setLanguageLabel('GB','GBL000183','Enter the posting narrative line 1');
setLanguageLabel('GB','GBL000184','Posting narrative 2');
setLanguageLabel('GB','GBL000185','Enter the posting narrative line 2');
setLanguageLabel('GB','GBL000186','Posting narrative 3');
setLanguageLabel('GB','GBL000187','Enter the posting narrative line 3');
setLanguageLabel('GB','GBL000188','Posting narrative 4');
setLanguageLabel('GB','GBL000189','Enter the posting narrative line 4');
setLanguageLabel('GB','GBL000190','Sundry item');
setLanguageLabel('GB','GBL000191','Enter the sundry item');
setLanguageLabel('GB','GBL000192','User code 1');
setLanguageLabel('GB','GBL000193','Enter the user code 1');
setLanguageLabel('GB','GBL000194','User code 2');
setLanguageLabel('GB','GBL000195','Enter the user code 2');
setLanguageLabel('GB','GBL000196','Charge detail');
setLanguageLabel('GB','GBL000197','This is the charge detail');
setLanguageLabel('GB','GBL000198','Credit Risk Management');
setLanguageLabel('GB','GBL000199','This is the credit risk management screen');
setLanguageLabel('GB','GBL000200','Customer mnemonic');
setLanguageLabel('GB','GBL000201','This is the customer mnemonic');
setLanguageLabel('GB','GBL000202','Customer location');
setLanguageLabel('GB','GBL000203','');
setLanguageLabel('GB','GBL000204','Customer group');
setLanguageLabel('GB','GBL000205','This is the customer group');
setLanguageLabel('GB','GBL000206','Customer country');
setLanguageLabel('GB','GBL000207','This is the customer country');
setLanguageLabel('GB','GBL000208','Limit category');
setLanguageLabel('GB','GBL000209','This is the limit category');
setLanguageLabel('GB','GBL000210','Currency');
setLanguageLabel('GB','GBL000211','This is the currency');
setLanguageLabel('GB','GBL000212','Risk amount');
setLanguageLabel('GB','GBL000213','This is the risk amount');
setLanguageLabel('GB','GBL000214','Limit amount');
setLanguageLabel('GB','GBL000215','This is the limit amount');
setLanguageLabel('GB','GBL000216','Available amount');
setLanguageLabel('GB','GBL000217','This is the available amount');
setLanguageLabel('GB','GBL000218','Expiry date');
setLanguageLabel('GB','GBL000219','This is the expiry date');
setLanguageLabel('GB','GBL000220','Country');
setLanguageLabel('GB','GBL000221','This is the customer country');
setLanguageLabel('GB','GBL000222','In Thousand text');
setLanguageLabel('GB','GBL000223','');
setLanguageLabel('GB','GBL000224','Reference');
setLanguageLabel('GB','GBL000225','This is the reference');
setLanguageLabel('GB','GBL000226','Currency');
setLanguageLabel('GB','GBL000227','This is the currency');
setLanguageLabel('GB','GBL000228','Transaction amount');
setLanguageLabel('GB','GBL000229','This is the transaction amount');
setLanguageLabel('GB','GBL000230','Remote override');
setLanguageLabel('GB','GBL000231','Offline override');
setLanguageLabel('GB','GBL000232','Supervisor Override');
setLanguageLabel('GB','GBL000233','User id');
setLanguageLabel('GB','GBL000234','Resident branch');
setLanguageLabel('GB','GBL000235','Phone number');
setLanguageLabel('GB','GBL000236','Transaction id');
setLanguageLabel('GB','GBL000237','BankFusion Equation Desktop');
setLanguageLabel('GB','GBL000238','Date');
setLanguageLabel('GB','GBL000239','Reporting Currency');
setLanguageLabel('GB','GBL000240','Pay total');
setLanguageLabel('GB','GBL000241','Receive total');
setLanguageLabel('GB','GBL000242','Net');
setLanguageLabel('GB','GBL000243','Cumulative');
setLanguageLabel('GB','GBL000244','Totals');
setLanguageLabel('GB','GBL000245','Sub-Totals');
setLanguageLabel('GB','GBL000246','Figures in actual currency');
setLanguageLabel('GB','GBL000247','Figures in reporting currency');
setLanguageLabel('GB','GBL000248','Ccy');
setLanguageLabel('GB','GBL000249','Today');
setLanguageLabel('GB','GBL000250','Net to date');
setLanguageLabel('GB','GBL000251','Open');
setLanguageLabel('GB','GBL000252','Forward');
setLanguageLabel('GB','GBL000253','Start date');
setLanguageLabel('GB','GBL000254','End date');
setLanguageLabel('GB','GBL000255','Customer');
setLanguageLabel('GB','GBL000256','Nostro');
setLanguageLabel('GB','GBL000257','Global Customer');
setLanguageLabel('GB','GBL000258','System account');
setLanguageLabel('GB','GBL000259','Customer number');
setLanguageLabel('GB','GBL000260','Customer name');
setLanguageLabel('GB','GBL000261','Master');
setLanguageLabel('GB','GBL000262','Type');
setLanguageLabel('GB','GBL000263','Par');
setLanguageLabel('GB','GBL000264','Res');
setLanguageLabel('GB','GBL000265','Act');
setLanguageLabel('GB','GBL000266','Rsp');
setLanguageLabel('GB','GBL000267','Analysis Code');
setLanguageLabel('GB','GBL000268','Account');
setLanguageLabel('GB','GBL000269','Account short name');
setLanguageLabel('GB','GBL000270','Iban');
setLanguageLabel('GB','GBL000271','Ext account');
setLanguageLabel('GB','GBL000272','Account type');
setLanguageLabel('GB','GBL000273','Status Balance');
setLanguageLabel('GB','GBL000274','Equivalent Balance');
setLanguageLabel('GB','GBL000275','Eqv Currency');
setLanguageLabel('GB','GBL000276','Account details');
setLanguageLabel('GB','GBL000277','Transfer reference');
setLanguageLabel('GB','GBL000278','Funding account');
setLanguageLabel('GB','GBL000279','Debit account basic no');
setLanguageLabel('GB','GBL000280','Debit account suffix');
setLanguageLabel('GB','GBL000281','Funding unit');
setLanguageLabel('GB','GBL000282','Credit account');
setLanguageLabel('GB','GBL000283','Credit account basic no');
setLanguageLabel('GB','GBL000284','Credit account suffix');
setLanguageLabel('GB','GBL000285','Credit unit');
setLanguageLabel('GB','GBL000286','Funding Details');
setLanguageLabel('GB','GBL000287','Transaction code');
setLanguageLabel('GB','GBL000288','Account currency');
setLanguageLabel('GB','GBL000289','Amount');
setLanguageLabel('GB','GBL000290','Value date');
setLanguageLabel('GB','GBL000291','Narrative');
setLanguageLabel('GB','GBL000292','Debit user code 1');
setLanguageLabel('GB','GBL000293','Debit user code 2');
setLanguageLabel('GB','GBL000294','Retail rate type');
setLanguageLabel('GB','GBL000295','Exchange rate');
setLanguageLabel('GB','GBL000296','Settlement account');
setLanguageLabel('GB','GBL000297','Credit value date');
setLanguageLabel('GB','GBL000298','User codes');
setLanguageLabel('GB','GBL000299','Credit user code 1');
setLanguageLabel('GB','GBL000300','Credit user code 2');
setLanguageLabel('GB','GBL000301','Application code');
setLanguageLabel('GB','GBL000302','Rate');
setLanguageLabel('GB','GBL000303','Days');
setLanguageLabel('GB','GBL000304','Provisions');
setLanguageLabel('GB','GBL000305','Status');
setLanguageLabel('GB','GBL000306','Non accrual status');
setLanguageLabel('GB','GBL000307','Deal type');
setLanguageLabel('GB','GBL000308','Deal reference');
setLanguageLabel('GB','GBL000309','Selection criteria');
setLanguageLabel('GB','GBL000310','Selection criteria summary');
setLanguageLabel('GB','GBL000311','Details');
setLanguageLabel('GB','GBL000312','Output queue');
setLanguageLabel('GB','GBL000313','Output queue:');
setLanguageLabel('GB','GBL000314','Library:');
setLanguageLabel('GB','GBL000315','Global Customer Name');
setLanguageLabel('GB','GBL000316','Master flag');
setLanguageLabel('GB','GBL000317','Sequence');
setLanguageLabel('GB','GBL000318','System name');
setLanguageLabel('GB','GBL000319','Customer owning unit');
setLanguageLabel('GB','GBL000320','Synch ID');
setLanguageLabel('GB','GBL000321','Enquiring global customers');
setLanguageLabel('GB','GBL000322','Link customers header');
setLanguageLabel('GB','GBL000323','Maintain Global Customer');
setLanguageLabel('GB','GBL000324','Day/Time');
setLanguageLabel('GB','GBL000325','From');
setLanguageLabel('GB','GBL000326','To');
setLanguageLabel('GB','GBL000327','Transaction');
setLanguageLabel('GB','GBL000328','Key Data');
setLanguageLabel('GB','GBL000329','Last Action');
setLanguageLabel('GB','GBL000330','Applied');
setLanguageLabel('GB','GBL000331','Failed');
setLanguageLabel('GB','GBL000332','Applied (CCSID errors)');
setLanguageLabel('GB','GBL000333','Retry Request');
setLanguageLabel('GB','GBL000334','Acknowledged');
setLanguageLabel('GB','GBL000335','Deleted');
setLanguageLabel('GB','GBL000336','Warnings/Errors');
setLanguageLabel('GB','GBL000337','Apply Type');
setLanguageLabel('GB','GBL000338','To be Manually Applied');
setLanguageLabel('GB','GBL000339','Warning');
setLanguageLabel('GB','GBL000340','To be Automatically Applied');
setLanguageLabel('GB','GBL000341','Auto Apply');
setLanguageLabel('GB','GBL000342','Manual Apply');
setLanguageLabel('GB','GBL000343','Acknowledge');
setLanguageLabel('GB','GBL000344','Delete');
setLanguageLabel('GB','GBL000345','Reset');
setLanguageLabel('GB','GBL000346','Retry');
setLanguageLabel('GB','GBL000347','Action');
setLanguageLabel('GB','GBL000348','Details - figures in Actual currency');
setLanguageLabel('GB','GBL000349','Details - figures in Reporting currency');
setLanguageLabel('GB','GBL000350','Details by Unit - figures in Actual currency');
setLanguageLabel('GB','GBL000351','Details by Unit - figures in Reporting currency');
setLanguageLabel('GB','GBL000352','Details by Unit and Branch - figures in Actual currency');
setLanguageLabel('GB','GBL000353','Details by Unit and Branch - figures in Reporting currency');
setLanguageLabel('GB','GBL000354','Details by Unit');
setLanguageLabel('GB','GBL000355','Details by Unit and Branch');
setLanguageLabel('GB','GBL000356','Apply');
setLanguageLabel('GB','GBL000357','Deals');
setLanguageLabel('GB','GBL000358','App');
setLanguageLabel('GB','GBL000359','Equivalent amount');
setLanguageLabel('GB','GBL000360','Non-accrual');
setLanguageLabel('GB','GBL000361','Customers');
setLanguageLabel('GB','GBL000362','Accounts');
setLanguageLabel('GB','GBL000363','Name');
setLanguageLabel('GB','GBL000364','Number');
setLanguageLabel('GB','GBL000365','Ac');
setLanguageLabel('GB','GBL000366','Short name');
setLanguageLabel('GB','GBL000367','Debit details');
setLanguageLabel('GB','GBL000368','Credit details');
setLanguageLabel('GB','GBL000369','Customer mnemonic/location');
setLanguageLabel('GB','GBL000370','Incomplete data, user not authorised to unit(s)');
setLanguageLabel('GB','GBL000371','Input Task');   
setLanguageLabel('GB','GBL000372','Auth Task');
setLanguageLabel('GB','GBL000373','ESF Task');          
setLanguageLabel('GB','GBL000374','Claimed');
setLanguageLabel('GB','GBL000375','Task Id');
setLanguageLabel('GB','GBL000376','LRP Referral');
setLanguageLabel('GB','GBL000377','Task Authorisation');      
setLanguageLabel('GB','GBL000378','Reason for rejection');    
setLanguageLabel('GB','GBL000379','Reason for authorisation');
setLanguageLabel('GB','GBL000380','Reason for re-refering');
setLanguageLabel('GB','GBL000381','Refresh Equation Cache');
setLanguageLabel('GB','GBL000382','Page:');      
setLanguageLabel('GB','GBL000383','Page range:');
setLanguageLabel('GB','GBL000384','Range:');     
setLanguageLabel('GB','GBL000385','Page No:');
setLanguageLabel('GB','GBL000386','M/C Submitted');
setLanguageLabel('GB','GBL000387','M/C Waiting');
setLanguageLabel('GB','GBL000388','M/C Rejected');
setLanguageLabel('GB','GBL000389','M/C Approved');
setLanguageLabel('GB','GBL000390','ENTRY');
setLanguageLabel('GB','GBL000391','DELETE');
setLanguageLabel('GB','GBL000392','ENQUIRY');
setLanguageLabel('GB','GBL000393','MAINT');
setLanguageLabel('GB','GBL000394','Maker Checker');
setLanguageLabel('GB','GBL000395','Decline Authorisation Request');
setLanguageLabel('GB','GBL000396','Reason');
setLanguageLabel('GB','GBL000397','Select checker for authorisation');
setLanguageLabel('GB','GBL000400','CAS user Id');
setLanguageLabel('GB','GBL000401','Login user id');
setLanguageLabel('GB','GBL000402','Equation user id');
setLanguageLabel('GB','GBL000403','IBM i user id');
setLanguageLabel('GB','GBL000404','Transaction Workload');
setLanguageLabel('GB','GBL000405','Selection criteria');
setLanguageLabel('GB','GBL000406','Processed date');
setLanguageLabel('GB','GBL000407','Option id');
setLanguageLabel('GB','GBL000408','My work?');
setLanguageLabel('GB','GBL000409','My approvals?');
setLanguageLabel('GB','GBL000410','Category');
setLanguageLabel('GB','GBL000411','Date');
setLanguageLabel('GB','GBL000412','Option');
setLanguageLabel('GB','GBL000413','Checker');
setLanguageLabel('GB','GBL000414','Reason');
setLanguageLabel('GB','GBL000415','Maker');
setLanguageLabel('GB','GBL000416','Equation Notifications');
setLanguageLabel('GB','GBL000417','Password Error');
setLanguageLabel('GB','GBL500001','030');
setLanguageLabel('GB','GBL600001','1=Select details');
setLanguageLabel('GB','GBL600002','X=Charge not applicable');
setLanguageLabel('GB','GBL700001','PROMPT');
setLanguageLabel('GB','GBL700002','F24=Override');
setLanguageLabel('GB','GBL700003','DMY');
setLanguageLabel('GB','GBL800001','<u>O</u>ption');
setLanguageLabel('GB','GBL800002','<u>S</u>earch');
setLanguageLabel('GB','GBL900001','You must correct the following error(s) before proceeding:');
setLanguageLabel('GB','GBL900002','User ID is a required field');
setLanguageLabel('GB','GBL900003','Password is a required field');
setLanguageLabel('GB','GBL900004','Unit is a required field');
setLanguageLabel('GB','GBL900005','System is a required field');
setLanguageLabel('GB','GBL900006','The user ID and password are invalid.');
setLanguageLabel('GB','GBL900007','reset the navigation system');
setLanguageLabel('GB','GBL900008','set the navigation area to full screen');
setLanguageLabel('GB','GBL900009','Please try again.');
setLanguageLabel('GB','GBL900010','The system specified does not exist');
setLanguageLabel('GB','GBL900011','The unit specified does not exist');
setLanguageLabel('GB','GBL900012','The user ID specified is not authorised to the Unit');
setLanguageLabel('GB','GBL900013','User is not a GUI administrator');
setLanguageLabel('GB','GBL900014','Unspecified error');
setLanguageLabel('GB','GBL900015','Are you sure you want to log out ofthis unit?');
setLanguageLabel('GB','GBL900016','Are you sure you want to quit');
setLanguageLabel('GB','GBL900018','You are currently in a transaction. Please return to the initial screen before commencing a new transaction.');
setLanguageLabel('GB','GBL900019','Enter an option');
setLanguageLabel('GB','GBL900020','Enter search term');
setLanguageLabel('GB','GBL900021','Click for additional information');
setLanguageLabel('GB','GBL900022','No spooled output files');
setLanguageLabel('GB','GBL900023','No recently used options');
setLanguageLabel('GB','GBL900024','User not authorised to any option');
setLanguageLabel('GB','GBL900025','Job log entry not found');
setLanguageLabel('GB','GBL900026','Refresh the job log and retry');
setLanguageLabel('GB','GBL900027','Message queue entry not found');
setLanguageLabel('GB','GBL900028','Refresh the message queue and retry');
setLanguageLabel('GB','GBL900029','Your session has expired, please re-enter your login details');
setLanguageLabel('GB','GBL900030','The Equation Desktop administratorhas suspended the input system you will now be logged out');
setLanguageLabel('GB','GBL900031','You are currently in a transaction. Please return to the initial screen before logging off.');
setLanguageLabel('GB','GBL900032','You are currently in a transaction. Please return to the initial screen before switching unit.');
setLanguageLabel('GB','GBL900033','You are currently in a transaction. Please return to the initial screen before suspending the input system');
setLanguageLabel('GB','GBL900034','The Equation Desktop administratorhas suspended the Equation desktop you will now be logged out');
setLanguageLabel('GB','GBL900035','The Equation Desktop administratorhas suspended the Equation desktop');
setLanguageLabel('GB','GBL900036','Equation Desktop suspended, now logging off');
setLanguageLabel('GB','GBL900037','You are currently in a transaction. Please return to the initial screen before suspending Equation desktop');
setLanguageLabel('GB','GBL900038','An error has occured, restarting Equation Desktop');
setLanguageLabel('GB','GBL900039','No details to display');
setLanguageLabel('GB','GBL900040','Invalid function key');
setLanguageLabel('GB','GBL900041','Transaction %2 has been authorised by %1');
setLanguageLabel('GB','GBL900042','Transaction %2 has been rejected by %1');
setLanguageLabel('GB','GBL900043','User %1 has cancelled the %2 authorisation request');
setLanguageLabel('GB','GBL900044','User %1 requires authorisation for transaction of type %2');
setLanguageLabel('GB','GBL900045','Transaction %2 request has timed out from user %1');
setLanguageLabel('GB','GBL900046','Cannot process request until other windows are closed');
setLanguageLabel('GB','GBL900047','Cursor must be on an open key field');
setLanguageLabel('GB','GBL900048','Error executing onblur user exit routine');
setLanguageLabel('GB','GBL900049','Error on field &1:');
setLanguageLabel('GB','GBL900050','Cursor must be positioned in a group field');
setLanguageLabel('GB','GBL900051','Invalid selection');
setLanguageLabel('GB','GBL900052','Transaction %2 has been partially authorised by %1');
setLanguageLabel('GB','GBL900053','Cannot open another transaction as another transaction is already open');
setLanguageLabel('GB','GBL900054','Awaiting supervisor approval ...');
setLanguageLabel('GB','GBL900055','Request has timed out.');
setLanguageLabel('GB','GBL900056','The supervisor has not begun to process your request.');
setLanguageLabel('GB','GBL900057','Supervisor reviewing request ...');
setLanguageLabel('GB','GBL900058','Your request has been refused by the supervisor');
setLanguageLabel('GB','GBL900059','Your request has been approved');
setLanguageLabel('GB','GBL900060','Your request has been partially approved');
setLanguageLabel('GB','GBL900061','The supervisor has cancelled the review');
setLanguageLabel('GB','GBL900062','You have cancelled the request');
setLanguageLabel('GB','GBL900063','Retry after');
setLanguageLabel('GB','GBL900064','Transaction ID must be entered');
setLanguageLabel('GB','GBL900065','Reason must be entered');
setLanguageLabel('GB','GBL900066','Transaction %2 referral from another user %1');
setLanguageLabel('GB','GBL900067','Data not available for unit(s) %1');
setLanguageLabel('GB','GBL900068','Output queue must be entered');
setLanguageLabel('GB','GBL900069','Library must be entered');
setLanguageLabel('GB','GBL900070','Enter the library name to refresh the list of output queues');
setLanguageLabel('GB','GBL900071','Select an output queue from the list');
setLanguageLabel('GB','GBL900072','Enter the name of the output queue');
setLanguageLabel('GB','GBL900073','No selected output queue');
setLanguageLabel('GB','GBL900074','Long running process is not enabled.');    
setLanguageLabel('GB','GBL900075','No task comment.');                       
setLanguageLabel('GB','GBL900076','This is not a Long running process task.');
setLanguageLabel('GB','GBL900077','Exception has occured, check server log.');
setLanguageLabel('GB','GBL900078','Add comment:');
setLanguageLabel('GB','GBL900079','Are you sure you want to refresh desktop cache?'); 
setLanguageLabel('GB','GBL900080','Desktop cache refreshed.');                        
setLanguageLabel('GB','GBL900081','Session has timed-out.');
setLanguageLabel('GB','GBL900082','WebFacing session has timed-out.');                                           
setLanguageLabel('GB','GBL900083','An error occured.  Press OK to recover.  Press Cancel to display the error.');
setLanguageLabel('GB','GBL900084','Either the server has been restarted/stopped or the session timed-out.');
setLanguageLabel('GB','GBL900085','Server may not be running anymore.Close Equation Desktop.');
setLanguageLabel('GB','GBL900086','An unrecoverable error occured.  Close Equation Desktop.');
setLanguageLabel('GB','GBL900087','Loading spooled file, please wait . . .');
setLanguageLabel('GB','GBL900088','The requested number of pages is more than the specified limit.  It will take time to load the pages.');
setLanguageLabel('GB','GBL900089','Maker %1 requires approval for transaction  %2');
setLanguageLabel('GB','GBL900090','Transaction %2 has been approved by checker %1');
setLanguageLabel('GB','GBL900091','Transaction %2 has been rejected by checker %1');
setLanguageLabel('GB','GBL900092','Transaction %2 has been completed by checker %1');
setLanguageLabel('GB','GBL900093','Please close the WebFacing %1 tab before logging off.');
setLanguageLabel('GB','GBL900094','Unable to load Equation transaction');
setLanguageLabel('GB','GBL900095','Option must be specified ');
setLanguageLabel('GB','GBL900096','You must complete or exit the currently active WebFacing function before running this one.');
setLanguageLabel('GB','GBL900097','Please close the WebFacing %1 tab before signing off.');
setLanguageLabel('GB','GBL900098','Please complete or cancel the WebFacing transaction before closing the tab.');
setLanguageLabel('GB','GBL900099','User %1 requests a Webfacing referral for option %2');
setLanguageLabel('GB','GBL900100','Transaction Workflow Enquiry');
setLanguageLabel('GB','GBL900101','Referrals processing only supported on IE.');
setLanguageLabel('GB','GBL900102','WebFacing');
setLanguageLabel('GB','GBL900103','Unable to load desktop resources');
setLanguageLabel('GB','GBL900104','You are not logged into BFEQ. If you need to access BFEQ transactions, contact the Administrator');
setLanguageLabel('GB','GBL900105','BFEQ transactions ready for use');
setLanguageLabel('GB','GBL900106','Failed to create %1 object.  This may be caused by using the -extoff IE setting [ %2 ]');
setLanguageLabel('GB','GBL900107','Session time-out or unable to login to BFEQ');
setLanguageLabel('GB','GBL900108','ESF Submitted');
setLanguageLabel('GB','GBL900109','ESF Waiting');
setLanguageLabel('GB','GBL900110','ESF Rejected');
setLanguageLabel('GB','GBL900111','ESF Approved');
setLanguageLabel('GB','GBL900112','ESF Part Approved');
setLanguageLabel('GB','GBL900113','Reason for decline, save transaction id');
setLanguageLabel('GB','GBL900114','Template id');
setLanguageLabel('GB','GBL900115','Transaction has been submitted');
setLanguageLabel('GB','GBL900116','Resume Equation Input and Enquiry');
setLanguageLabel('GB','GBL900117','Equation Input and Enquiry Suspended');
setLanguageLabel('GB','GBL900118','Equation Input and Enquiry Activated');
setLanguageLabel('GB','GBL900119','Suspend Equation Input and Enquiry');
setLanguageLabel('GB','GCODES','Guaranteed or certified - SDGC');
setLanguageList('GB','GCOVAL',['C','G']);
setLanguageList('GB','GCODSC',['Certified','Guaranteed']);
setLanguageLabel('GB','HDRDES','Header');
setLanguageLabel('GB','HD2DES','Header for 1 command key line');
setLanguageLabel('GB','HFWDES','Header footer widget only');
setLanguageLabel('GB','HOTDES','Hedge or trade');
setLanguageList('GB','HOTVAL',['H','T']);
setLanguageList('GB','HOTDSC',['Hedge','Trade']);
setLanguageLabel('GB','HRLDES','Horizontal line');
setLanguageLabel('GB','HTPDES','Charge type');
setLanguageList('GB','HTPVAL',['F','P','U']);
setLanguageList('GB','HTPDSC',['Flat charges per deal','Percentage of deal amount','Flat charges per unit of deal amt']);
setLanguageLabel('GB','IBSDES','Interest bearing');
setLanguageList('GB','IBSVAL',['F','N','S']);
setLanguageList('GB','IBSDSC',['Floating rate','Non-interest bearing','Straight']);
setLanguageLabel('GB','ICBDES','Interest calc base');
setLanguageList('GB','ICBVAL',['B','Y']);
setLanguageList('GB','ICBDSC',['B','Y']);
setLanguageLabel('GB','ICFDES','Instruction code');
setLanguageList('GB','ICFVAL',['BONL','CHQB','CORT','HOLD','INTC','PHOB','PHOI','PHON','REPA','SDVA','TELB','TELE','TELI']);
setLanguageList('GB','ICFDSC',['Payment to beneficary only','Pay beneficiary cust by cheque','Payment made in settle of a trade','Beneficiary will call','Intra-company payment','Advise beneficiary by phone','Advise intermediary inst by phone','Advise institution by phone','Has e-payment reference','Execute payment with same day value','Advise beneficiary','Advise institution','Advise intermediary institution']);
setLanguageLabel('GB','ICLDES','Interest calculated on');
setLanguageList('GB','ICLVAL',['1','2']);
setLanguageList('GB','ICLDSC',['Actual balance','Schedule balance']);
setLanguageLabel('GB','IDBDES','Interest days basis');
setLanguageList('GB','IDBVAL',['0','1','2','3','4','5','6']);
setLanguageList('GB','IDBDSC',['   /365','   /360','   /365-6',' 30/360',' 30/365',' 30/365-6','30/360G']);
setLanguageLabel('GB','IDODES','Increase or decreased - SDPID');
setLanguageList('GB','IDOVAL',['D','I']);
setLanguageList('GB','IDODSC',['Decrease','Increase']);
setLanguageLabel('GB','ID1DES','Insert or delete');
setLanguageList('GB','ID1VAL',['D','I']);
setLanguageList('GB','ID1DSC',['Delete','Insert']);
setLanguageLabel('GB','ID2DES','Interest days basis');
setLanguageList('GB','ID2VAL',['A','0','1','2','3','4','5']);
setLanguageList('GB','ID2DSC',['Constant repayment','/365','/360','/365-6','30/360','30/365','30/365-6']);
setLanguageLabel('GB','IFQDES','Frequency');
setLanguageList('GB','IFQVAL',['1','2','3','4']);
setLanguageList('GB','IFQDSC',['Annual','Bi-annual','Quarterly','Monthly']);
setLanguageLabel('GB','IMTDES','Instruction movement type');
setLanguageList('GB','IMTVAL',['A','I','P']);
setLanguageList('GB','IMTDSC',['All','Interest','Principal']);
setLanguageLabel('GB','INEDES','Include/Exclude');
setLanguageList('GB','INEVAL',['I','N']);
setLanguageList('GB','INEDSC',['Include','Exclude']);
setLanguageLabel('GB','INPDES','Input characteristics');
setLanguageList('GB','INPVAL',['M','N','O','P']);
setLanguageList('GB','INPDSC',['Mandatory','Not applicable','Optional','Predefined']);
setLanguageLabel('GB','INSDES','Insert');
setLanguageList('GB','INSVAL',['I']);
setLanguageList('GB','INSDSC',['Insert']);
setLanguageLabel('GB','INTDES','Interest rate type');
setLanguageList('GB','INTVAL',['1','2','3','4']);
setLanguageList('GB','INTDSC',['Base/Diff/Margin','Actual rate','Pegged rate','Any']);
setLanguageLabel('GB','IPMDES','Interpolation method');
setLanguageList('GB','IPMVAL',['E','S']);
setLanguageList('GB','IPMDSC',['Exponential','Straight line']);
setLanguageLabel('GB','IPODES','Interest posting');
setLanguageList('GB','IPOVAL',['1','2','3']);
setLanguageList('GB','IPODSC',['Interest at maturity','At inception','Interest frequency']);
setLanguageLabel('GB','IP1DES','Interest posting');
setLanguageList('GB','IP1VAL',['1','2','3','4']);
setLanguageList('GB','IP1DSC',['Interest at maturity','In advance','Interest frequency','Review frequency']);
setLanguageLabel('GB','IP2DES','Interest posting');
setLanguageList('GB','IP2VAL',['1','2','3','4']);
setLanguageList('GB','IP2DSC',['Interest at maturity','At inception','Interest frequency','Rollover date']);
setLanguageLabel('GB','IRADES','Indicative rates assign');
setLanguageList('GB','IRAVAL',['0','1','2','3']);
setLanguageList('GB','IRADSC',['Zero','Previous profit rate','Specified value','External']);
setLanguageLabel('GB','IRCDES','Rate changes');
setLanguageList('GB','IRCVAL',['1','2','3']);
setLanguageList('GB','IRCDSC',['No interim changes','Any date','Interest review date']);
setLanguageLabel('GB','IRPDES','Increase or reduce');
setLanguageList('GB','IRPVAL',['1','2']);
setLanguageList('GB','IRPDSC',['Increase period','Reduce period']);
setLanguageLabel('GB','IRTDES','Interest rate type');
setLanguageList('GB','IRTVAL',['1','2','4']);
setLanguageList('GB','IRTDSC',['Base/Diff/Margin','Actual rate','Any']);
setLanguageLabel('GB','IR2DES','Rate changes');
setLanguageList('GB','IR2VAL',['1','2','3']);
setLanguageList('GB','IR2DSC',['No interim changes','Interim rate change','Rollover date']);
setLanguageLabel('GB','IXIDES','Include or exclude');
setLanguageList('GB','IXIVAL',['C','L']);
setLanguageList('GB','IXIDSC',['Exclude','Include']);
setLanguageLabel('GB','JTTDES','Function type');
setLanguageList('GB','JTTVAL',['A','D','M']);
setLanguageList('GB','JTTDSC',['Add','Delete','Maintain']);
setLanguageLabel('GB','LBLDES','Label');
setLanguageLabel('GB','LBRDES','Label - right aligned');
setLanguageLabel('GB','LIODES','Inward/Outward');
setLanguageList('GB','LIOVAL',['1','2']);
setLanguageList('GB','LIODSC',['Inward','Outward']);
setLanguageLabel('GB','LMTDES','Message type');
setLanguageList('GB','LMTVAL',['1','2']);
setLanguageList('GB','LMTDSC',['Customer transfer','Interbank transfer']);
setLanguageLabel('GB','LODDES','Loan or deposit');
setLanguageList('GB','LODVAL',['D','L']);
setLanguageList('GB','LODDSC',['Deposit','Loan']);
setLanguageLabel('GB','LO1DES','AOE Available Options');
setLanguageList('GB','LO1VAL',['1','2','3','4','5','6','7']);
setLanguageList('GB','LO1DSC',['Account Summary Enquiry','Account Enquiry','Account Balance Enquiry','Account Balances by Calendar Month','Account Turnover by Calendar Month','Account Cheque Clearing Enquiry','Account Status History Enquiry']);
setLanguageLabel('GB','LSTDES','Limit structure type');
setLanguageList('GB','LSTVAL',['B','C','G']);
setLanguageList('GB','LSTDSC',['Both','Country','Group/Customer']);
setLanguageLabel('GB','LTRDES','Left to right display file');
setLanguageLabel('GB','LVADES','Limit override');
setLanguageList('GB','LVAVAL',['N','S','Y']);
setLanguageList('GB','LVADSC',['User is not authorised to override','Supervisor user ID is needed','User is authorised to override']);
setLanguageLabel('GB','LVLDES','Program level');
setLanguageLabel('GB','MDRDES','Maturing deposit rule');
setLanguageList('GB','MDRVAL',['0','1','2','3']);
setLanguageList('GB','MDRDSC',['Indicative rate will be used','Use the previous period profit rate','Zero for the final period','Payment delayed until next profit']);
setLanguageLabel('GB','MD1DES','Maintain or Delete');
setLanguageList('GB','MD1VAL',['D','M']);
setLanguageList('GB','MD1DSC',['Delete','Maintain']);
setLanguageLabel('GB','MNTDES','Maintain');
setLanguageList('GB','MNTVAL',['M']);
setLanguageList('GB','MNTDSC',['Maintain']);
setLanguageLabel('GB','MODDES','Modifier');
setLanguageList('GB','MODVAL',['1','2','3']);
setLanguageList('GB','MODDSC',['Absolute value','Multiplier','Offset']);
setLanguageLabel('GB','MONDES','Months');
setLanguageList('GB','MONVAL',['01','02','03','04','05','06','07','08','09','10','11','12']);
setLanguageList('GB','MONDSC',['January','February','March','April','May','June','July','August','September','October','November','December']);
setLanguageLabel('GB','MRUDES','Minimum rule');
setLanguageList('GB','MRUVAL',['1','2']);
setLanguageList('GB','MRUDSC',['Round up to minimum','Waive below minimum']);
setLanguageLabel('GB','MSCDES','Message control');
setLanguageLabel('GB','MSLDES','Apply date');
setLanguageList('GB','MSLVAL',['1','10','11','12','2','3','4','5','6','7','8','9']);
setLanguageList('GB','MSLDSC',['One','Ten','Eleven','Twelve','Two','Three','Four','Five','Six','Seven','Eight','Nine']);
setLanguageLabel('GB','MSTDES','Message status');
setLanguageList('GB','MSTVAL',['1','3']);
setLanguageList('GB','MSTDSC',['Received on Clean Payments database','Processing has failed']);
setLanguageLabel('GB','MTODES','Maintenance option');
setLanguageList('GB','MTOVAL',['1','2','3']);
setLanguageList('GB','MTODSC',['Suspend','Release','Maint']);
setLanguageLabel('GB','MVEDES','Maintain or View Exceptions');
setLanguageList('GB','MVEVAL',['M','V']);
setLanguageList('GB','MVEDSC',['Maintain','View Exceptions']);
setLanguageLabel('GB','MVTDES','Movement type');
setLanguageList('GB','MVTVAL',['F','P','R']);
setLanguageList('GB','MVTDSC',['Fee','Principal','Repayment']);
setLanguageLabel('GB','NDPDES','Non display');
setLanguageLabel('GB','NMODES','Data required');
setLanguageList('GB','NMOVAL',['M','N','O']);
setLanguageList('GB','NMODSC',['Mandatory','No','Optional']);
setLanguageLabel('GB','NOADES','Number of authorisers');
setLanguageList('GB','NOAVAL',['1','2','3','4','5','6','7','8','9']);
setLanguageList('GB','NOADSC',['One','Two','Three','Four','Five','Six','Seven','Eight','Nine']);
setLanguageLabel('GB','NOCDES','Denomination');
setLanguageList('GB','NOCVAL',['C','N']);
setLanguageList('GB','NOCDSC',['Coin','Note']);
setLanguageLabel('GB','NPFDES','Non proportional font');
setLanguageLabel('GB','NVODES','Nostro or vostro');
setLanguageList('GB','NVOVAL',['1','2']);
setLanguageList('GB','NVODSC',['Nostro','Vostro']);
setLanguageLabel('GB','NWSDES','Notice withdrawal status');
setLanguageList('GB','NWSVAL',['0','1','2']);
setLanguageList('GB','NWSDSC',['For review','Pending','Manual']);
setLanguageLabel('GB','NWTDES','Notice withdrawal type');
setLanguageList('GB','NWTVAL',['1','2','3','4']);
setLanguageList('GB','NWTDSC',['Notice','Free','Penalty','Combined']);
setLanguageLabel('GB','OCTDES','Movement type');
setLanguageList('GB','OCTVAL',['C','D','F','I','P']);
setLanguageList('GB','OCTDSC',['Amortised charge','Discount','One off fee','Interest','Principal']);
setLanguageLabel('GB','OFPDES','Offline period');
setLanguageList('GB','OFPVAL',['1','2','3','4','5','6','7']);
setLanguageList('GB','OFPDSC',['One','Two','Three','Four','Five','Six','Seven']);
setLanguageLabel('GB','OMPDES','Optional or mandatory');
setLanguageList('GB','OMPVAL',['M','O']);
setLanguageList('GB','OMPDSC',['Mandatory','Optional']);
setLanguageLabel('GB','OOADES','Or/And');
setLanguageList('GB','OOAVAL',['A','O']);
setLanguageList('GB','OOADSC',['And','Or']);
setLanguageLabel('GB','OOQDES','Override output queue');
setLanguageList('GB','OOQVAL',['SCRN','UNIT','USER']);
setLanguageList('GB','OOQDSC',['Display output on the screen','Unit output queue','User output queue']);
setLanguageLabel('GB','OPCDES','Operation code');
setLanguageList('GB','OPCVAL',['G','I','L','N','R','X']);
setLanguageList('GB','OPCDSC',['Greater than','Include','Less than','Not equal','Range','Not in range']);
setLanguageLabel('GB','OPTDES','Option picker');
setLanguageLabel('GB','OREDES','Include repayments');
setLanguageList('GB','OREVAL',['1','2','3']);
setLanguageList('GB','OREDSC',['All repayments','Late/partial/overdue repayments','Partial/overdue repayments']);
setLanguageLabel('GB','OSTDES','Implementation status');
setLanguageList('GB','OSTVAL',['I','L']);
setLanguageList('GB','OSTDSC',['Being implemented at the branch','Live at the branch']);
setLanguageLabel('GB','OTYDES','Option Type');
setLanguageList('GB','OTYVAL',['1','2','3']);
setLanguageList('GB','OTYDSC',['Major processing characteristic','System variable','Control system tailoring']);
setLanguageLabel('GB','OURDES','Output field - right aligned');
setLanguageLabel('GB','OUTDES','Output field');
setLanguageLabel('GB','PALDES','Penalty interest method');
setLanguageList('GB','PALVAL',['0','1','2']);
setLanguageList('GB','PALDSC',['No penalty to be calculated','Calculated based on the excess bal','Calculated based on the full bal']);
setLanguageLabel('GB','PBRDES','Branch reference');
setLanguageList('GB','PBRVAL',['01','02','03','04','05']);
setLanguageList('GB','PBRDSC',['Receive settlement','Pay settlement','Chief local','Input','Default customer']);
setLanguageLabel('GB','PCADES','Penalty calculation');
setLanguageList('GB','PCAVAL',['1','2','3']);
setLanguageList('GB','PCADSC',['Fixed amount','Per time per amount','Forgo interest']);
setLanguageLabel('GB','PCDDES','Payment code');
setLanguageList('GB','PCDVAL',['001','017','018','019']);
setLanguageList('GB','PCDDSC',['Initial payment','Normal payment','Re-presented payment','Final payment']);
setLanguageLabel('GB','PCLDES','Penalty calc basis');
setLanguageList('GB','PCLVAL',['1','2','3']);
setLanguageList('GB','PCLDSC',['Unpaid principal','Unpaid princ + int','Unpaid princ & int separately']);
setLanguageLabel('GB','PCNDES','ON/2 posting code number');
setLanguageList('GB','PCNVAL',['1','2']);
setLanguageList('GB','PCNDSC',['User Code 1','User Code 2']);
setLanguageLabel('GB','PDODES','Premium or discount - SDPDI');
setLanguageList('GB','PDOVAL',['-','D','P']);
setLanguageList('GB','PDODSC',['Discount','Discount','Premium']);
setLanguageLabel('GB','PGMDES','Program name');
setLanguageLabel('GB','PGTDES','Program title');
setLanguageLabel('GB','PHADES','Phase');
setLanguageList('GB','PHAVAL',['C00','C05','C15','C40','C80','MAN']);
setLanguageList('GB','PHADSC',['Start of business hours','Start of end of day processing','After end of day interest accruals','After end of day processing','Start of day','Manually']);
setLanguageLabel('GB','PHSDES','Phase');
setLanguageList('GB','PHSVAL',['C00','C05','C10','C15','C20','C30','C35','C40','C41','C42','C43','C45','C65','C80','C85','C90','DAY']);
setLanguageList('GB','PHSDSC',['C00','C05','C10','C15','C20','C30','C35','C40','C41','C42','C43','C45','C65','C80','C85','C90','Day']);
setLanguageLabel('GB','PH2DES','Phase');
setLanguageList('GB','PH2VAL',['C15','C80']);
setLanguageList('GB','PH2DSC',['End of day','Start of day']);
setLanguageLabel('GB','PINDES','Price indicator');
setLanguageList('GB','PINVAL',['D','P','Y']);
setLanguageList('GB','PINDSC',['Discount rate','Price per 100 units of nominal val','Yield to maturity']);
setLanguageLabel('GB','PMADES','F4 - Prompt with *');
setLanguageLabel('GB','PMTDES','F4 - Standard prompt');
setLanguageLabel('GB','PRADES','Post revaluation adjustments');
setLanguageList('GB','PRAVAL',['AE']);
setLanguageList('GB','PRADSC',['Accounting entries to be posted']);
setLanguageLabel('GB','PRCDES','Process code');
setLanguageList('GB','PRCVAL',['1','2','3']);
setLanguageList('GB','PRCDSC',['Bill','Promissory note','Cheque']);
setLanguageLabel('GB','PRFDES','Pay or receive');
setLanguageList('GB','PRFVAL',['P','R']);
setLanguageList('GB','PRFDSC',['Pay','Receive']);
setLanguageLabel('GB','PRMDES','Parameter');
setLanguageList('GB','PRMVAL',['SD','SM','SN','ZP']);
setLanguageList('GB','PRMDSC',['System dictionary','System messages','System notation','Prompt screen titles']);
setLanguageLabel('GB','PRODES','Period');
setLanguageList('GB','PROVAL',['1','2','3']);
setLanguageList('GB','PRODSC',['Full period','Each day notice not given','Each month notice not given']);
setLanguageLabel('GB','PRTDES','Penalty rate type');
setLanguageList('GB','PRTVAL',['1','2','3','4','5']);
setLanguageList('GB','PRTDSC',['Fixed rate','Fixed rate less normal rate','Base/Diff/Margin','Loan rate + margin','Loan rate+percentage']);
setLanguageLabel('GB','PR2DES','Process code');
setLanguageList('GB','PR2VAL',['00','01','02','03','04','05','06','07','08','09','10','11','12']);
setLanguageList('GB','PR2DSC',['Pre-Logged','Logged','Reviewed','Authorised','Sent for Collection','Paid','Unpaid','Cancelled','Sent to Court','Returned with Paymen','Returned without Payment','Referred (for House cheques/bills)','Withdrawn']);
setLanguageLabel('GB','PR3DES','Process code');
setLanguageList('GB','PR3VAL',['1','2','3','4','5']);
setLanguageList('GB','PR3DSC',['Collateral','Standby collateral','Collection','Collection - blacklisted collateral','Discounted cheque']);
setLanguageLabel('GB','PR4DES','Process code');
setLanguageList('GB','PR4VAL',['1','2','3','4','5']);
setLanguageList('GB','PR4DSC',['House','Local clearing house','Collection inside city','Collection outside city','Cash']);
setLanguageLabel('GB','PTDDES','Enquiry or Update');
setLanguageList('GB','PTDVAL',['E','U']);
setLanguageList('GB','PTDDSC',['Enquiry','Update']);
setLanguageLabel('GB','PTODES','Profit type');
setLanguageList('GB','PTOVAL',['1','2','3','4','5','6','7','8']);
setLanguageList('GB','PTODSC',['Charges','FX','DR interest','CR interest','Charges by month','FX by month','DR interest by month','CR interest by month']);
setLanguageLabel('GB','PUSDES','Purchase or sale');
setLanguageList('GB','PUSVAL',['P','S']);
setLanguageList('GB','PUSDSC',['Purchase','Sale']);
setLanguageLabel('GB','PVRDES','P/V data - right aligned');
setLanguageLabel('GB','PVSDES','P/V data');
setLanguageLabel('GB','PYFDES','Payment funded from');
setLanguageList('GB','PYFVAL',['1','2','3']);
setLanguageList('GB','PYFDSC',['Cash/internal','Customer account','Nostro']);
setLanguageLabel('GB','QOTDES','Query output type');
setLanguageList('GB','QOTVAL',['1','2','3']);
setLanguageList('GB','QOTDSC',['Display','Printer','Database file']);
setLanguageLabel('GB','QT1DES','TQM Available Options');
setLanguageList('GB','QT1VAL',['M','1','2','3','4']);
setLanguageList('GB','QT1DSC',['Maintain','Work with','Enquire','Audit','Account Enquiries']);
setLanguageLabel('GB','RAADES','Release account/deal action');
setLanguageList('GB','RAAVAL',['1','2']);
setLanguageList('GB','RAADSC',['Release','Maintain']);
setLanguageLabel('GB','RDADES','Rollover date action');
setLanguageList('GB','RDAVAL',['0','1']);
setLanguageList('GB','RDADSC',['None','Set open if instruction not receive']);
setLanguageLabel('GB','RDFDES','Reformat and remove dots');
setLanguageLabel('GB','RDPDES','Rounding - decimal position');
setLanguageList('GB','RDPVAL',['0','1','2','3','4','5','6','7']);
setLanguageList('GB','RDPDSC',['Zero','One','Two','Three','Four','Five','Six','Seven']);
setLanguageLabel('GB','REFAUT','Authorise');
setLanguageLabel('GB','REFDES','ESF referral');
setLanguageLabel('GB','REFIGN','Ignore');
setLanguageLabel('GB','REFOPT','Option:');
setLanguageLabel('GB','REFREQ','Requires authorisation for');
setLanguageLabel('GB','REFTIT','Referral alert');
setLanguageLabel('GB','REFUSR','User:');
setLanguageLabel('GB','RGBDES','Registered/Bearer');
setLanguageList('GB','RGBVAL',['B','R']);
setLanguageList('GB','RGBDSC',['Bearer','Registered']);
setLanguageLabel('GB','RGTDES','Reporting group type');
setLanguageList('GB','RGTVAL',['1','2','3','4','5','6']);
setLanguageList('GB','RGTDSC',['Non-banks - connected','Non-banks - not connected','Banks - connected','Banks - not connected','Government/Central banks - Zone A','Government/Central banks - Zone B']);
setLanguageLabel('GB','RITDES','Branch reference');
setLanguageList('GB','RITVAL',['1','2','3','4']);
setLanguageList('GB','RITDSC',['Posting','Charge','Hold','Report']);
setLanguageLabel('GB','RMDDES','Revaluation method');
setLanguageList('GB','RMDVAL',['L','M']);
setLanguageList('GB','RMDDSC',['Lower of market or book value','Mark to market price']);
setLanguageLabel('GB','ROQDES','Report output queue');
setLanguageList('GB','ROQVAL',['UNIT','USER','']);
setLanguageList('GB','ROQDSC',['Unit output queue','User output queue','Input a branch output queue']);
setLanguageLabel('GB','RPADES','Release profit action');
setLanguageList('GB','RPAVAL',['1','2','3']);
setLanguageList('GB','RPADSC',['Release','Products','Accounts/deals']);
setLanguageLabel('GB','RPDDES','Replace dots');
setLanguageLabel('GB','RPMDES','Repayment method');
setLanguageList('GB','RPMVAL',['1','2','3']);
setLanguageList('GB','RPMDSC',['Manual repayment','Automatic repayment','Direct debit']);
setLanguageLabel('GB','RPRDES','Release product action');
setLanguageList('GB','RPRVAL',['1','2']);
setLanguageList('GB','RPRDSC',['Release','Accounts/deals']);
setLanguageLabel('GB','RPYDES','Repay if insuff fund');
setLanguageList('GB','RPYVAL',['1','2','3']);
setLanguageList('GB','RPYDSC',['No repayment','Partial repayment','Force full repayment']);
setLanguageLabel('GB','RQUDES','Reason transaction queued');
setLanguageList('GB','RQUVAL',['1','2','3','4','5','6','7','8']);
setLanguageList('GB','RQUDSC',['No available balance','Higher priority transaction existed','Held until future value date','Court order','Forced or all for account queued','Manually repaid loans','Linked transaction','Queued for another reason']);
setLanguageLabel('GB','RSCDES','Reason code');
setLanguageList('GB','RSCVAL',['1','2','3','4']);
setLanguageList('GB','RSCDSC',['Account closed','Card lost','Card stolen','Irregular']);
setLanguageLabel('GB','RTLDES','Right to left display file');
setLanguageLabel('GB','RTPDES','Report type');
setLanguageList('GB','RTPVAL',['B','F','S']);
setLanguageList('GB','RTPDSC',['Both','Full report','Summary report']);
setLanguageLabel('GB','RTYDES','Interest rate type');
setLanguageList('GB','RTYVAL',['D','F','N','V']);
setLanguageList('GB','RTYDSC',['Derived','Fixed','N/A','Variable']);
setLanguageLabel('GB','R1BDES','Selection field - nonsubfile');
setLanguageList('GB','R1BVAL',['1']);
setLanguageList('GB','R1BDSC',['1']);
setLanguageLabel('GB','SAPDES','Schedule Advice Print options');
setLanguageList('GB','SAPVAL',['1','2','3']);
setLanguageList('GB','SAPDSC',['No schedule advice will be produced','Produce schedule advice immediately','Produce advice at end of day']);
setLanguageLabel('GB','SAUDES','Select, authorise or unauthorise');
setLanguageList('GB','SAUVAL',['A','U','1']);
setLanguageList('GB','SAUDSC',['Authorise','Unauthorise','Select']);
setLanguageLabel('GB','SBMDES','Select / send break message');
setLanguageList('GB','SBMVAL',['1','2']);
setLanguageList('GB','SBMDSC',['Select','Send break message']);
setLanguageLabel('GB','SCHDES','Schedule recalculate');
setLanguageList('GB','SCHVAL',['0','1','2','3']);
setLanguageList('GB','SCHDSC',['Manual principal and interest','Manual principal','Automatic','Manual dates']);
setLanguageLabel('GB','SELDES','Selection field');
setLanguageLabel('GB','SENDES','Start of excess/non-excess');
setLanguageList('GB','SENVAL',['E','N']);
setLanguageList('GB','SENDSC',['Excess','Non-excess']);
setLanguageLabel('GB','SFODES','Settlement Formula');
setLanguageList('GB','SFOVAL',['A','G','U']);
setLanguageList('GB','SFODSC',['Australian','Standard','American']);
setLanguageLabel('GB','SGNDES','Sign');
setLanguageList('GB','SGNVAL',['N','P']);
setLanguageList('GB','SGNDSC',['-','+']);
setLanguageLabel('GB','SITDES','Settlement instruction for');
setLanguageList('GB','SITVAL',['C','I','L','P']);
setLanguageList('GB','SITDSC',['Charges','Interest','CLS Principal','Principal']);
setLanguageLabel('GB','SLTDES','Use system or local time');
setLanguageList('GB','SLTVAL',['1','2']);
setLanguageList('GB','SLTDSC',['System','Local']);
setLanguageLabel('GB','SOADES','Sign of amount');
setLanguageList('GB','SOAVAL',['B','C','D']);
setLanguageList('GB','SOADSC',['Debit or credit','Always credit','Always debit']);
setLanguageLabel('GB','SPADES','Purchases to be allocated');
setLanguageList('GB','SPAVAL',['S']);
setLanguageList('GB','SPADSC',['Show purchases to be allocated']);
setLanguageLabel('GB','STADES','Status');
setLanguageList('GB','STAVAL',['A','S','U']);
setLanguageList('GB','STADSC',['Authorised','Saved ready for authorisation','Not saved or authorised']);
setLanguageLabel('GB','STCDES','Status code');
setLanguageList('GB','STCVAL',['1','2']);
setLanguageList('GB','STCDSC',['Active','Inactive']);
setLanguageLabel('GB','STRDES','Constant script - do not use');
setLanguageLabel('GB','STSDES','Transfer status');
setLanguageList('GB','STSVAL',['C','E','M','N','P','R','X']);
setLanguageList('GB','STSDSC',['Completed transfer','Error in transfer','Manually checked transfer','Reconciled transfer','Pending transfer','Rejected transfer','Rejected then reversed transfer']);
setLanguageLabel('GB','STYDES','Settlement Type');
setLanguageList('GB','STYVAL',['A','C','N']);
setLanguageList('GB','STYDSC',['Review ad-hoc netting groups','Review compensation groups','Review netting groups']);
setLanguageLabel('GB','ST1DES','Message status');
setLanguageList('GB','ST1VAL',['1','2','3','4']);
setLanguageList('GB','ST1DSC',['Not yet processed','Processed','Processing failed','Manual processing']);
setLanguageLabel('GB','ST2DES','Status');
setLanguageList('GB','ST2VAL',['1','2','3','4','5']);
setLanguageList('GB','ST2DSC',['Active','Lost','Voided','Stopped','Used']);
setLanguageLabel('GB','SURDES','Spot/User Rate');
setLanguageList('GB','SURVAL',['S','U']);
setLanguageList('GB','SURDSC',['Spot Rate','User Rate']);
setLanguageLabel('GB','SYBDES','Selection Y or blank');
setLanguageList('GB','SYBVAL',['1']);
setLanguageList('GB','SYBDSC',['1']);
setLanguageLabel('GB','S1BDES','Selection 1 or blank');
setLanguageList('GB','S1BVAL',['1']);
setLanguageList('GB','S1BDSC',['1']);
setLanguageLabel('GB','TADDES','Tax advice type');
setLanguageList('GB','TADVAL',['1','2']);
setLanguageList('GB','TADDSC',['Daily during EOD or as requested','Yearly at end of tax year']);
setLanguageLabel('GB','TATDES','Direct debit mandate status');
setLanguageList('GB','TATVAL',['0','1','2','3','8','9']);
setLanguageList('GB','TATDSC',['Pending','Active','Held','Expired','Dormant','Cancelled']);
setLanguageLabel('GB','TAXDES','Tax type');
setLanguageList('GB','TAXVAL',['1','2']);
setLanguageList('GB','TAXDSC',['Single','Joint']);
setLanguageLabel('GB','TBADES','Before or after');
setLanguageList('GB','TBAVAL',['1','2']);
setLanguageList('GB','TBADSC',['Before','After']);
setLanguageLabel('GB','TIMDES','System time');
setLanguageLabel('GB','TLUDES','Tier level');
setLanguageList('GB','TLUVAL',['1','2','3']);
setLanguageList('GB','TLUDSC',['Level before withdrawal','Level after withdrawal','Maximum level']);
setLanguageLabel('GB','TMIDES','Tax method');
setLanguageList('GB','TMIVAL',['1','2','3']);
setLanguageList('GB','TMIDSC',['Tax, if threshold has been reached','Tax, regardless of tax threshold','Do not tax']);
setLanguageLabel('GB','TMPDES','Time period');
setLanguageList('GB','TMPVAL',['D','M','T','W','Y']);
setLanguageList('GB','TMPDSC',['Days between 1 and 999 days','Months between 1 and 99 months','Processing dates bet 0 and 99 days','Weeks between 1 and 99 weeks','Years between 1 and 99 years']);
setLanguageLabel('GB','TOPDES','Type of profit');
setLanguageList('GB','TOPVAL',['1','2','3','4']);
setLanguageList('GB','TOPDSC',['Charges','FX P&L','Debit interest','Credit interest']);
setLanguageLabel('GB','TRCDES','Transaction code');
setLanguageList('GB','TRCVAL',['000','002','003','004','014','024','083']);
setLanguageList('GB','TRCDSC',['Regular cheque','Special clearing receipts','Charge slips','Non machine readable cheque','Returned cheques with charge','Returned cheques without charge','ATM charge slips']);
setLanguageLabel('GB','TRTDES','Customer transfer type');
setLanguageList('GB','TRTVAL',['1','2','3','4']);
setLanguageList('GB','TRTDSC',['No transfer message required','MT100','MT103','MT103+']);
setLanguageLabel('GB','TTPDES','Transaction type');
setLanguageList('GB','TTPVAL',['I','P','R','S','X']);
setLanguageList('GB','TTPDSC',['Issue','Purchase','Repo','Sale','Reverse repo']);
setLanguageLabel('GB','TYPDES','Referral type');
setLanguageList('GB','TYPVAL',['1','2','3']);
setLanguageList('GB','TYPDSC',['Mandate errors','Account not found','Account errors']);
setLanguageLabel('GB','TY1DES','Request type');
setLanguageList('GB','TY1VAL',['P','R']);
setLanguageList('GB','TY1DSC',['Process','Report']);
setLanguageLabel('GB','UCDDES','Address use');
setLanguageList('GB','UCDVAL',['1','2','3','4','5','6','7','8','9']);
setLanguageList('GB','UCDDSC',['Title','First Name','Surname','Maiden / Previous Name','Street and House number','Postcode','Town','Country','House Name']);
setLanguageLabel('GB','VDVDES','Valid value selection');
setLanguageLabel('GB','VODDES','Value or description');
setLanguageList('GB','VODVAL',['D','V']);
setLanguageList('GB','VODDSC',['Description','Value']);
setLanguageLabel('GB','VPHDES','Valid phase');
setLanguageList('GB','VPHVAL',['ALL','C50','DAY']);
setLanguageList('GB','VPHDSC',['ALL','C50','DAY']);
setLanguageLabel('GB','WAIDES','Not applicable or waived');
setLanguageList('GB','WAIVAL',['0','1']);
setLanguageList('GB','WAIDSC',['Not applicable charge','Waived charge']);
setLanguageLabel('GB','W97DES','Driver processing - W97HMR');
setLanguageLabel('GB','YDBDES','Yield days basis');
setLanguageList('GB','YDBVAL',['A','0','1','2','3','4','5']);
setLanguageList('GB','YDBDSC',['Constant coupon amount','  /365','  /360','  /365-6','30/360','30/365','30/365-6']);
setLanguageLabel('GB','YNADES','Rollovers');
setLanguageList('GB','YNAVAL',['A','N','Y']);
setLanguageList('GB','YNADSC',['Automatically renewing','No rollovers','Rollover frequency is allowed']);
setLanguageLabel('GB','YNBDES','Yes or No or Both - SDYN/SDBOT');
setLanguageList('GB','YNBVAL',['B','N','Y']);
setLanguageList('GB','YNBDSC',['Both','No','Yes']);
setLanguageLabel('GB','YNHDES','Business day override');
setLanguageList('GB','YNHVAL',['H','N','Y']);
setLanguageList('GB','YNHDSC',['Eq. buss day but not at the branch','Default value','Working day for branch but not Eq.']);
setLanguageLabel('GB','YNNDES','Yes, No or Blank');
setLanguageList('GB','YNNVAL',['N','Y']);
setLanguageList('GB','YNNDSC',['No','Yes']);
setLanguageLabel('GB','YNODES','Yes/No abbreviations');
setLanguageLabel('GB','YOBDES','Yes or blank');
setLanguageList('GB','YOBVAL',['1']);
setLanguageList('GB','YOBDSC',['Yes']);
setLanguageLabel('GB','50FDES','50F Code');
setLanguageList('GB','50FVAL',['ARNU','CCPT','CUST','DRLC','EMPL','IBEI','NIDN','SOSE','TXID']);
setLanguageList('GB','50FDSC',['Alien registration number','Passport number','Customer number','Driving license number','Employee number','Intl business entity identifier','National identity number','Social security number','Tax identification number']);
setLanguageLabel('GB','57ADES','Field 57A option');
setLanguageList('GB','57AVAL',['1','2','3']);
setLanguageList('GB','57ADSC',['Unedited','Edited','Both']);
setLanguageLabel('GB','59ADES','Field 59A name lines');
setLanguageList('GB','59AVAL',['1','2','3','4']);
setLanguageList('GB','59ADSC',['One','Two','Three','Four']);
setLanguageLabel('GB','GBLACTMNT','Account Maintenance');
setLanguageLabel('GB','GBLCHGPAS','Change Password');
setLanguageLabel('GB','GBLRDTLGP','Redirecting to Login page');