package com.misys.equation.common.datastructure;

import com.misys.equation.common.access.EquationDataStructure;
import com.misys.equation.common.utilities.Toolbox;

public class EqDS_DSSYS2 extends EquationDataStructure
{

	//This attribute is used to store cvs version information.
	public static final String _revision = "$Id: EqDS_DSSYS2.java 12357 2011-11-25 21:43:28Z williae1 $";
	private static final long serialVersionUID = 1L;

	public final static String GBCCY = "$GBCCY";
	public final static String GBEDC = "$GBEDC";
	public final static String GBPWD = "$GBPWD";
	public final static String GLCCY = "$GLCCY";
	public final static String GLEDC = "$GLEDC";
	public final static String GLPWD = "$GLPWD";
	public final static String SDTX = "$SDTX";
	public final static String LRHC = "$LRHC";
	public final static String RRDA = "$RRDA";
	public final static String RLRP = "$RLRP";
	public final static String PIOI = "$PIOI";
	public final static String PIOP = "$PIOP";
	public final static String INRP = "$INRP";
	public final static String PNRP = "$PNRP";
	public final static String DCPS = "$DCPS";
	public final static String ADPS = "$ADPS";
	public final static String ASB = "$ASB";
	public final static String NAPI = "$NAPI";
	public final static String NOAI = "$NOAI";
	public final static String ACIN = "$ACIN";
	public final static String OVDR = "$OVDR";
	public final static String NACH = "$NACH";
	public final static String NHRC = "$NHRC";
	public final static String PINA = "$PINA";
	public final static String OBRN = "$OBRN";
	public final static String OEXN = "$OEXN";
	public final static String OFRQ = "$OFRQ";
	public final static String OWAP = "$OWAP";
	public final static String BMNM = "$BMNM";
	public final static String DOAFI = "$DOAFI";
	public final static String DOERT = "$DOERT";
	public final static String RSM = "$RSM";
	public final static String CDM = "$CDM";
	public final static String IBBSC = "$IBBSC";
	public final static String CIR = "$CIR";
	public final static String RCH = "$RCH";
	public final static String RCHD = "$RCHD";
	public final static String TCRRT = "$TCRRT";
	public final static String GRAI = "$GRAI";
	public final static String DDRP = "$DDRP";
	public final static String DODP = "$DODP";
	public final static String DDAP = "$DDAP";
	public final static String DDTG = "$DDTG";
	public final static String DGFB = "$DGFB";
	public final static String DDSC = "$DDSC";
	public final static String DRDG = "$DRDG";
	public final static String DMST = "$DMST";
	public final static String EORL = "$EORL";
	public final static String UNWRT = "$UNWRT";
	public final static String MXFRT = "$MXFRT";
	public final static String NWREF = "$NWREF";
	public final static String FWSRT = "$FWSRT";
	public final static String NWRT = "$NWRT";
	public final static String DFXP = "$DFXP";
	public final static String DFXR = "$DFXR";
	public final static String REVR = "$REVR";
	public final static String CONR = "$CONR";
	public final static String NSDTP = "$NSDTP";
	public final static String PNP = "$PNP";
	public final static String DOLP = "$DOLP";
	public final static String AGII = "$AGII";
	public final static String FXOVR = "$FXOVR";
	public final static String SRPM = "$SRPM";
	public final static String ASOR = "$ASOR";
	public final static String SOSN = "$SOSN";
	public final static String ACSN = "$ACSN";
	public final static String SOCO = "$SOCO";
	public final static String GRR = "$GRR";
	public final static String FJRF = "$FJRF";
	public final static String NOSJ = "$NOSJ";
	public final static String VNC = "$VNC";
	public final static String CPAR = "$CPAR";
	public final static String MCC = "$MCC";
	public final static String NSPR = "$NSPR";
	public final static String TAMB = "$TAMB";
	public final static String TAMO = "$TAMO";
	public final static String ACBB = "$ACBB";
	public final static String ACBO = "$ACBO";
	public final static String DCRB = "$DCRB";
	public final static String RRB = "$RRB";
	public final static String DCRO = "$DCRO";
	public final static String RRO = "$RRO";
	public final static String HEXH = "$HEXH";
	public final static String CEXU = "$CEXU";
	public final static String RETP = "$RETP";
	public final static String RBS = "$RBS";
	public final static String RTBS = "$RTBS";
	public final static String BSDC = "$BSDC";
	public final static String BSTO = "$BSTO";
	public final static String BSN = "$BSN";
	public final static String BSSP = "$BSSP";
	public final static String FXPPI = "$FXPPI";
	public final static String FXRNS = "$FXRNS";
	public final static String FXPED = "$FXPED";
	public final static String IST = "$IST";
	public final static String EQEX = "$EQEX";
	public final static String MQTAU = "$MQTAU";
	public final static String MQJAU = "$MQJAU";
	public final static String GPRCE = "$GPRCE";
	public final static String CODB = "$CODB";
	public final static String SWAC = "$SWAC";
	public final static String SPOT = "$SPOT";
	public final static String FXPL1 = "$FXPL1";
	public final static String SODAI = "$SODAI";
	public final static String PNPL = "$PNPL";
	public final static String HLDC = "$HLDC";
	public final static String RPER = "$RPER";
	public final static String DDLP = "$DDLP";
	public final static String DCCR = "$DCCR";
	public final static String DPCR = "$DPCR";
	public final static String DSCR = "$DSCR";
	public final static String WRFCR = "$WRFCR";
	public final static String DMCR = "$DMCR";
	public final static String CPRRT = "$CPRRT";
	public final static String FL50 = "$FL50";
	public final static String LHRC = "$LHRC";
	public final static String LDC = "$LDC";
	public final static String ORAC = "$ORAC";
	public final static String ORSAC = "$ORSAC";
	public final static String ENAI = "$ENAI";
	public final static String ROAMT = "$ROAMT";
	public final static String IBAN = "$IBAN";
	public final static String IBNV = "$IBNV";
	public final static String BDO = "$BDO";
	public final static String MPSO = "$MPSO";
	public final static String SOC = "$SOC";
	public final static String AGSOR = "$AGSOR";
	public final static String NDRSO = "$NDRSO";
	public final static String ASO = "$ASO";
	public final static String HSOCP = "$HSOCP";
	public final static String PSO = "$PSO";
	public final static String ORIFS = "$ORIFS";
	public final static String ORPCP = "$ORPCP";
	public final static String CLSB = "$CLSB";
	public final static String CLSM = "$CLSM";
	public final static String CLSA = "$CLSA";
	public final static String CLSC = "$CLSC";
	public final static String CLSR = "$CLSR";
	public final static String RCRET = "$RCRET";
	public final static String SSTRM = "$SSTRM";
	public final static String RUPST = "$RUPST";
	public final static String GENSW = "$GENSW";
	public final static String TDDS = "$TDDS";
	public final static String CRC = "$CRC";
	public final static String COA = "$COA";
	public final static String GNTRM = "$GNTRM";
	public final static String SDAWS = "$SDAWS";
	public final static String SCTA = "$SCTA";
	public final static String RCSM = "$RCSM";
	public final static String RTSM = "$RTSM";
	public final static String STTA = "$STTA";
	public final static String OPCF = "$OPCF";
	public final static String OPNF = "$OPNF";
	public final static String OPSAF = "$OPSAF";
	public final static String OPFXF = "$OPFXF";
	public final static String OPRRF = "$OPRRF";
	public final static String CPRA = "$CPRA";
	public final static String CPPP = "$CPPP";
	public final static String CPAP = "$CPAP";
	public final static String CPFD = "$CPFD";
	public final static String SNC = "$SNC";
	public final static String SDARR = "$SDARR";
	public final static String CSOT = "$CSOT";
	public final static String CSHM = "$CSHM";
	public final static String RQTD = "$RQTD";
	public final static String RQTE = "$RQTE";
	public final static String RQTS = "$RQTS";
	public final static String PTQR = "$PTQR";
	public final static String QCLC = "$QCLC";
	public final static String SMRL = "$SMRL";
	public final static String HQTB = "$HQTB";
	public final static String RCDE = "$RCDE";
	public final static String DCDE = "$DCDE";
	public final static String SFE = "$SFE";
	public final static String FEHC = "$FEHC";
	public final static String FEDC = "$FEDC";
	public final static String FEPU = "$FEPU";
	public final static String SFN50 = "$SFN50";
	public final static String CPRR = "$CPRR";
	public final static String IASBS = "$IASBS";
	public final static String IASSA = "$IASSA";
	public final static String IASDE = "$IASDE";
	public final static String GDIAS = "$GDIAS";
	public final static String MNRES = "$MNRES";
	public final static String MXEIR = "$MXEIR";
	public final static String TLEIR = "$TLEIR";
	public final static String OP50 = "$OP50";
	public final static String CIMD = "$CIMD";
	public final static String CPMD = "$CPMD";
	public final static String PAST = "$PAST";
	public final static String FEEAC = "$FEEAC";
	public final static String FORCH = "$FORCH";
	public final static String PSTPL = "$PSTPL";
	public final static String QACCS = "$QACCS";
	public final static String INACS = "$INACS";
	public final static String GRETP = "$GRETP";
	public final static String NCDL = "$NCDL";
	public final static String SADD = "$SADD";
	public final static String FSNME = "$FSNME";
	public final static String FSSBM = "$FSSBM";
	public final static String FNSER = "$FNSER";
	public final static String FSUBS = "$FSUBS";
	public final static String FJOBQ = "$FJOBQ";
	public final static String FJOBD = "$FJOBD";
	public final static String FMCON = "$FMCON";
	public final static String FFLIB = "$FFLIB";
	public final static String FWLIB = "$FWLIB";
	public final static String FLLIB = "$FLLIB";
	public final static String FLOGF = "$FLOGF";
	public final static String FCHKS = "$FCHKS";
	public final static String FMATC = "$FMATC";
	public final static String FDUP = "$FDUP";
	public final static String FACLP = "$FACLP";
	public final static String FWCAW = "$FWCAW";
	public final static String FWCPW = "$FWCPW";
	public final static String FWDLW = "$FWDLW";
	public final static String FALER = "$FALER";
	public final static String FMACS = "$FMACS";
	public final static String FMBPA = "$FMBPA";
	public final static String FMBPS = "$FMBPS";
	public final static String TPCRP = "$TPCRP";
	public final static String SMRP = "$SMRP";
	public final static String UCRP = "$UCRP";
	public final static String FPRP = "$FPRP";
	public final static String AMLA = "$AMLA";
	public final static String AMSID = "$AMSID";
	public final static String AMSTD = "$AMSTD";
	public final static String CAUSR = "$CAUSR";
	public final static String CAPWD = "$CAPWD";
	public final static String AACY = "$AACY";
	public final static String DIAC = "$DIAC";
	public final static String DCADR = "$DCADR";
	public final static String DCACR = "$DCACR";
	public final static String RDIRO = "$RDIRO";
	public final static String SPWT = "$SPWT";
	public final static String IASAR = "$IASAR";
	public final static String EIRA = "$EIRA";
	public final static String IASCA = "$IASCA";
	public final static String IASPL = "$IASPL";
	public final static String IASCH = "$IASCH";
	public final static String TDSP = "$TDSP";
	public final static String OPMM = "$OPMM";
	public final static String DPRU = "$DPRU";
	public final static String PLTXR = "$PLTXR";
	public final static String PLCDR = "$PLCDR";
	public final static String PLRPP = "$PLRPP";
	public final static String UCACP = "$UCACP";
	public final static String ERT2 = "$ERT2";
	public final static String CPDP = "$CPDP";
	public final static String PNPEI = "$PNPEI";
	public final static String NPPSI = "$NPPSI";
	public final static String SPIWN = "$SPIWN";
	public final static String NWRPD = "$NWRPD";
	public final static String NWRPM = "$NWRPM";
	public final static String TJAC = "$TJAC";
	public final static String IASMD = "$IASMD";
	public final static String IASPE = "$IASPE";
	public final static String BCGC = "$BCGC";
	public final static String BCRW = "$BCRW";
	public final static String BCRP = "$BCRP";
	public final static String IASFX = "$IASFX";
	public final static String PCAP = "$PCAP";
	public final static String PCHCL = "$PCHCL";
	public final static String PCHCS = "$PCHCS";
	public final static String PASD = "$PASD";
	public final static String CPLE = "$CPLE";
	public final static String EAL = "$EAL";
	public final static String IBIS = "$IBIS";
	public final static String BSPM = "$BSPM";
	public final static String BSCC = "$BSCC";
	public final static String VDBS = "$VDBS";
	public final static String FREV = "$FREV";
	public final static String CPCN = "$CPCN";
	public final static String CPBN = "$CPBN";
	public final static String CPPR = "$CPPR";
	public final static String CPBC = "$CPBC";
	public final static String BHOA = "$BHOA";
	public final static String CPPL = "$CPPL";
	public final static String BJPO1 = "$BJPO1";
	public final static String BJPO2 = "$BJPO2";
	public final static String BJVR1 = "$BJVR1";
	public final static String BJVR2 = "$BJVR2";
	public final static String RPPBK = "$RPPBK";
	public final static String CSLCV = "$CSLCV";
	public final static String CPAC = "$CPAC";
	public final static String CPPRS = "$CPPRS";
	public final static String DSIPO = "$DSIPO";
	public final static String CPMBE = "$CPMBE";
	public final static String IASND = "$IASND";
	public final static String MDSHRC = "$MDSHRC";
	public final static String MDSDC = "$MDSDC";
	public final static String MDNRP = "$MDNRP";
	public final static String MDARP = "$MDARP";
	public final static String MDCVP = "$MDCVP";
	public final static String MDBBC = "$MDBBC";
	public final static String DSPLC = "$DSPLC";
	public final static String TNUN = "$TNUN";
	public final static String NBDH = "$NBDH";
	public final static String ORACP = "$ORACP";
	public final static String FFE = "$FFE";
	public final static String IRAF = "$IRAF";
	public final static String SCPT = "$SCPT";
	public final static String OUTFMT = "$OUTFMT";
	public final static String OUTADP = "$OUTADP";
	public final static String OUTRLT = "$OUTRLT";
	public final static String RETOWF = "$RETOWF";
	public final static String RETIWF = "$RETIWF";
	public final static String OUTRTR = "$OUTRTR";
	public final static String LCUNCC = "$LCUNCC";
	public final static String LCRTCD = "$LCRTCD";
	public final static String LCODTR = "$LCODTR";
	public final static String LCOCTR = "$LCOCTR";
	public final static String OUTACT = "$OUTACT";
	public final static String APPDPD = "$APPDPD";
	public final static String DCLACT = "$DCLACT";
	public final static String DBCS = "$DBCS";
	public final static String KLPP = "$KLPP";
	public final static String KCPL = "$KCPL";
	public final static String KSTOT = "$KSTOT";
	public final static String PCSSC = "$PCSSC";
	public final static String AFII = "$AFII";
	public final static String HICP = "$HICP";
	public final static String PACSP = "$PACSP";
	public final static String OHBFE = "$OHBFE";
	public final static String GTYM = "$GTYM";
	public final static String GTYD = "$GTYD";
	public final static String TTHR = "$TTHR";
	public final static String TTUR = "$TTUR";
	public final static String AVRL = "$AVRL";
	public final static String MNTI = "$MNTI";
	public final static String MXTS = "$MXTS";
	public final static String MXTJ = "$MXTJ";
	public final static String ECCRV = "$ECCRV";
	public final static String DIXM = "$DIXM";
	public final static String DLCXM = "$DLCXM";
	public final static String SAPI = "$SAPI";
	public final static String EASI = "$EASI";
	public final static String S24CE = "$S24CE";
	public final static String S24CF = "$S24CF";
	public final static String DAFCN = "$DAFCN";
	public final static String DAFSN = "$DAFSN";
	public final static String DAFFN = "$DAFFN";
	public final static String DAFHN = "$DAFHN";
	public final static String DAFPL = "$DAFPL";
	public final static String DAFRD = "$DAFRD";
	public final static String DAFPC = "$DAFPC";
	public final static String CIFLF = "$CIFLF";
	public final static String REPA = "$REPA";
	public final static String EPRP = "$EPRP";
	public final static String UNBD = "$UNBD";
	public final static String PCGRP = "$PCGRP";
	public final static String PCCDE = "$PCCDE";
	public final static String FLACT = "$FLACT";
	public final static String KWVID = "$KWVID";
	public final static String SPRT = "$SPRT";
	public final static String FNRD = "$FNRD";
	public final static String PCTDC = "$PCTDC";
	public final static String DEC = "$DEC";
	public final static String OPROD = "$OPROD";
	public final static String KWVKN = "$KWVKN";
	public final static String KWVER = "$KWVER";
	public final static String KWLID = "$KWLID";
	public final static String KWFLT = "$KWFLT";
	public final static String KWFLR = "$KWFLR";
	public final static String KWMAX = "$KWMAX";
	public final static String KWRNR = "$KWRNR";
	public final static String KWDLR = "$KWDLR";
	public final static String KWTBT = "$KWTBT";
	public final static String KWTBR = "$KWTBR";
	public final static String FXNBM = "$FXNBM";
	public final static String TSOS = "$TSOS";
	public final static String RSTMN = "$RSTMN";
	public final static String ALPAS = "$ALPAS";
	public final static String AODA = "$AODA";
	public final static String CIFMA = "$CIFMA";
	public final static String S24RP = "$S24RP";
	public final static String BPOST = "$BPOST";
	public final static String BSTRT = "$BSTRT";
	public final static String BTOWN = "$BTOWN";
	public final static String STAX = "$STAX";
	public final static String PALA = "$PALA";
	public final static String MCBRPT = "$MCBRPT";
	public final static String ASCT = "$ASCT";
	public final static String ASCRP = "$ASCRP";
	public final static String UIF25 = "$UIF25";
	public final static String OPSCD = "$OPSCD";
	public final static String OPSCS = "$OPSCS";
	public final static String OPSSA = "$OPSSA";
	public final static String OPSND = "$OPSND";
	public final static String OPSFX = "$OPSFX";
	public final static String OPSCFD = "$OPSCFD";
	public final static String OPSCP = "$OPSCP";
	public final static String OPSNP = "$OPSNP";
	public final static String OPSSAF = "$OPSSAF";
	public final static String OPSFXF = "$OPSFXF";
	public final static String OPSRRF = "$OPSRRF";
	public final static String OPSMAB = "$OPSMAB";
	public final static String OPICP = "$OPICP";
	public final static String EODM = "$EODM";
	public final static String TELZ = "$TELZ";
	public final static String STDAY = "$STDAY";
	public final static String STMON = "$STMON";
	public final static String CPEA = "$CPEA";
	public final static String CPDT = "$CPDT";
	public final static String CPCT = "$CPCT";
	public final static String CPDF = "$CPDF";
	public final static String NPEA = "$NPEA";
	public final static String NPDT = "$NPDT";
	public final static String NPCT = "$NPCT";
	public final static String NPDF = "$NPDF";
	public final static String PNFC = "$PNFC";
	public final static String VDC = "$VDC";
	public final static String VRH = "$VRH";
	public final static String VPAC = "$VPAC";
	public final static String VFAC = "$VFAC";
	public final static String VSAC = "$VSAC";
	public final static String VCAC = "$VCAC";
	public final static String EDRC = "$EDRC";
	public final static String IASAP = "$IASAP";
	public final static String MDPAC = "$MDPAC";
	public final static String MDPC = "$MDPC";
	public final static String DCCS = "$DCCS";
	public final static String DSLC1 = "$DSLC1";
	public final static String DSLC2 = "$DSLC2";
	public final static String DSLC3 = "$DSLC3";
	public final static String DSLC4 = "$DSLC4";
	public final static String DSLC5 = "$DSLC5";
	public final static String DXML1 = "$DXML1";
	public final static String DXML2 = "$DXML2";
	public final static String DXML3 = "$DXML3";
	public final static String DXML4 = "$DXML4";
	public final static String DXML5 = "$DXML5";
	public final static String PIM = "$PIM";
	public final static String CLSOD = "$CLSOD";
	public final static String IRRP = "$IRRP";
	public final static String RTAD = "$RTAD";
	public final static String ACRQ = "$ACRQ";
	public final static String RTBC = "$RTBC";
	public final static String ERASD = "$ERASD";
	public final static String CPSBF = "$CPSBF";
	public final static String WBLNS = "$WBLNS";
	public final static String DSRCL = "$DSRCL";
	public final static String DSRCF = "$DSRCF";
	public final static String DTRCL = "$DTRCL";
	public final static String DTSRC = "$DTSRC";
	public final static String WFAPS = "$WFAPS";
	public final static String WFAPI = "$WFAPI";
	public final static String EQSSV = "$EQSSV";
	public final static String EQSID = "$EQSID";
	public final static String WFAPP = "$WFAPP";
	public final static String EQSAP = "$EQSAP";
	public final static String EQSUI = "$EQSUI";
	public final static String OPP50 = "$OPP50";
	public final static String IP50 = "$IP50";
	public final static String IPP50 = "$IPP50";
	public final static String KWTFN = "$KWTFN";
	public final static String FXNSM = "$FXNSM";
	public final static String SPZCI = "$SPZCI";
	public final static String PSPBL = "$PSPBL";
	public final static String VDAR = "$VDAR";
	public final static String SPOCH = "$SPOCH";
	public final static String MSNDB = "$MSNDB";
	public final static String FWCDW = "$FWCDW";
	public final static String CSREF = "$CSREF";
	public final static String CPUS = "$CPUS";
	public final static String SIDD = "$SIDD";
	public final static String GSWME = "$GSWME";
	public final static String _50F1 = "$50F1";
	public final static String _50F2 = "$50F2";
	public final static String FERHC = "$FERHC";
	public final static String FERDC = "$FERDC";
	public final static String DRRP = "$DRRP";
	public final static String BOHC = "$BOHC";
	public final static String BODC = "$BODC";
	public final static String BONHC = "$BONHC";
	public final static String BONDC = "$BONDC";
	public final static String WFHFW = "$WFHFW";
	public final static String CPERR = "$CPERR";
	public final static String FCLST = "$FCLST";
	public final static String ABAD = "$ABAD";
	public final static String RSOIF = "$RSOIF";
	public final static String CPSP = "$CPSP";
	public final static String IPPF = "$IPPF";
	public final static String FFFEC = "$FFFEC";
	public final static String FFFEG = "$FFFEG";
	public final static String FFFEL = "$FFFEL";
	public final static String FFFIP = "$FFFIP";
	public final static String FFFDI = "$FFFDI";
	public final static String FFFUS = "$FFFUS";
	public final static String FFFPW = "$FFFPW";
	public final static String FFFFS = "$FFFFS";
	public final static String FMFTR = "$FMFTR";
	public final static String NPWDA = "$NPWDA";
	public final static String DPWDU = "$DPWDU";
	public final static String RCUII = "$RCUII";
	public final static String DDBCS = "$DDBCS";
	public final static String TRLIB = "$TRLIB";
	public final static String TRTBL = "$TRTBL";
	public final static String FFFTR = "$FFFTR";
	public final static String DF71A = "$DF71A";
	public final static String TCHR = "$TCHR";
	public final static String RLSEL = "$RLSEL";
	public final static String NBDGD = "$NBDGD";
	public final static String NBDST = "$NBDST";
	public final static String URTM = "$URTM";
	public final static String BSNG = "$BSNG";
	public final static String SFAD = "$SFAD";
	public final static String D13DC = "$D13DC";
	public final static String ESUMI = "$ESUMI";
	public final static String SSUMC = "$SSUMC";
	public final static String SSUMD = "$SSUMD";
	public final static String SSUMA = "$SSUMA";
	public final static String RNFXP = "$RNFXP";
	public final static String FXCD = "$FXCD";
	public final static String UIIR = "$UIIR";
	public final static String FBBC = "$FBBC";
	public final static String BPL = "$BPL";
	public final static String RCCID = "$RCCID";
	public final static String FWERR = "$FWERR";
	public final static String PCRTN = "$PCRTN";
	public final static String ESABO = "$ESABO";
	public final static String CCOY = "$CCOY";
	public final static String FNAL1 = "$FNAL1";
	public final static String FNAL2 = "$FNAL2";
	public final static String FNAL3 = "$FNAL3";
	public final static String RLCF = "$RLCF";
	public final static String CBVT = "$CBVT";
	public final static String FTRYT = "$FTRYT";
	public final static String PFDC = "$PFDC";
	public final static String IPDF = "$IPDF";
	public final static String IPKJ = "$IPKJ";
	public final static String IPRT = "$IPRT";
	public final static String IPDR = "$IPDR";
	public final static String INBD = "$INBD";
	public final static String IPDO = "$IPDO";
	public final static String IPDA = "$IPDA";
	public final static String IPRR = "$IPRR";
	public final static String IPJD = "$IPJD";
	public final static String CFPRI = "$CFPRI";
	public final static String CIACV = "$CIACV";
	public final static String VDIFT = "$VDIFT";
	public final static String SACID = "$SACID";
	public final static String CVDS = "$CVDS";
	public final static String AIKE = "$AIKE";
	public final static String CACCI = "$CACCI";
	public final static String PDT = "$PDT";
	public final static String AMSI = "$AMSI";

	public final static String DUM1 = "$DUM1";
	public final static String DUM2 = "$DUM2";
	public final static String DUM3 = "$DUM3";
	public final static String DUM4 = "$DUM4";
	public final static String DUM5 = "$DUM5";

	/**
	 * Constructor to create the DSSYS2 data structure
	 */
	public EqDS_DSSYS2()
	{
		super("DSSYS2", Toolbox.DEF_CCSID);

		createCharacterField(GBCCY, "Group Base currency (character)", 1 - 1, 3);
		createZonedFieldAsChar(GBEDC, "Group Base currency edit code / decimal places", 4 - 1, 1, 0);
		createZonedFieldAsChar(GBPWD, "Group Base currency edit code to power 10", 5 - 1, 4, 0);
		createCharacterField(GLCCY, "Group Local currency (character)", 9 - 1, 3);
		createZonedFieldAsChar(GLEDC, "Group Local currency edit code / decimal places", 12 - 1, 1, 0);
		createZonedFieldAsChar(GLPWD, "Group Local currency edit code to power 10", 13 - 1, 4, 0);
		createCharacterField(SDTX, "Settlement Deal Type (Foreign Exchange)", 17 - 1, 3);
		createCharacterField(LRHC, "Loan repayment reason code", 20 - 1, 3);
		createCharacterField(RRDA, "Repayment reminders days in advance", 23 - 1, 2);
		createCharacterField(RLRP, "Method of retail repayment priority", 25 - 1, 1);
		createCharacterField(PIOI, "Penalty interest-overdue interest", 26 - 1, 2);
		createCharacterField(PIOP, "Penalty interest-overdue principal", 28 - 1, 2);
		createCharacterField(INRP, "Interest repayments", 30 - 1, 2);
		createCharacterField(PNRP, "Principal repayments", 32 - 1, 2);
		createCharacterField(DCPS, "Default Customer Profit Structure", 34 - 1, 5);
		createCharacterField(ADPS, "Apply Default Profit Structure", 39 - 1, 1);
		createCharacterField(ASB, "Automatic system balancing (Y/N)", 40 - 1, 1);
		createCharacterField(NAPI, "Non-accrual penalty interest", 41 - 1, 2);
		createCharacterField(NOAI, "Non-accrual ineterest", 43 - 1, 2);
		createCharacterField(ACIN, "Accrued interest", 45 - 1, 2);
		createCharacterField(OVDR, "Overdraft", 47 - 1, 2);
		createCharacterField(NACH, "Create holds for non-accrual accounts?", 49 - 1, 1);
		createCharacterField(NHRC, "Non-accrual hold reason code", 50 - 1, 3);
		createCharacterField(PINA, "Post accrued int. if in accrual?", 53 - 1, 1);
		createCharacterField(OBRN, "Equation branch number in OPICS", 54 - 1, 2);
		createCharacterField(OEXN, "Use external a/c no.s for OPICS", 56 - 1, 1);
		createCharacterField(OFRQ, "Currency trading & Nostro pos. transfer frq.", 57 - 1, 3);
		createCharacterField(OWAP, "Wait period for OPICS end of day", 60 - 1, 3);
		createCharacterField(BMNM, "Branch mnemonic of the OPICS branch", 63 - 1, 4);
		createCharacterField(DOAFI, "Discretionary Overdrafts Against Forward Item", 67 - 1, 1);
		createCharacterField(DOERT, "Discretionary Overdraft Retention Period", 68 - 1, 2);
		createCharacterField(RSM, "Calculated business day in the same month", 70 - 1, 1);
		createCharacterField(CDM, "Clearing date mode", 71 - 1, 1);
		createCharacterField(IBBSC, "Issuing bank/branch sort code", 72 - 1, 1);
		createZonedFieldAsChar(CIR, "Collateral item retention", 73 - 1, 2, 0);
		createCharacterField(RCH, "Reason for collateral hold", 75 - 1, 3);
		createCharacterField(RCHD, "Reason for collateral hold description", 78 - 1, 30);
		createCharacterField(TCRRT, "Tax conversion retail rate type", 108 - 1, 3);
		createCharacterField(GRAI, "German Retail Account Interest Calculation", 111 - 1, 1);
		createCharacterField(DDRP, "Direct Debit Retention Period", 112 - 1, 4);
		createCharacterField(DODP, "Dormant Direct Debit Period", 116 - 1, 4);
		createCharacterField(DDAP, "Direct Debit Activation Period", 120 - 1, 4);
		createCharacterField(DDTG, "Direct Debit Days of Grace", 124 - 1, 4);
		createCharacterField(DGFB, "DD Days of Grace fwd/bkwd", 128 - 1, 1);
		createCharacterField(DDSC, "Suppress DD Mandate Confirmation", 129 - 1, 1);
		createCharacterField(DRDG, "Direct Debit Returns Days of Grace", 130 - 1, 4);
		createCharacterField(DMST, "Default Mandate Status", 134 - 1, 1);
		createCharacterField(EORL, "Electronic Originators Reference Length", 135 - 1, 2);
		createZonedFieldAsChar(UNWRT, "Unmatured notice withdrawal retention days", 137 - 1, 2, 0);
		createZonedFieldAsChar(MXFRT, "Maximum days for notice withdrawal rates", 139 - 1, 3, 0);
		createCharacterField(NWREF, "Automatic notice withdrawal references", 142 - 1, 1);
		createZonedFieldAsChar(FWSRT, "Free withdrawal statistics retention", 143 - 1, 2, 0);
		createZonedFieldAsChar(NWRT, "Notice withdrawal retention", 145 - 1, 2, 0);
		createZonedFieldAsChar(DFXP, "Days in advance for notice wdl projections", 147 - 1, 3, 0);
		createZonedFieldAsChar(DFXR, "Days in advance to fix notice wdl FX rates", 150 - 1, 3, 0);
		createCharacterField(REVR, "Review required", 153 - 1, 1);
		createCharacterField(CONR, "Confirmation required", 154 - 1, 1);
		createCharacterField(NSDTP, "Notice savings account deal reference", 155 - 1, 3);
		createCharacterField(PNP, "Pending period", 158 - 1, 2);
		createCharacterField(DOLP, "Direct debit lead origination period", 160 - 1, 2);
		createCharacterField(AGII, "Auto-generate instruction identifier", 162 - 1, 1);
		createCharacterField(FXOVR, "Allow override of internal FX rates?", 163 - 1, 1);
		createCharacterField(SRPM, "Spread rate processing mode", 164 - 1, 1);
		createCharacterField(ASOR, "Automatic Generation of Stop Order Reference", 165 - 1, 1);
		createCharacterField(SOSN, "Stop Order by Cheque Serial no./serialno & amt", 166 - 1, 1);
		createCharacterField(ACSN, "Alpha Numeric Serial Numbers allowed", 167 - 1, 1);
		createCharacterField(SOCO, "Stop Order Confirmations", 168 - 1, 1);
		createCharacterField(GRR, "Group reporting currency", 169 - 1, 3);
		createCharacterField(FJRF, "Fast journal recovery flag", 172 - 1, 1);
		createZonedFieldAsChar(NOSJ, "No. of journal stream jobs allowed", 173 - 1, 3, 0);
		createCharacterField(VNC, "Validate new claims", 176 - 1, 1);
		createZonedFieldAsChar(CPAR, "Par exchange warning range", 177 - 1, 2, 0);
		createCharacterField(MCC, "Maturities considered in commitment", 179 - 1, 1);
		createCharacterField(NSPR, "Enable Next Business Day Spot Rates", 180 - 1, 1);
		createCharacterField(TAMB, "Transaction Amounts in Base Currency", 181 - 1, 1);
		createCharacterField(TAMO, "Transaction Amounts in User Currency", 182 - 1, 3);
		createCharacterField(ACBB, "Account Balances in Base Currency", 185 - 1, 1);
		createCharacterField(ACBO, "Account Balances in User Currency", 186 - 1, 3);
		createCharacterField(DCRB, "Default Base currency rate type", 189 - 1, 1);
		createCharacterField(RRB, "Base currency Retail Rate", 190 - 1, 3);
		createCharacterField(DCRO, "Default User currency rate type", 193 - 1, 1);
		createCharacterField(RRO, "User currency Retail Rate", 194 - 1, 3);
		createCharacterField(HEXH, "Hold historical exchange rates", 197 - 1, 1);
		createCharacterField(CEXU, "Use current exchange rate", 198 - 1, 1);
		createCharacterField(RETP, "Historical exchange rates retention period", 199 - 1, 2);
		createCharacterField(RBS, "Regional branch settlement?", 201 - 1, 1);
		createCharacterField(RTBS, "Real time branch settlement?", 202 - 1, 1);
		createCharacterField(BSDC, "Branch settlement - separate DR/CR?", 203 - 1, 1);
		createCharacterField(BSTO, "Regional branch settlement turnover?", 204 - 1, 1);
		createCharacterField(BSN, "Narrative on branch settlements?", 205 - 1, 1);
		createCharacterField(BSSP, "Suppress inter-region/CLO postings?", 206 - 1, 1);
		createCharacterField(FXPPI, "Post FX Deal P&L at SOD and input      ", 207 - 1, 1);
		createCharacterField(FXRNS, "Revalue NBD FX mats using NBD spot     ", 208 - 1, 1);
		createCharacterField(FXPED, "Mature split value deal on earlier date", 209 - 1, 1);
		createZonedFieldAsChar(IST, "Interest schedule tolerance", 210 - 1, 3, 0);
		createCharacterField(EQEX, "Print int a/c no. in external format", 213 - 1, 1);
		createCharacterField(MQTAU, "MQ processor transmission audit", 214 - 1, 6);
		createCharacterField(MQJAU, "MQ processor journal audit", 220 - 1, 6);
		createCharacterField(GPRCE, "Guarantor Risk Country Exposure", 226 - 1, 1);
		createCharacterField(CODB, "Collateral on Debit Balance", 227 - 1, 1);
		createZonedFieldAsChar(SWAC, "Swift address comparison", 228 - 1, 2, 0);
		createCharacterField(SPOT, "Allow date beyond spot", 230 - 1, 1);
		createCharacterField(FXPL1, "Single base ccy posting for FX P&L", 231 - 1, 1);
		createCharacterField(SODAI, "Accrue interest at start of day?", 232 - 1, 1);
		createCharacterField(PNPL, "Record Non-Deal FX", 233 - 1, 1);
		createCharacterField(HLDC, "Hold Code", 234 - 1, 3);
		createZonedFieldAsChar(RPER, "Commercial Papers Retention Period", 237 - 1, 2, 0);
		createZonedFieldAsChar(DDLP, "Com. Papers Default Debtor Spread Control", 239 - 1, 5, 2);
		createCharacterField(DCCR, "Com. Papers Default Commision Charge Rule", 244 - 1, 8);
		createCharacterField(DPCR, "Com. Papers Default Postage Fees Charge Rule", 252 - 1, 8);
		createCharacterField(DSCR, "Com. Papers Default Stamp Fees Charge Rule", 260 - 1, 8);
		createCharacterField(WRFCR, "Com. Papers Withdrawal/Return Fees Charge Rule", 268 - 1, 8);
		createCharacterField(DMCR, "Com. Papers Default Maturity Fees Charge Rule", 276 - 1, 8);
		createCharacterField(CPRRT, "Commercial. Papers Retail Rate", 284 - 1, 3);
		createCharacterField(FL50, "Use SWIFT address on field 50?", 287 - 1, 1);
		createCharacterField(LHRC, "Loan repayments hold reason code", 288 - 1, 3);
		createCharacterField(LDC, "Loan department code", 291 - 1, 3);
		createCharacterField(ORAC, "ORF Arabic conversion required (Y/N)", 294 - 1, 1);
		createCharacterField(ORSAC, "ORF Arabic conversion to be run in background", 295 - 1, 1);
		createCharacterField(ENAI, "Enable non-Misys ATM interface", 296 - 1, 1);
		createCharacterField(ROAMT, "Repay RL overdue amt first at EOD", 297 - 1, 1);
		createCharacterField(IBAN, "International bank account number (generation)", 298 - 1, 1);
		createCharacterField(IBNV, "International bank account number (validation)", 299 - 1, 1);
		createZonedFieldAsChar(BDO, "Business days off-set for sending postdated ch", 300 - 1, 2, 0);
		createCharacterField(MPSO, "Manual processing of standing orders default", 302 - 1, 1);
		createCharacterField(SOC, "Standing orders confirmations default", 303 - 1, 1);
		createCharacterField(AGSOR, "Automatic generation of standing orders reference", 304 - 1, 1);
		createCharacterField(NDRSO, "No. of days to retry standing order              ", 305 - 1, 4);
		createCharacterField(ASO, "Authorisation for standing orders                ", 309 - 1, 1);
		createCharacterField(HSOCP, "Hold standing order clean payments               ", 310 - 1, 1);
		createCharacterField(PSO, "Process standing orders                          ", 311 - 1, 3);
		createCharacterField(ORIFS, "Use IFS with ORF", 314 - 1, 1);
		createCharacterField(ORPCP, "ORF PC Code page", 315 - 1, 5);
		createCharacterField(CLSB, "CLS Bank BIC                      ", 320 - 1, 11);
		createCharacterField(CLSM, "CLS deal maintenance              ", 331 - 1, 1);
		createZonedFieldAsChar(CLSA, "Min days in adv for CLS deal entry", 332 - 1, 2, 0);
		createZonedFieldAsChar(CLSC, "CLS cut-off time                  ", 334 - 1, 4, 0);
		createZonedFieldAsChar(CLSR, "CLS rescind time                  ", 338 - 1, 4, 0);
		createZonedFieldAsChar(RCRET, "", 342 - 1, 2, 0);
		createZonedFieldAsChar(SSTRM, "Number of stream       ", 344 - 1, 2, 0);
		createZonedFieldAsChar(RUPST, "Number of urgent stream", 346 - 1, 2, 0);
		createCharacterField(GENSW, "Generate field 56 on MT300", 348 - 1, 1);
		createCharacterField(TDDS, "Default settlement a/c's to funding a/c", 349 - 1, 1);
		createCharacterField(CRC, "Chequebook request confirmation", 350 - 1, 1);
		createCharacterField(COA, "Chequebokk request advice      ", 351 - 1, 1);
		createCharacterField(GNTRM, "Generate message if TRAM installed", 352 - 1, 1);
		createCharacterField(SDAWS, "Subtract discount accrued when sold", 353 - 1, 1);
		createCharacterField(SCTA, "Stock cash transit accounting      ", 354 - 1, 1);
		createCharacterField(RCSM, "Record cash stock movements        ", 355 - 1, 1);
		createCharacterField(RTSM, "Record t/c stock movements         ", 356 - 1, 1);
		createCharacterField(STTA, "Stock t/c transit accounting       ", 357 - 1, 1);
		createCharacterField(OPCF, "Currency trading pos. transfer frq.", 358 - 1, 3);
		createCharacterField(OPNF, "Nostro pos. transfer frq.", 361 - 1, 3);
		createCharacterField(OPSAF, "Payment download request frq.", 364 - 1, 3);
		createCharacterField(OPFXF, "FX Rate download request frq.", 367 - 1, 3);
		createCharacterField(OPRRF, "Retail Rate download request frq.", 370 - 1, 3);
		createCharacterField(CPRA, "Retry CP advice retention period", 373 - 1, 4);
		createCharacterField(CPPP, "Retention period for clean payments posting information", 377 - 1, 4);
		createCharacterField(CPAP, "Retention period for clean payment audit information", 381 - 1, 4);
		createCharacterField(CPFD, "Retention period for clean payment with failed information", 385 - 1, 4);
		createCharacterField(SNC, "Suppress narrative on charges", 389 - 1, 1);
		createCharacterField(SDARR, "Subtract Disc Accr for R999001 Rep", 390 - 1, 1);
		createCharacterField(CSOT, "Cashier V9 TCP/IP online trace    ", 391 - 1, 1);
		createCharacterField(CSHM, "Cashier V9 TCP/IP HM trace        ", 392 - 1, 1);
		createCharacterField(RQTD, "Retry queued transactions during day", 393 - 1, 3);
		createCharacterField(RQTE, "Retry queued transactions at EOD", 396 - 1, 1);
		createCharacterField(RQTS, "Retry queued transactions at SOD", 397 - 1, 1);
		createCharacterField(PTQR, "Print transaction queue retry process", 398 - 1, 1);
		createCharacterField(QCLC, "Queue capitalised loan charges", 399 - 1, 1);
		createCharacterField(SMRL, "Suppress multi-streaming of RL repay", 400 - 1, 1);
		createCharacterField(HQTB, "Hide queued transaction in other branch", 401 - 1, 1);
		createCharacterField(RCDE, "Queued transaction hold code", 402 - 1, 3);
		createCharacterField(DCDE, "Queued transaction department code", 405 - 1, 3);
		createCharacterField(SFE, "Supoort for four eyes", 408 - 1, 1);
		createCharacterField(FEHC, "Four eyes hold code", 409 - 1, 3);
		createCharacterField(FEDC, "Four eyes department code", 412 - 1, 3);
		createCharacterField(FEPU, "Four eyes pop-up display correction", 415 - 1, 1);
		createCharacterField(SFN50, "Show full name on field 50", 416 - 1, 1);
		createZonedFieldAsChar(CPRR, "CP SWIFT msgs and reports retry frq", 417 - 1, 2, 0);
		createCharacterField(IASBS, "IAS 39 Balance Sheet                   ", 419 - 1, 1);
		createCharacterField(IASSA, "IAS 39 Straight Line Accrual           ", 420 - 1, 1);
		createCharacterField(IASDE, "IAS 39 Dummy Spot Exchange             ", 421 - 1, 1);
		createCharacterField(GDIAS, "Generic Deal IAS 39 Accounting         ", 422 - 1, 1);
		createZonedFieldAsChar(MNRES, "Min Residual Term for Net Present Value", 423 - 1, 2, 0);
		createZonedFieldAsChar(MXEIR, "Max Iteration for EIR Calculation      ", 425 - 1, 4, 0);
		createZonedFieldAsChar(TLEIR, "Tolerance for EIR Calculation          ", 429 - 1, 6, 0);
		createCharacterField(OP50, "Protect Ordering Customer field", 435 - 1, 1);
		createCharacterField(CIMD, "Capitalise interest on mat date", 436 - 1, 1);
		createCharacterField(CPMD, "Capitalise penalty on mat date ", 437 - 1, 1);
		createCharacterField(PAST, "Print annual statement if no transaction", 438 - 1, 1);
		createCharacterField(FEEAC, "Fees receivable accounting", 439 - 1, 1);
		createCharacterField(FORCH, "Force display of charges", 440 - 1, 1);
		createCharacterField(PSTPL, "Post to P&L when chrg on fees rcv", 441 - 1, 1);
		createCharacterField(QACCS, "Queue account service charges", 442 - 1, 1);
		createCharacterField(INACS, "Individual a/c service chrg postings", 443 - 1, 1);
		createZonedFieldAsChar(GRETP, "Generic transalation file ret period", 444 - 1, 2, 0);
		createCharacterField(NCDL, "Next consultancy date calculation", 446 - 1, 2);
		createCharacterField(SADD, "Use structured address fields?", 448 - 1, 1);
		createCharacterField(FSNME, "OFAC-agent Server Host Name", 449 - 1, 20);
		createCharacterField(FSSBM, "OFAC-agent Server Service Basic Name", 469 - 1, 20);
		createZonedFieldAsChar(FNSER, "Number of OFAC-agent servers", 489 - 1, 2, 0);
		createCharacterField(FSUBS, "Subsystem for OFAC-agent servers", 491 - 1, 10);
		createCharacterField(FJOBQ, "Job queue for OFAC-agent servers", 501 - 1, 10);
		createCharacterField(FJOBD, "Job description for OFAC-agent servers", 511 - 1, 10);
		createZonedFieldAsChar(FMCON, "Max Simultaneous Connections Permitted", 521 - 1, 2, 0);
		createCharacterField(FFLIB, "Library containing OFAC-agent programs", 523 - 1, 10);
		createCharacterField(FWLIB, "Library containing OFAC-agent database", 533 - 1, 10);
		createCharacterField(FLLIB, "Library containing Log File", 543 - 1, 10);
		createCharacterField(FLOGF, "Name of Log File", 553 - 1, 5);
		createCharacterField(FCHKS, "Checking Severity", 558 - 1, 20);
		createCharacterField(FMATC, "Matching method", 578 - 1, 20);
		createCharacterField(FDUP, "uplicates", 598 - 1, 1);
		createCharacterField(FACLP, "Create Clean Payments If No Check", 599 - 1, 1);
		createCharacterField(FWCAW, "Customer Address WLC", 600 - 1, 1);
		createCharacterField(FWCPW, "Clean Payment WLC", 601 - 1, 1);
		createCharacterField(FWDLW, "Deal WLC", 602 - 1, 1);
		createCharacterField(FALER, "Alert User of Watch List Matches", 603 - 1, 1);
		createCharacterField(FMACS, "Block new account customer status", 604 - 1, 2);
		createCharacterField(FMBPA, "Block payment authorisation status", 606 - 1, 2);
		createCharacterField(FMBPS, "Block payment maintenance status  ", 608 - 1, 2);
		createZonedFieldAsChar(TPCRP, "True Positive Case Retention      ", 610 - 1, 2, 0);
		createZonedFieldAsChar(SMRP, "Suspected Match Retention Period", 612 - 1, 2, 0);
		createZonedFieldAsChar(UCRP, "Unchecked Cases Retention Period", 614 - 1, 2, 0);
		createZonedFieldAsChar(FPRP, "False Positive Case Retention Period", 616 - 1, 2, 0);
		createCharacterField(AMLA, "AML interface active                    ", 618 - 1, 1);
		createCharacterField(AMSID, "AML server id                          ", 619 - 1, 20);
		createCharacterField(AMSTD, "AML server target directory            ", 639 - 1, 20);
		createCharacterField(CAUSR, "Compliance Alert user                  ", 659 - 1, 20);
		createCharacterField(CAPWD, "Compliance Alert password              ", 679 - 1, 20);
		createCharacterField(AACY, "AML analysis currency                   ", 699 - 1, 3);
		createCharacterField(DIAC, "Download internal accounts?             ", 702 - 1, 1);
		createCharacterField(DCADR, "Default Compliance Alert DR transaction", 703 - 1, 20);
		createCharacterField(DCACR, "Default Compliance Alert CR transaction", 723 - 1, 20);
		createCharacterField(RDIRO, "Separate posting for withholding tax", 743 - 1, 1);
		createCharacterField(SPWT, "Amortised cost calculation report         ", 744 - 1, 1);
		createCharacterField(IASAR, "Effective interest rate audit             ", 745 - 1, 4);
		createCharacterField(EIRA, "IAS Charges amortised to date report audit", 749 - 1, 1);
		createCharacterField(IASCA, "IAS Charges P&L contra breakout           ", 750 - 1, 1);
		createCharacterField(IASPL, "Use Interest categories for charges       ", 751 - 1, 1);
		createCharacterField(IASCH, "Suspense postings required", 752 - 1, 1);
		createCharacterField(TDSP, "MM Deals to go to OPICS as deals?", 753 - 1, 1);
		createCharacterField(OPMM, "MM Deals to go to OPICS as deals?", 754 - 1, 1);
		createCharacterField(DPRU, "Default posting ref to user id", 755 - 1, 1);
		createZonedFieldAsChar(PLTXR, "PL Tax Retention", 756 - 1, 2, 0);
		createZonedFieldAsChar(PLCDR, "Charge Details Retention", 758 - 1, 2, 0);
		createZonedFieldAsChar(PLRPP, "PL Reporting Retention", 760 - 1, 2, 0);
		createCharacterField(UCACP, "Use Customer Address on Clean Payments", 762 - 1, 1);
		createCharacterField(ERT2, "Exchange rate tolerance 2 for Cashier system", 763 - 1, 3);
		createCharacterField(CPDP, "Enable Auto CP Document Production", 766 - 1, 1);
		createCharacterField(PNPEI, "Post notice penalty if exceeds interest amount", 767 - 1, 1);
		createCharacterField(NPPSI, "Notice penalty posted separately from interest", 768 - 1, 1);
		createCharacterField(SPIWN, "Show penalty in withdrawal narrative", 769 - 1, 1);
		createZonedFieldAsChar(NWRPD, "Unmatured notice withdrawal retention (days)", 770 - 1, 3, 0);
		createZonedFieldAsChar(NWRPM, "Unmatured notice withdrawal retention (months)", 773 - 1, 2, 0);
		createCharacterField(TJAC, "Enable Trader joint accounts", 775 - 1, 1);
		createCharacterField(IASMD, "Use Maturity Date for CL Calculation", 776 - 1, 1);
		createCharacterField(IASPE, "IAS Post Earned Amortisation", 777 - 1, 1);
		createCharacterField(BCGC, "Generate Card Numbers          ", 778 - 1, 1);
		createCharacterField(BCRW, "Card Renewal                   ", 779 - 1, 4);
		createZonedFieldAsChar(BCRP, "Card Retention Period ", 783 - 1, 2, 0);
		createCharacterField(DUM1, "DUM1", 785 - 1, 40);
		createCharacterField(IASFX, "IAS Post Earned Amortisation             ", 825 - 1, 1);
		createCharacterField(PCAP, "Print Customer Address on Passbook ", 826 - 1, 1);
		createZonedFieldAsChar(PCHCL, "PCHC a/c number length                   ", 827 - 1, 2, 0);
		createCharacterField(PCHCS, "PCHC a/c number system                   ", 829 - 1, 1);
		createCharacterField(PASD, "Post account service charges on same day?", 830 - 1, 1);
		createCharacterField(CPLE, "Consolidate P&L at EOD?                  ", 831 - 1, 1);
		createCharacterField(EAL, "Enable Account Locking", 832 - 1, 1);
		createCharacterField(IBIS, "Include bonus in interest statistics           ", 833 - 1, 1);
		createCharacterField(BSPM, "Bonus statistics processing mode               ", 834 - 1, 1);
		createCharacterField(BSCC, "Bonus statistics charge code                   ", 835 - 1, 2);
		createCharacterField(VDBS, "P45C value dated bonus statements              ", 837 - 1, 4);
		createCharacterField(FREV, "Force reversal postings                        ", 841 - 1, 1);
		createCharacterField(CPCN, "Enable CP Confirmations                        ", 842 - 1, 1);
		createCharacterField(CPBN, "Enable CP Beneficiary Advices                  ", 843 - 1, 1);
		createCharacterField(CPPR, "Enable CP Pay & Receive Advices                ", 844 - 1, 1);
		createCharacterField(CPBC, "Enable Bank Cheque Advices                     ", 845 - 1, 1);
		createCharacterField(BHOA, "Branch or Head Office Accounting               ", 846 - 1, 2);
		createCharacterField(CPPL, "Calculate & Post Non-Deal FX P&L               ", 848 - 1, 1);
		createCharacterField(BJPO1, "Percentage amount outstanding (LO)             ", 849 - 1, 2);
		createCharacterField(BJPO2, "Percentage amount outstanding (HI)             ", 851 - 1, 2);
		createCharacterField(BJVR1, "Variable 1                                     ", 853 - 1, 2);
		createCharacterField(BJVR2, "Variable 2                                     ", 855 - 1, 2);
		createCharacterField(RPPBK, "Reprint passbook enabled?                      ", 857 - 1, 1);
		createCharacterField(CSLCV, "Cashier local credit validation enabled?       ", 858 - 1, 1);
		createCharacterField(CPAC, "Enable CP Advices/Confirmations in C20         ", 859 - 1, 1);
		createCharacterField(CPPRS, "Enable CP Pay & Receive Advices at Start of Day", 860 - 1, 1);
		createCharacterField(DSIPO, "D17 Suppress if Principal Overdue=0          ", 861 - 1, 1);
		createCharacterField(CPMBE, "Commercial paper multi-branch entry          ", 862 - 1, 1);
		createZonedFieldAsChar(IASND, "No. of interest a/c digits for IAS charge a/c", 863 - 1, 1, 0);
		createCharacterField(MDSHRC, "MDS Hold Reason Code", 864 - 1, 3);
		createCharacterField(MDSDC, "MDS Department Code", 867 - 1, 3);
		createZonedFieldAsChar(MDNRP, "MDS NCA Retention Period", 870 - 1, 2, 0);
		createZonedFieldAsChar(MDARP, "MDS ACIC Retention Period", 872 - 1, 2, 0);
		createZonedFieldAsChar(MDCVP, "MDS Check Validity Period", 874 - 1, 2, 0);
		createCharacterField(MDBBC, "MDS BOT Bank Code", 876 - 1, 2);
		createCharacterField(DSPLC, "Force display of charges", 878 - 1, 1);
		createCharacterField(TNUN, "Transfer non-accrual unearned off balance sheet", 879 - 1, 1);
		createCharacterField(NBDH, "Non-business date start of day holds", 880 - 1, 1);
		createCharacterField(ORACP, "ORF Arabic code page", 881 - 1, 5);
		createCharacterField(FFE, "Force Full Repayment if SC032 = Y", 886 - 1, 1);
		createCharacterField(IRAF, "Inland Revenue Address Format", 887 - 1, 1);
		createCharacterField(SCPT, "Separate charge posting required?", 888 - 1, 1);
		createCharacterField(OUTFMT, "Local clearing outgoing formatter", 889 - 1, 10);
		createCharacterField(OUTADP, "Local clearing outgoing adaptor", 899 - 1, 10);
		createCharacterField(OUTRLT, "Local clearing outgoing in real time", 909 - 1, 1);
		createCharacterField(RETOWF, "Retention period for outgoing work file", 910 - 1, 2);
		createCharacterField(RETIWF, "Retention period for incoming local clearing file", 912 - 1, 2);
		createCharacterField(OUTRTR, "Allow retransmission of LC messages", 914 - 1, 1);
		createCharacterField(LCUNCC, "Live clearing unit cross check", 915 - 1, 3);
		createCharacterField(LCRTCD, "Local clearing DD returns reason code", 918 - 1, 3);
		createCharacterField(LCODTR, "Local clearing outward debit transaction code", 921 - 1, 3);
		createCharacterField(LCOCTR, "Local clearing outward credit transaction code", 924 - 1, 3);
		createCharacterField(OUTACT, "Outward clearing is active", 927 - 1, 1);
		createCharacterField(APPDPD, "Apply deal payments directly?", 928 - 1, 1);
		createCharacterField(DCLACT, "Customer deal clearing account type", 929 - 1, 2);
		createCharacterField(DBCS, "Enhanced API DBCS Support Required", 931 - 1, 1);
		createZonedFieldAsChar(KLPP, "Number of lines per page", 932 - 1, 2, 0);
		createZonedFieldAsChar(KCPL, "Number of characters per line per page", 934 - 1, 3, 0);
		createZonedFieldAsChar(KSTOT, "Statement timeout interval", 937 - 1, 5, 0);
		createCharacterField(PCSSC, "Split service charge", 942 - 1, 1);
		createCharacterField(AFII, "Authorisation for Interest Instructions", 943 - 1, 1);
		createCharacterField(HICP, "Hold Interest Clean Payments", 944 - 1, 1);
		createCharacterField(PACSP, "Print a/c & charges stmts on one paper", 945 - 1, 1);
		createCharacterField(OHBFE, "Online Help Bookmarking Facility Enabled", 946 - 1, 1);
		createZonedFieldAsChar(GTYM, "German tax year start month", 947 - 1, 2, 0);
		createZonedFieldAsChar(GTYD, "German tax year start day", 949 - 1, 2, 0);
		createZonedFieldAsChar(TTHR, "Tax threshold history retention", 951 - 1, 2, 0);
		createZonedFieldAsChar(TTUR, "Tax/threshold utilisation history retention", 953 - 1, 2, 0);
		createCharacterField(AVRL, "Average rate limit", 955 - 1, 2);
		createZonedFieldAsChar(MNTI, "Minimum taxable interest", 957 - 1, 6, 0);
		createZonedFieldAsChar(MXTS, "Maximum tax threshold - Single", 963 - 1, 6, 0);
		createZonedFieldAsChar(MXTJ, "Maximum tax threshold - Joint", 969 - 1, 6, 0);
		createCharacterField(ECCRV, "EC card request record version number", 975 - 1, 8);
		createCharacterField(DIXM, "Default internal transfer method", 983 - 1, 2);
		createCharacterField(DLCXM, "Default local clearing transfer method", 985 - 1, 2);
		createCharacterField(SAPI, "Separate authorisation for principal increase", 987 - 1, 1);
		createCharacterField(EASI, "Enable abbreviated settlement instr", 988 - 1, 1);
		createCharacterField(S24CE, "S24c enabled", 989 - 1, 1);
		createCharacterField(S24CF, "S24c 3rd party format", 990 - 1, 1);
		createCharacterField(DAFCN, "Country code on DAF screen", 991 - 1, 2);
		createZonedFieldAsChar(DAFSN, "Surname field id on DAF screen", 993 - 1, 3, 0);
		createZonedFieldAsChar(DAFFN, "First name field id on DAF screen", 996 - 1, 3, 0);
		createZonedFieldAsChar(DAFHN, "House no field id on DAF screen", 999 - 1, 3, 0);
		createZonedFieldAsChar(DAFPL, "Place field id on DAF screen", 1002 - 1, 3, 0);
		createZonedFieldAsChar(DAFRD, "Road field id on DAF screen                            ", 1005 - 1, 3, 0);
		createZonedFieldAsChar(DAFPC, "Post code field id on DAF screen                       ", 1008 - 1, 3, 0);
		createCharacterField(CIFLF, "Calculate Interest From Last Frequency                 ", 1011 - 1, 1);
		createCharacterField(REPA, "Record event/user and posting audit                    ", 1012 - 1, 1);
		createZonedFieldAsChar(EPRP, "Event/user/posting retention period                    ", 1013 - 1, 2, 0);
		createCharacterField(UNBD, "Use next business day cleared balance                  ", 1015 - 1, 1);
		createCharacterField(PCGRP, "Grouped charge postings                                ", 1016 - 1, 1);
		createCharacterField(PCCDE, "Group charge code                                      ", 1017 - 1, 2);
		createCharacterField(FLACT, "A/C at nostro institution information?.                ", 1019 - 1, 1);
		createZonedFieldAsChar(KWVID, "S24c KWG reporting party's ID                          ", 1020 - 1, 6, 0);
		createCharacterField(SPRT, "Shadow Posting Retention Term                          ", 1026 - 1, 2);
		createCharacterField(FNRD, "Force next rollover date to monthend                   ", 1028 - 1, 1);
		createCharacterField(PCTDC, "Post to cust a/c due to tech def chq                   ", 1029 - 1, 1);
		createCharacterField(DEC, "Default edit code                                      ", 1030 - 1, 1);
		createCharacterField(OPROD, "Use rollover date on cash flows if before maturity date", 1031 - 1, 1);
		createCharacterField(KWVKN, "S24c KWG reporting party's code                        ", 1032 - 1, 4);
		createCharacterField(KWVER, "S24c KWG version of 3rd party software                 ", 1036 - 1, 8);
		createCharacterField(KWLID, "S24c KWG vendor ID                                     ", 1044 - 1, 4);
		createCharacterField(KWFLT, "S24c KWG outgoing transmission folder                  ", 1048 - 1, 60);
		createCharacterField(KWFLR, "S24c KWG incoming transmission folder                  ", 1108 - 1, 60);
		createZonedFieldAsChar(KWMAX, "S24c KWG maximum size of transmission file (Mb)", 1168 - 1, 3, 0);
		createCharacterField(KWRNR, "S24c KWG rename response file flag             ", 1171 - 1, 1);
		createCharacterField(KWDLR, "S24c KWG delete response file flag             ", 1172 - 1, 1);
		createCharacterField(KWTBT, "S24c KWG outgoing data translation table       ", 1173 - 1, 10);
		createCharacterField(KWTBR, "S24c KWG incoming data translation table       ", 1183 - 1, 10);
		createCharacterField(FXNBM, "Non-business day FX movements included?       ", 1193 - 1, 1);
		createCharacterField(TSOS, "Transaction sequence on statements            ", 1194 - 1, 1);
		createCharacterField(RSTMN, "Reset stmt number at start of the year        ", 1195 - 1, 1);
		createCharacterField(ALPAS, "Allow alpha account suffixes?                 ", 1196 - 1, 1);
		createCharacterField(AODA, "Allow o/d defaults on a/c types               ", 1197 - 1, 1);
		createCharacterField(CIFMA, "Cal int on the first month of a/c             ", 1198 - 1, 1);
		createZonedFieldAsChar(S24RP, "S24c transmission file retention period       ", 1199 - 1, 2, 0);
		createCharacterField(BPOST, "Branch postcode identifier                    ", 1201 - 1, 1);
		createCharacterField(BSTRT, "Branch street identifier                      ", 1202 - 1, 1);
		createCharacterField(BTOWN, "Branch town identifier                        ", 1203 - 1, 1);
		createCharacterField(STAX, "Special tax address                           ", 1204 - 1, 1);
		createCharacterField(PALA, "Produce audit letter on account basis         ", 1205 - 1, 1);
		createCharacterField(MCBRPT, "Midas style reporting                         ", 1206 - 1, 1);
		createCharacterField(ASCT, "Account statement charge type                 ", 1207 - 1, 1);
		createZonedFieldAsChar(ASCRP, "Account statement charge data retention period", 1208 - 1, 2, 0);
		createCharacterField(UIF25, "Use IBAN/EAN on Field 25                      ", 1210 - 1, 1);
		createCharacterField(OPSCD, "Suppress OPICS customer details               ", 1211 - 1, 1);
		createCharacterField(OPSCS, "Suppress OPICS cust settlement inst           ", 1212 - 1, 1);
		createCharacterField(OPSSA, "Suppress OPICS cust settlement A/C's          ", 1213 - 1, 1);
		createCharacterField(OPSND, "Suppress nostro details d/l                   ", 1214 - 1, 1);
		createCharacterField(OPSFX, "Suppress FX deal d/l", 1215 - 1, 1);
		createCharacterField(OPSCFD, "Suppress deal cash flow downloads", 1216 - 1, 1);
		createCharacterField(OPSCP, "Suppress currency trading pos'n tf", 1217 - 1, 1);
		createCharacterField(OPSNP, "Suppress EQ/OPICS nostro pos'n tfr", 1218 - 1, 1);
		createCharacterField(OPSSAF, "Suppress OPICS A/C settle d/l reqs", 1219 - 1, 1);
		createCharacterField(OPSFXF, "Suppress FX rate d/l requests", 1220 - 1, 1);
		createCharacterField(OPSRRF, "Suppress retail rate d/l requests", 1221 - 1, 1);
		createCharacterField(OPSMAB, "Suppress movement account balances", 1222 - 1, 1);
		createCharacterField(OPICP, "Immediate d/l of ccy trading pos'n", 1223 - 1, 1);
		createCharacterField(EODM, "End of Day mode", 1224 - 1, 1);
		createCharacterField(TELZ, "Treat expired o/d limit as zero?", 1225 - 1, 1);
		createCharacterField(STDAY, "Start Tax Date (Month)", 1226 - 1, 2);
		createCharacterField(STMON, "Start Tax Date (Day)", 1228 - 1, 2);
		createCharacterField(CPEA, "Positions extract active", 1230 - 1, 1);
		createZonedFieldAsChar(CPDT, "Positions download threshold", 1231 - 1, 15, 0);
		createZonedFieldAsChar(CPCT, "Positions download cut-off time", 1246 - 1, 4, 0);
		createZonedFieldAsChar(CPDF, "Positions download frequency", 1250 - 1, 4, 0);
		createCharacterField(NPEA, "Projections extract active", 1254 - 1, 1);
		createZonedFieldAsChar(NPDT, "Projections download threshold", 1255 - 1, 15, 0);
		createZonedFieldAsChar(NPCT, "Projections download cut-off time", 1270 - 1, 4, 0);
		createZonedFieldAsChar(NPDF, "Projections download frequency", 1274 - 1, 4, 0);
		createCharacterField(PNFC, "Post Narrative For Charges", 1278 - 1, 1);
		createCharacterField(VDC, "Visa electron department code", 1279 - 1, 3);
		createCharacterField(VRH, "Visa electron reason for hold", 1282 - 1, 3);
		createCharacterField(VPAC, "Principal a/c mnemonic", 1285 - 1, 5);
		createCharacterField(VFAC, "Visa fee account mnemonic", 1290 - 1, 5);
		createCharacterField(VSAC, "Visa electron suspense a/c mnemonic", 1295 - 1, 5);
		createCharacterField(VCAC, "Visa electron credit a/c mnemonic", 1300 - 1, 5);
		createCharacterField(EDRC, "EOD Rollback Checkpoints Option         ", 1305 - 1, 1);
		createZonedFieldAsChar(IASAP, "IAS Archive Period                      ", 1306 - 1, 2, 0);
		createCharacterField(MDPAC, "Midas detailed postings account category", 1308 - 1, 5);
		createCharacterField(MDPC, "Midas default profit centre             ", 1313 - 1, 4);
		createZonedFieldAsChar(DCCS, "Default CCSID", 1317 - 1, 5, 0);
		createCharacterField(DSLC1, "Default schema location", 1322 - 1, 20);
		createCharacterField(DSLC2, "Schema location continuation", 1342 - 1, 20);
		createCharacterField(DSLC3, "Schema location continuation", 1362 - 1, 20);
		createCharacterField(DSLC4, "Schema location continuation", 1382 - 1, 20);
		createCharacterField(DSLC5, "Schema location continuation", 1402 - 1, 20);
		createCharacterField(DXML1, "Default XML output location", 1422 - 1, 20);
		createCharacterField(DXML2, "XML output location continuation", 1442 - 1, 20);
		createCharacterField(DXML3, "XML output location continuation", 1462 - 1, 20);
		createCharacterField(DXML4, "XML output location continuation", 1482 - 1, 20);
		createCharacterField(DXML5, "XML output location continuation", 1502 - 1, 20);
		createCharacterField(PIM, "Print Incoming Messages", 1522 - 1, 1);
		createCharacterField(CLSOD, "Repeg CRL deals only during SOD", 1523 - 1, 1);
		createCharacterField(IRRP, "Input reference retention period", 1524 - 1, 4);
		createCharacterField(RTAD, "Allow real time address download?", 1528 - 1, 1);
		createCharacterField(ACRQ, "Account classification required?", 1529 - 1, 1);
		createCharacterField(RTBC, "RTBO Target Balance Calculation", 1530 - 1, 1);
		createCharacterField(ERASD, "Exposure rebuild at Start of Day Y/N?", 1531 - 1, 1);
		createCharacterField(CPSBF, "Commercial paper split by receiver's branch", 1532 - 1, 1);
		createCharacterField(WBLNS, "IFS path for language script", 1533 - 1, 20);
		createCharacterField(DSRCL, "Default source library", 1553 - 1, 10);
		createCharacterField(DSRCF, "Default source file", 1563 - 1, 10);
		createCharacterField(DTRCL, "Default target source library", 1573 - 1, 10);
		createCharacterField(DTSRC, "Default target source file", 1583 - 1, 10);
		createCharacterField(WFAPS, "Webfacing application server", 1593 - 1, 16);
		createCharacterField(WFAPI, "Webfacing application identifier", 1609 - 1, 20);
		createCharacterField(EQSSV, "Equation services server", 1629 - 1, 16);
		createCharacterField(EQSID, "Equation services identifier", 1645 - 1, 20);
		createZonedFieldAsChar(WFAPP, "Webfacing application port", 1665 - 1, 5, 0);
		createZonedFieldAsChar(EQSAP, "Equation services application port", 1670 - 1, 5, 0);
		createCharacterField(EQSUI, "Equation services user ID", 1675 - 1, 10);
		createCharacterField(OPP50, "Protect at Option PIM for Outward", 1685 - 1, 1);
		createCharacterField(IP50, "Protect Ordering Customer Inward ", 1686 - 1, 1);
		createCharacterField(IPP50, "Protect at Option PIM for Inward ", 1687 - 1, 1);
		createCharacterField(KWTFN, "S24c KWG Today's file number     ", 1688 - 1, 3);
		createCharacterField(FXNSM, "FX Netting SODM?                 ", 1691 - 1, 1);
		createCharacterField(SPZCI, "Suppress printing zero chg item", 1692 - 1, 1);
		createCharacterField(PSPBL, "Print selective posting at C45", 1693 - 1, 1);
		createCharacterField(VDAR, "Validate Deal and Account Relationship", 1694 - 1, 1);
		createCharacterField(SPOCH, "Apply DAUD/DAIF with Stop Order", 1695 - 1, 1);
		createCharacterField(MSNDB, "Map sending bank on MT202?", 1696 - 1, 1);
		createCharacterField(FWCDW, "Cashier Draft WLC", 1697 - 1, 1);
		createCharacterField(CSREF, "CRM Referral Message", 1698 - 1, 1);
		createCharacterField(CPUS, "CP User Security Active?", 1699 - 1, 1);
		createCharacterField(SIDD, "Sundry item download delay", 1700 - 1, 2);
		createCharacterField(GSWME, "Gen. MT103 msg though error exists", 1702 - 1, 1);
		createCharacterField(_50F1, "50F Subfield 1 format mask", 1703 - 1, 1);
		createCharacterField(_50F2, "50F Subfield 2 format mask", 1704 - 1, 4);
		createCharacterField(FERHC, "Funding error hold code            ", 1708 - 1, 3);
		createCharacterField(FERDC, "Funding error department code      ", 1711 - 1, 3);
		createCharacterField(DRRP, "Deposit rate table retention period", 1714 - 1, 2);
		createCharacterField(BOHC, "BO from RD hold code               ", 1716 - 1, 3);
		createCharacterField(BODC, "BO from RD department code         ", 1719 - 1, 3);
		createCharacterField(BONHC, "BO from RD negative hold code      ", 1722 - 1, 3);
		createCharacterField(BONDC, "BO from RD negative department code", 1725 - 1, 3);
		createCharacterField(WFHFW, "Header/footer webfacing conversion support", 1728 - 1, 1);
		createCharacterField(CPERR, "Prevent accounting error on clean payment", 1729 - 1, 1);
		createCharacterField(FCLST, "Clear statistics file FKOFSTA", 1730 - 1, 1);
		createCharacterField(ABAD, "Allow SWIFT bulk address download", 1731 - 1, 1);
		createCharacterField(RSOIF, "Retry S/o if failed", 1732 - 1, 1);
		createCharacterField(CPSP, "Print Clean Payment on separate page", 1733 - 1, 1);
		createCharacterField(IPPF, "Ignore Printed on Passbook Field", 1734 - 1, 1);
		createCharacterField(FFFEC, "Use FFF export for ECR Report         ", 1735 - 1, 1);
		createCharacterField(FFFEG, "Use FFF export for EGR Report         ", 1736 - 1, 1);
		createCharacterField(FFFEL, "Use FFF export for ELR Report         ", 1737 - 1, 1);
		createCharacterField(FFFIP, "FFF FTP Server IP                     ", 1738 - 1, 20);
		createCharacterField(FFFDI, "FFF FTP Server Target Directory       ", 1758 - 1, 20);
		createCharacterField(FFFUS, "FFF FTP Server Username               ", 1778 - 1, 20);
		createCharacterField(FFFPW, "FFF FTP Server Password               ", 1798 - 1, 20);
		createCharacterField(FFFFS, "FFF FTP file size limit (in megabytes)", 1818 - 1, 6);
		createCharacterField(FMFTR, "Trace FMF data string", 1824 - 1, 1);
		createZonedFieldAsChar(NPWDA, "Number of password attempts", 1825 - 1, 2, 0);
		createZonedFieldAsChar(DPWDU, "Days for password unlock", 1827 - 1, 2, 0);
		createCharacterField(RCUII, "Reason code for UII loss", 1829 - 1, 3);
		createCharacterField(DDBCS, "Enable DBCS for display files", 1832 - 1, 1);
		createCharacterField(TRLIB, "Translation table library    ", 1833 - 1, 10);
		createCharacterField(TRTBL, "Translation table            ", 1843 - 1, 10);
		createCharacterField(FFFTR, "Trace FFF data string", 1853 - 1, 1);
		createCharacterField(DF71A, "Use BEN as default charges for field 71A", 1854 - 1, 1);
		createCharacterField(TCHR, "Tax calculation using historical rates", 1855 - 1, 1);
		createCharacterField(RLSEL, "Allow selection for schedule recalculation", 1856 - 1, 1);
		createCharacterField(NBDGD, "Grace day if repayment on NBD", 1857 - 1, 1);
		createCharacterField(NBDST, "Status if repayment on NBD   ", 1858 - 1, 1);
		createCharacterField(URTM, "Unknown rate table method", 1859 - 1, 1);
		createCharacterField(BSNG, "Branch specific netting groups", 1860 - 1, 1);
		createCharacterField(SFAD, "Specify funds availability days", 1861 - 1, 1);
		createCharacterField(D13DC, "Display DR/CR in the D13ARCC report?", 1862 - 1, 1);
		createCharacterField(ESUMI, "Enable SUMMIT interface", 1863 - 1, 1);
		createCharacterField(SSUMC, "Suppress SUMMIT customers", 1864 - 1, 1);
		createCharacterField(SSUMD, "Suppress SUMMIT deals", 1865 - 1, 1);
		createCharacterField(SSUMA, "Suppress SUMMIT account balances", 1866 - 1, 1);
		createCharacterField(RNFXP, "Record non-deal FX in PA", 1867 - 1, 1);
		createCharacterField(FXCD, "FX profitability on contract date", 1868 - 1, 1);
		createCharacterField(UIIR, "UII history retention period", 1869 - 1, 3);
		createCharacterField(FBBC, "FUND B/O BALANCE CALCULATION", 1872 - 1, 1);
		createCharacterField(BPL, "Backup payroll libraries?", 1873 - 1, 1);
		createCharacterField(RCCID, "Reset Default CCSID", 1874 - 1, 1);
		createCharacterField(FWERR, "Enable CP WLC error message", 1875 - 1, 1);
		createCharacterField(PCRTN, "Stop input of 014/024 w/o Cheque itm.", 1876 - 1, 1);
		createCharacterField(ESABO, "Exclude Shadow Adjustment on Balance Order", 1877 - 1, 1);
		createCharacterField(CCOY, "Century cut-off year", 1878 - 1, 2);
		createCharacterField(FNAL1, "Release local cheque funds", 1880 - 1, 20);
		createCharacterField(FNAL2, "Capitalise int for back valued tran?", 1900 - 1, 20);
		createCharacterField(FNAL3, "Number of times to retry connection", 1920 - 1, 20);
		createCharacterField(RLCF, "Post Future Dated Charges Instantly", 1940 - 1, 1);
		createCharacterField(CBVT, "FircoSoft Matching Algorithm codes Line 1", 1941 - 1, 1);
		createZonedFieldAsChar(FTRYT, "FircoSoft Matching Algorithm codes Line 2", 1942 - 1, 3, 0);
		createCharacterField(PFDC, "FircoSoft Matching Algorithm codes Line 3", 1945 - 1, 1);
		createCharacterField(IPDF, "IPD P&L forecast method", 1946 - 1, 1);
		createCharacterField(IPKJ, "IPD product balance forecast method", 1947 - 1, 1);
		createCharacterField(IPRT, "IPD pool calculation retention period", 1948 - 1, 2);
		createCharacterField(IPDR, "IPD detailed history retention period", 1950 - 1, 2);
		createCharacterField(INBD, "IPD next profit period end date      ", 1952 - 1, 1);
		createZonedFieldAsChar(IPDO, "IPD offset                           ", 1953 - 1, 2, 0);
		createCharacterField(IPDA, "IPD manual approval required         ", 1955 - 1, 1);
		createCharacterField(IPRR, "IPD payment release required         ", 1956 - 1, 1);
		createCharacterField(IPJD, "IPD job description                  ", 1957 - 1, 10);
		createCharacterField(DUM2, "DUM2", 1967 - 1, 1);
		createCharacterField(CFPRI, "Enable credit facility prioritisation", 1968 - 1, 1);
		createCharacterField(CIACV, "Enable collateral item addition coverage", 1969 - 1, 1);
		createCharacterField(VDIFT, "Value Date for ITA FX Transactions", 1970 - 1, 1);
		createZonedFieldAsChar(SACID, "Suspicious Activity data CCSID", 1971 - 1, 5, 0);
		createCharacterField(DUM3, "DUM3", 1976 - 1, 2);
		createCharacterField(CVDS, "Collect value dated statistics for Islamic accounts only", 1978 - 1, 1);
		createCharacterField(AIKE, "Allow issue KAP0030 msg during EOD", 1979 - 1, 1);
		createCharacterField(DUM4, "DUM4", 1980 - 1, 2);
		createCharacterField(CACCI, "Calculate accrued int for closing MMBI accounts?", 1982 - 1, 1);
		createCharacterField(DUM5, "DUM5", 1983 - 1, 1);
		createCharacterField(PDT, "Print Desktop Transaction (Y/N)?", 1984 - 1, 1);
		createCharacterField(AMSI, "Apportion manual schedule interest", 1985 - 1, 1);

		// final setup
		initialDefaultValue();
	}

}
